from __future__ import annotations

from types import SimpleNamespace

def _dialog_step_0007(_state):
    _state.placement_tree.setAlternatingRowColors(True)
    _state.placement_tree.setUniformRowHeights(True)
    _state.placement_tree.setSelectionMode(_state.QAbstractItemView.SelectionMode.SingleSelection)
    _state.self._populate_attachment_placement_dialog_tree(_state.placement_tree, _state.hkx_attachment_graph)
    _state.placement_tree.header().setStretchLastSection(True)
    _state.placement_tree.header().resizeSection(0, 180)
    _state.placement_tree.header().resizeSection(1, 300)
    _state.placement_tree.header().resizeSection(2, 130)
    _state.placement_left_splitter.addWidget(_state.placement_tree)
    _state.placement_context_tabs = _state.QTabWidget()
    _state.placement_socket_page = _state.QWidget()
    _state.placement_socket_layout = _state.QVBoxLayout(_state.placement_socket_page)
    _state.placement_socket_layout.setContentsMargins(0, 0, 0, 0)
    _state.placement_socket_layout.setSpacing(6)
    _state.placement_socket_summary = _state.QLabel("Select a placement chain to inspect resolved socket XML rows.")
    _state.placement_socket_summary.setObjectName("HintLabel")
    _state.placement_socket_summary.setWordWrap(True)
    _state.placement_socket_summary.setTextInteractionFlags(_state.Qt.TextInteractionFlag.TextSelectableByMouse)
    _state.placement_socket_layout.addWidget(_state.placement_socket_summary)
    _state.placement_socket_tree = _state.QTreeWidget()
    _state.placement_socket_tree.setColumnCount(5)
    _state.placement_socket_tree.setHeaderLabels(["Socket", "Parent", "Translation", "Rotation", "Source"])
    _state.placement_socket_tree.setRootIsDecorated(False)
    _state.placement_socket_tree.setAlternatingRowColors(True)
    _state.placement_socket_tree.setUniformRowHeights(True)
    _state.placement_socket_tree.setSelectionMode(_state.QAbstractItemView.SelectionMode.SingleSelection)
    _state.placement_socket_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.placement_socket_layout.addWidget(_state.placement_socket_tree, stretch=1)
    _state.placement_context_tabs.addTab(_state.placement_socket_page, "Socket Details")
    _state.placement_related_tree = _state.QTreeWidget()
    _state.placement_related_tree.setColumnCount(5)
    _state.placement_related_tree.setHeaderLabels(["Role", "File", "Status", "Evidence", "Why"])
    _state.placement_related_tree.setRootIsDecorated(True)
    _state.placement_related_tree.setAlternatingRowColors(True)
    _state.placement_related_tree.setUniformRowHeights(True)
    _state.placement_related_tree.setSelectionMode(_state.QAbstractItemView.SelectionMode.SingleSelection)
    _state.placement_related_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.self._populate_asset_family_dialog_tree(_state.placement_related_tree, _state.hkx_attachment_graph)
    _state.placement_related_tree.header().setStretchLastSection(True)
    _state.placement_related_tree.header().resizeSection(0, 140)
    _state.placement_related_tree.header().resizeSection(1, 260)
    _state.placement_context_tabs.addTab(_state.placement_related_tree, "Related Files")
    _state.placement_left_splitter.addWidget(_state.placement_context_tabs)
    _state.placement_left_splitter.setStretchFactor(0, 2)
    _state.placement_left_splitter.setStretchFactor(1, 1)
    _state.placement_left_layout.addWidget(_state.placement_left_splitter, stretch=1)
    _state.placement_button_row = _state.QHBoxLayout()
    _state.placement_edit_socket_button = _state.QPushButton("Edit Socket Values...")
    _state.placement_edit_socket_button.setToolTip(
        "Manual socket value editor. Normal placement swaps should start with Choose Placement Source."
    )
    _state.placement_related_button = _state.QPushButton("Related Files")
    _state.placement_related_button.setToolTip("Show the inline asset family evidence for this HKX.")
    _state.placement_button_row.addWidget(_state.placement_edit_socket_button)
    _state.placement_button_row.addWidget(_state.placement_related_button)
    _state.placement_button_row.addStretch(1)
    _state.placement_left_layout.addLayout(_state.placement_button_row)
    _state.placement_swap_hint = _state.QLabel("Disabled - WIP. Placement swap/package flow is paused until this workflow is ready again.")
    _state.placement_swap_hint.setObjectName("HintLabel")
    _state.placement_swap_hint.setWordWrap(True)
    _state.placement_left_layout.addWidget(_state.placement_swap_hint)
    _state.placement_splitter.addWidget(_state.placement_left_panel)

    _state.placement_swap_panel = _state.QWidget()
    _state.placement_swap_layout = _state.QVBoxLayout(_state.placement_swap_panel)
    _state.placement_swap_layout.setContentsMargins(8, 0, 0, 0)
    _state.placement_swap_layout.setSpacing(8)
    _state.placement_swap_title = _state.QLabel("Placement Swap (Disabled - WIP)")
    _state.placement_swap_title.setStyleSheet("font-weight: 600;")
    _state.placement_swap_layout.addWidget(_state.placement_swap_title)
    _state.placement_swap_summary = _state.QLabel("")
    _state.placement_swap_summary.setObjectName("HintLabel")
    _state.placement_swap_summary.setWordWrap(True)
    _state.placement_swap_summary.setTextInteractionFlags(_state.Qt.TextInteractionFlag.TextSelectableByMouse)
    _state.placement_swap_layout.addWidget(_state.placement_swap_summary)
    _state.placement_swap_steps = _state.QTreeWidget()
    _state.placement_swap_steps.setColumnCount(4)
    _state.placement_swap_steps.setHeaderLabels(["Input", "Resolved Value", "Used For", "Status"])
    _state.placement_swap_steps.setRootIsDecorated(False)
    _state.placement_swap_steps.setAlternatingRowColors(True)
    _state.placement_swap_steps.setUniformRowHeights(True)
    _state.placement_swap_steps.setSelectionMode(_state.QAbstractItemView.SelectionMode.SingleSelection)
    _state.placement_swap_steps.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.placement_swap_steps.header().setStretchLastSection(True)
    _state.placement_swap_steps.header().resizeSection(0, 160)
    _state.placement_swap_steps.header().resizeSection(1, 360)
    _state.placement_swap_steps.header().resizeSection(2, 240)
    _state.placement_swap_layout.addWidget(_state.placement_swap_steps, stretch=1)
    _state.placement_swap_action_label = _state.QLabel("Disabled - WIP. Choosing placement sources and building placement-copy packages is paused.")
    _state.placement_swap_action_label.setObjectName("HintLabel")
    _state.placement_swap_action_label.setWordWrap(True)
    _state.placement_swap_layout.addWidget(_state.placement_swap_action_label)
    _state.placement_swap_button_row = _state.QHBoxLayout()
    _state.placement_swap_copy_button = _state.QPushButton("Choose Placement Source (Disabled - WIP)")
    _state.placement_swap_copy_button.setToolTip("Disabled - WIP. Placement source comparison/package flow is paused.")
    _state.placement_swap_copy_button.setEnabled(False)
    _state.placement_swap_related_button = _state.QPushButton("Show Related Files")
    _state.placement_swap_related_button.setToolTip("Inspect the files used to infer this placement chain.")
    _state.placement_swap_button_row.addWidget(_state.placement_swap_copy_button)
    _state.placement_swap_button_row.addWidget(_state.placement_swap_related_button)
    _state.placement_swap_button_row.addStretch(1)
    _state.placement_swap_layout.addLayout(_state.placement_swap_button_row)
    _state.placement_splitter.addWidget(_state.placement_swap_panel)
    _state.placement_splitter.setStretchFactor(0, 1)
    _state.placement_splitter.setStretchFactor(1, 2)
    _state.placement_layout.addWidget(_state.placement_splitter, stretch=1)
    _state.placement_tab_index = _state.tab_widget.addTab(_state.placement_page, "Placement (Disabled - WIP)")
    _state.tab_widget.setTabToolTip(_state.placement_tab_index, "Disabled - WIP. Placement swap/package flow is paused.")
    _state.tab_widget.setTabEnabled(_state.placement_tab_index, False)
    _state.placement_page.setEnabled(False)

STEPS = (_dialog_step_0007,)
