from __future__ import annotations

from types import SimpleNamespace

def _dialog_step_0001(_state):
    _state.dialog = _state.QDialog(_state.self)
    _state.dialog.setWindowTitle(f"Edit HKX - {_state.entry.basename}")
    _state.dialog.resize(1360, 860)

    _state.layout = _state.QVBoxLayout(_state.dialog)
    _state.layout.setContentsMargins(12, 12, 12, 12)
    _state.layout.setSpacing(8)

    _state.hint = _state.QLabel(
        "CDMW HKX patch view. Only blue patchable numeric rows are import-safe; Havok-style XML remains read-only."
    )
    _state.hint.setWordWrap(True)
    _state.hint.setToolTip(
        "Descriptions and notes are ignored on import. Supported edits are written as a loose mod package without changing game archives."
    )
    _state.layout.addWidget(_state.hint)

    _state.workspace_splitter = _state.QSplitter(_state.Qt.Orientation.Horizontal)
    _state.layout.addWidget(_state.workspace_splitter, stretch=1)

    _state.browser_panel = _state.QWidget()
    _state.browser_layout = _state.QVBoxLayout(_state.browser_panel)
    _state.browser_layout.setContentsMargins(4, 2, 8, 4)
    _state.browser_layout.setSpacing(7)
    _state.browser_title = _state.QLabel("HKX Views")
    _state.browser_title.setStyleSheet("font-weight: 600;")
    _state.browser_layout.addWidget(_state.browser_title)
    _state.browser_summary_label = _state.QLabel(
        "Focused views first. Advanced decoded rows are hidden below."
    )
    _state.browser_summary_label.setObjectName("HintLabel")
    _state.browser_summary_label.setWordWrap(True)
    _state.browser_summary_label.setContentsMargins(2, 0, 2, 2)
    _state.browser_layout.addWidget(_state.browser_summary_label)
    _state.section_nav_list = _state.QListWidget()
    _state.section_nav_list.setAlternatingRowColors(True)
    _state.section_nav_list.setUniformItemSizes(True)
    _state.section_nav_list.setSelectionMode(_state.QAbstractItemView.SelectionMode.SingleSelection)
    _state.section_nav_list.setMinimumHeight(230)
    _state.section_nav_list.setToolTip("Switch between HKX views without opening the compact drop-down selector.")
    _state.browser_layout.addWidget(_state.section_nav_list)
    _state.section_advanced_views_toggle = _state.QCheckBox("Show advanced views")
    _state.section_advanced_views_toggle.setToolTip(
        "Show lower-level object layout, context, catalog, and byte-map views. The main workflow views remain visible by default."
    )
    _state.browser_layout.addWidget(_state.section_advanced_views_toggle)
    _state.browser_advanced_toggle = _state.QCheckBox("Show decoded row browser")
    _state.browser_advanced_toggle.setToolTip(
        "Advanced fallback: browse every decoded HKX row, object, and relationship edge. Most users should start with the focused views above."
    )
    _state.browser_layout.addWidget(_state.browser_advanced_toggle)
    _state.browser_advanced_panel = _state.QWidget()
    _state.browser_advanced_layout = _state.QVBoxLayout(_state.browser_advanced_panel)
    _state.browser_advanced_layout.setContentsMargins(0, 0, 0, 0)
    _state.browser_advanced_layout.setSpacing(6)
    _state.browser_advanced_panel.setVisible(False)
    _state.browser_filter_row = _state.QVBoxLayout()
    _state.browser_filter_row.setSpacing(4)
    _state.browser_filter_edit = _state.QLineEdit()
    _state.browser_filter_edit.setPlaceholderText("Filter decoded rows")
    _state.browser_filter_edit.setSizePolicy(_state.QSizePolicy.Policy.Expanding, _state.QSizePolicy.Policy.Fixed)
    _state.browser_follow_selection_checkbox = _state.QCheckBox("Follow selection")
    _state.browser_follow_selection_checkbox.setChecked(True)
    _state.browser_follow_selection_checkbox.setToolTip("Automatically open the linked view when a navigator row maps to an editor row.")
    _state.browser_follow_preview_checkbox = _state.QCheckBox("Follow 3D")
    _state.browser_follow_preview_checkbox.setChecked(False)
    _state.browser_follow_preview_checkbox.setToolTip(
        "Automatically highlight a recovered 3D physics target only when a matching preview is already loaded. "
        "It does not open the embedded 3D Preview pane by itself."
    )
    _state.browser_editable_only_checkbox = _state.QCheckBox("Patchable only")
    _state.browser_editable_only_checkbox.setToolTip("Show rows with safe patch targets only.")
    _state.browser_preview_linked_checkbox = _state.QCheckBox("3D-linked rows")
    _state.browser_preview_linked_checkbox.setToolTip(
        "Show rows with a recovered visible shape, constraint, anchor, or bone target. "
        "If a matching 3D preview is loaded, rows for missing targets are hidden."
    )
    _state.browser_decoded_only_checkbox = _state.QCheckBox("Decoded/context only")
    _state.browser_decoded_only_checkbox.setToolTip("Hide raw-preserved rows and show decoded/inferred rows.")
    _state.browser_raw_preserved_checkbox = _state.QCheckBox("Raw/unknown only")
    _state.browser_raw_preserved_checkbox.setToolTip("Show raw-preserved rows and unknown schema areas.")
    for _state.checkbox in (
        _state.browser_follow_selection_checkbox,
        _state.browser_follow_preview_checkbox,
        _state.browser_editable_only_checkbox,
        _state.browser_preview_linked_checkbox,
        _state.browser_decoded_only_checkbox,
        _state.browser_raw_preserved_checkbox,
    ):
        _state.checkbox.setSizePolicy(_state.QSizePolicy.Policy.MinimumExpanding, _state.QSizePolicy.Policy.Fixed)
        _state.checkbox.setMinimumWidth(max(_state.checkbox.sizeHint().width() + 12, 104))
    _state.browser_toggle_row = _state.QGridLayout()
    _state.browser_toggle_row.setContentsMargins(0, 0, 0, 0)
    _state.browser_toggle_row.setHorizontalSpacing(18)
    _state.browser_toggle_row.setVerticalSpacing(2)
    _state.browser_toggle_row.addWidget(_state.browser_follow_selection_checkbox, 0, 0)
    _state.browser_toggle_row.addWidget(_state.browser_follow_preview_checkbox, 0, 1)
    _state.browser_toggle_row.addWidget(_state.browser_editable_only_checkbox, 1, 0)
    _state.browser_toggle_row.addWidget(_state.browser_preview_linked_checkbox, 1, 1)
    _state.browser_toggle_row.addWidget(_state.browser_decoded_only_checkbox, 2, 0)
    _state.browser_toggle_row.addWidget(_state.browser_raw_preserved_checkbox, 2, 1)
    _state.browser_toggle_row.setColumnStretch(1, 1)
    _state.browser_filter_row.addWidget(_state.browser_filter_edit)
    _state.browser_filter_row.addLayout(_state.browser_toggle_row)
    _state.browser_advanced_layout.addLayout(_state.browser_filter_row)
    _state.hkx_browser_tree = _state.QTreeWidget()
    _state.hkx_browser_tree.setColumnCount(4)
    _state.hkx_browser_tree.setHeaderLabels(("Item", "Role / Class", "Value", "Status"))
    _state.hkx_browser_tree.setAlternatingRowColors(True)
    _state.hkx_browser_tree.setUniformRowHeights(True)
    _state.hkx_browser_tree.setRootIsDecorated(True)
    _state.hkx_browser_tree.setSortingEnabled(False)
    _state.hkx_browser_tree.setSelectionMode(_state.QAbstractItemView.SelectionMode.SingleSelection)
    _state.browser_advanced_layout.addWidget(_state.hkx_browser_tree, stretch=1)
    _state.browser_button_row = _state.QHBoxLayout()
    _state.browser_show_editor_button = _state.QPushButton("Open Owning Editor")
    _state.browser_show_editor_button.setToolTip("Open the linked HKX view that owns the selected navigator row.")
    _state.browser_show_xml_button = _state.QPushButton("Open XML")
    _state.browser_show_xml_button.setToolTip("Search the XML / Raw section for the selected row's patch path, ID, or label.")

def _dialog_step_0002(_state):
    _state.browser_show_preview_button = _state.QPushButton("Show in 3D")
    _state.browser_show_preview_button.setToolTip("Open the 3D Preview pane and highlight the selected decoded shape, constraint, anchor, or bone when a mapping is available.")
    _state.browser_button_row.addWidget(_state.browser_show_editor_button)
    _state.browser_button_row.addWidget(_state.browser_show_xml_button)
    _state.browser_button_row.addWidget(_state.browser_show_preview_button)
    _state.browser_advanced_layout.addLayout(_state.browser_button_row)
    _state.browser_status_label = _state.QLabel("")
    _state.browser_status_label.setWordWrap(True)
    _state.browser_status_label.setContentsMargins(6, 4, 6, 4)
    _state.browser_status_label.setFrameShape(_state.QFrame.Shape.StyledPanel)
    _state.browser_advanced_layout.addWidget(_state.browser_status_label)
    _state.browser_layout.addWidget(_state.browser_advanced_panel, stretch=1)
    _state.workspace_splitter.addWidget(_state.browser_panel)

    _state.right_panel = _state.QWidget()
    _state.right_layout = _state.QVBoxLayout(_state.right_panel)
    _state.right_layout.setContentsMargins(10, 2, 8, 4)
    _state.right_layout.setSpacing(7)
    _state.section_row = _state.QGridLayout()
    _state.section_row.setContentsMargins(0, 0, 0, 0)
    _state.section_row.setHorizontalSpacing(6)
    _state.section_row.setVerticalSpacing(2)
    _state.section_label = _state.QLabel("View")
    _state.section_label.setObjectName("HintLabel")
    _state.section_combo = _state.QComboBox()
    _state.section_combo.setMinimumContentsLength(24)
    _state.section_combo.setMinimumWidth(280)
    _state.section_combo.setSizeAdjustPolicy(_state.QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
    _state.section_combo.setToolTip(
        "Switch between linked HKX views. Counts in parentheses show decoded rows and visible rows where available."
    )
    _state.section_combo.setVisible(False)
    _state.section_current_label = _state.QLabel("Modding Workspace")
    _state.section_current_label.setStyleSheet("font-weight: 600;")
    _state.section_current_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Fixed)
    _state.preview_toggle_button = _state.QPushButton("Show 3D")
    _state.preview_toggle_button.setCheckable(True)
    _state.preview_toggle_button.setMinimumWidth(92)
    _state.preview_toggle_button.setToolTip("Show or hide the optional 3D Preview pane. Keep it hidden when you only want the linked editor/table views.")
    _state.section_summary_label = _state.QLabel("")
    _state.section_summary_label.setObjectName("HintLabel")
    _state.section_summary_label.setWordWrap(True)
    _state.section_summary_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Preferred)
    _state.section_row.addWidget(_state.section_label, 0, 0)
    _state.section_row.addWidget(_state.section_current_label, 0, 1)
    _state.section_row.addWidget(_state.preview_toggle_button, 0, 2)
    _state.section_row.addWidget(_state.section_summary_label, 1, 0, 1, 3)
    _state.section_row.setColumnMinimumWidth(0, 84)
    _state.section_row.setColumnStretch(1, 1)
    _state.right_layout.addLayout(_state.section_row)
    _state.hkx_editor_legend = _state.QLabel(
        "Blue values are patchable. Grey/context and yellow/red rows are evidence only."
    )
    _state.hkx_editor_legend.setObjectName("HintLabel")
    _state.hkx_editor_legend.setWordWrap(True)
    _state.hkx_editor_legend.setToolTip(
        "Mesh primitive tuple rows only allow winding/order changes. Array counts, references, strings, and topology changes remain blocked."
    )
    _state.right_layout.addWidget(_state.hkx_editor_legend)
    _state.tab_widget = _state.QTabWidget()
    _state.tab_widget.tabBar().hide()
    _state.right_layout.addWidget(_state.tab_widget, stretch=1)
    _state.comparison_text = _state.QPlainTextEdit()
    _state.comparison_text.setReadOnly(True)
    _state.comparison_text.setMaximumHeight(64)
    _state.comparison_text.setLineWrapMode(_state.QPlainTextEdit.LineWrapMode.WidgetWidth)
    _state.comparison_text.setPlaceholderText("Select a value, relationship, or decoded row to see original/current value, confidence, risk, byte offset, and editing guidance.")
    _state.right_layout.addWidget(_state.comparison_text)
    _state.workspace_splitter.addWidget(_state.right_panel)

    _state.overview_page = _state.QWidget()
    _state.overview_layout = _state.QVBoxLayout(_state.overview_page)
    _state.overview_layout.setContentsMargins(0, 0, 0, 0)
    _state.overview_layout.setSpacing(6)
    _state.workflow_guide_label = _state.QLabel(
        "Recovered readable areas. Counts are evidence, not certainty."
    )
    _state.workflow_guide_label.setWordWrap(True)
    _state.workflow_guide_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Fixed)
    _state.workflow_guide_label.setMaximumHeight(36)
    _state.modding_readiness_label = _state.QLabel("")
    _state.modding_readiness_label.setObjectName("HintLabel")
    _state.modding_readiness_label.setWordWrap(True)
    _state.modding_readiness_label.setMaximumHeight(44)
    _state.modding_readiness_label.setToolTip(
        "Per-file HKX modding readiness. Patchable means fixed-size CDMW patch rows only; Havok XML remains read-only."
    )
    _state.overview_layout.addWidget(_state.modding_readiness_label)
    _state.modding_workspace_status_label = _state.QLabel("HKX Edit Readiness")
    _state.modding_workspace_status_label.setObjectName("HintLabel")
    _state.modding_workspace_status_label.setWordWrap(True)
    _state.modding_workspace_status_label.setMaximumHeight(42)
    _state.overview_layout.addWidget(_state.modding_workspace_status_label)
    _state.overview_workspace_tabs = _state.QTabWidget()
    _state.overview_workspace_tabs.setDocumentMode(True)
    _state.overview_layout.addWidget(_state.overview_workspace_tabs, stretch=1)
    _state.workspace_values_page = _state.QWidget()
    _state.workspace_values_layout = _state.QVBoxLayout(_state.workspace_values_page)
    _state.workspace_values_layout.setContentsMargins(0, 0, 0, 0)
    _state.workspace_values_layout.setSpacing(6)
    _state.workspace_toolbar = _state.QGridLayout()
    _state.workspace_toolbar.setContentsMargins(0, 0, 0, 0)
    _state.workspace_toolbar.setHorizontalSpacing(8)
    _state.workspace_toolbar.setVerticalSpacing(4)
    _state.workspace_task_label = _state.QLabel("Task")
    _state.workspace_task_label.setObjectName("HintLabel")
    _state.workspace_task_combo = _state.QComboBox()
    _state.workspace_task_combo.setToolTip("Filter the HKX Modding Workspace to a practical physics tuning task.")
    _state.workspace_task_combo.addItem("Collision Size", "collision_size")
    _state.workspace_task_combo.addItem("Body Transform", "body_transform")
    _state.workspace_task_combo.addItem("Joint Strength", "joint_strength")
    _state.workspace_task_combo.addItem("Damping / Motion", "damping_motion")
    _state.workspace_task_combo.addItem("Material / Friction", "material_friction")
    _state.workspace_task_combo.addItem("Mesh Winding", "mesh_winding")
    _state.workspace_task_combo.addItem("Inspect Only", "inspect_only")
    _state.workspace_filter_edit = _state.QLineEdit()
    _state.workspace_filter_edit.setPlaceholderText("Filter workspace rows")

def _dialog_step_0003(_state):
    _state.workflow_summary_toggle = _state.QCheckBox("Readable areas")
    _state.workflow_summary_toggle.setToolTip("Show the readable-area summary and helper actions. Hidden by default so the value list has more room.")
    _state.workflow_summary_toggle.setVisible(False)
    _state.workspace_toolbar.addWidget(_state.workspace_task_label, 0, 0)
    _state.workspace_toolbar.addWidget(_state.workspace_task_combo, 0, 1)
    _state.workspace_toolbar.addWidget(_state.workspace_filter_edit, 0, 2)
    _state.workspace_toolbar.setColumnStretch(2, 1)
    _state.workspace_values_layout.addLayout(_state.workspace_toolbar)
    _state.modding_workspace_tree = _state.QTreeWidget()
    _state.modding_workspace_tree.setColumnCount(10)
    _state.modding_workspace_tree.setHeaderLabels(
        (
            "Meaning",
            "Import safety",
            "Risk",
            "Evidence",
            "Linked by",
            "Record",
            "Offset",
            "Original",
            "Current",
            "Details",
        )
    )
    _state.modding_workspace_tree.setAlternatingRowColors(True)
    _state.modding_workspace_tree.setUniformRowHeights(True)
    _state.modding_workspace_tree.setRootIsDecorated(True)
    _state.modding_workspace_tree.setSortingEnabled(True)
    _state.modding_workspace_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.modding_workspace_tree.setToolTip(
        "Patchable rows are shown first, read-only candidate rows second, and structural blocked rows are evidence only. Fixed numeric values are the only import-safe write class here."
    )
    _state.modding_workspace_tree.setMinimumHeight(260)
    _state.workspace_values_layout.addWidget(_state.modding_workspace_tree, stretch=1)
    _state.modding_workspace_detail_text = _state.QPlainTextEdit()
    _state.modding_workspace_detail_text.setReadOnly(True)
    _state.modding_workspace_detail_text.setMaximumHeight(68)
    _state.modding_workspace_detail_text.setSizePolicy(_state.QSizePolicy.Policy.Expanding, _state.QSizePolicy.Policy.Fixed)
    _state.modding_workspace_detail_text.setLineWrapMode(_state.QPlainTextEdit.LineWrapMode.WidgetWidth)
    _state.modding_workspace_detail_text.setPlaceholderText(
        "Select a workspace row to see Meaning, Import safety, Risk, Evidence, Linked by, Record, Offset, Original, and Current value."
    )
    _state.workspace_values_layout.addWidget(_state.modding_workspace_detail_text)
    _state.overview_workspace_tabs.addTab(_state.workspace_values_page, "Values")
    _state.workflow_summary_page = _state.QWidget()
    _state.workflow_summary_layout = _state.QVBoxLayout(_state.workflow_summary_page)
    _state.workflow_summary_layout.setContentsMargins(0, 0, 0, 0)
    _state.workflow_summary_layout.setSpacing(6)
    _state.workflow_guide_tree = _state.QTreeWidget()
    _state.workflow_guide_tree.setColumnCount(6)
    _state.workflow_guide_tree.setHeaderLabels(("Area", "Useful Values", "Safe", "Context", "Risk", "Meaning"))
    _state.workflow_guide_tree.setAlternatingRowColors(True)
    _state.workflow_guide_tree.setUniformRowHeights(True)
    _state.workflow_guide_tree.setRootIsDecorated(False)
    _state.workflow_guide_tree.setSortingEnabled(False)
    _state.workflow_guide_tree.setMinimumHeight(220)
    _state.workflow_guide_tree.setSizePolicy(_state.QSizePolicy.Policy.Expanding, _state.QSizePolicy.Policy.Expanding)
    _state.workflow_guide_tree.setSelectionMode(_state.QAbstractItemView.SelectionMode.SingleSelection)
    _state.workflow_summary_layout.addWidget(_state.workflow_guide_label)
    _state.workflow_summary_layout.addWidget(_state.workflow_guide_tree, stretch=1)
    _state.workflow_detail_text = _state.QPlainTextEdit()
    _state.workflow_detail_text.setReadOnly(True)
    _state.workflow_detail_text.setMaximumHeight(64)
    _state.workflow_detail_text.setSizePolicy(_state.QSizePolicy.Policy.Expanding, _state.QSizePolicy.Policy.Fixed)
    _state.workflow_detail_text.setLineWrapMode(_state.QPlainTextEdit.LineWrapMode.WidgetWidth)
    _state.workflow_detail_text.setPlaceholderText(
        "Select an area above to see what is import-safe, what is context only, and what remains inferred."
    )
    _state.workflow_summary_layout.addWidget(_state.workflow_detail_text)
    _state.workflow_guide_button_row = _state.QHBoxLayout()
    _state.workflow_show_values_button = _state.QPushButton("Filter Values")
    _state.workflow_show_values_button.setToolTip("Filter the owning editor to rows related to the selected area.")
    _state.workflow_show_connected_button = _state.QPushButton("Show Relationships")
    _state.workflow_show_connected_button.setToolTip("Open Connected Physics with the selected area as a context filter.")
    _state.workflow_show_safe_catalog_button = _state.QPushButton("Safe Rows Only")
    _state.workflow_show_safe_catalog_button.setToolTip("Open the Patchable Catalog filtered to import-safe patch targets related to the selected area.")
    _state.workflow_show_guide_button = _state.QPushButton("Technical Details")
    _state.workflow_show_guide_button.setToolTip("Show the detailed decoder report for this HKX.")
    _state.workflow_guide_button_row.addWidget(_state.workflow_show_values_button)
    _state.workflow_guide_button_row.addWidget(_state.workflow_show_connected_button)
    _state.workflow_guide_button_row.addWidget(_state.workflow_show_safe_catalog_button)
    _state.workflow_guide_button_row.addWidget(_state.workflow_show_guide_button)
    _state.workflow_guide_button_row.addStretch(1)
    _state.workflow_summary_layout.addLayout(_state.workflow_guide_button_row)
    _state.overview_workspace_tabs.addTab(_state.workflow_summary_page, "Readable Areas")
    _state.overview_report_page = _state.QWidget()
    _state.overview_report_layout = _state.QVBoxLayout(_state.overview_report_page)
    _state.overview_report_layout.setContentsMargins(0, 0, 0, 0)
    _state.overview_report_layout.setSpacing(6)
    _state.overview_report_toggle = _state.QCheckBox("Show technical details")
    _state.overview_report_toggle.setToolTip("Show detailed converter status, decode gaps, fixup proof, and corpus/readiness notes.")
    _state.overview_report_toggle.setVisible(False)
    _state.overview_text = _state.QPlainTextEdit()
    _state.overview_text.setReadOnly(True)
    _state.overview_text.setFont(_state.build_monospace_font(_state.self.settings))
    _state.overview_report_layout.addWidget(_state.overview_text, stretch=1)
    _state.overview_workspace_tabs.addTab(_state.overview_report_page, "Technical Details")
    _state.overview_filler = _state.QWidget()
    _state.overview_filler.setSizePolicy(_state.QSizePolicy.Policy.Expanding, _state.QSizePolicy.Policy.Expanding)
    _state.overview_filler.setVisible(False)
    _state.overview_layout.addWidget(_state.overview_filler, stretch=1)
    _state.tab_widget.addTab(_state.overview_page, "Modding Workspace")

    _state.tuning_page = _state.QWidget()
    _state.tuning_layout = _state.QVBoxLayout(_state.tuning_page)
    _state.tuning_layout.setContentsMargins(0, 0, 0, 0)
    _state.tuning_layout.setSpacing(6)
    _state.tuning_hint = _state.QLabel(
        "Structured view of inferred physics tuning values. Patchable rows have an Item and Offset; descriptor_context rows are read-only reference hints from companion XML."
    )
    _state.tuning_hint.setWordWrap(True)
    _state.tuning_layout.addWidget(_state.tuning_hint)
    _state.tuning_toolbar = _state.QGridLayout()
    _state.tuning_toolbar.setContentsMargins(0, 0, 0, 0)
    _state.tuning_toolbar.setHorizontalSpacing(8)
    _state.tuning_toolbar.setVerticalSpacing(4)

def _dialog_step_0004(_state):
    _state.edit_tuning_value_button = _state.QPushButton("Edit Selected Value...")
    _state.tuning_editable_only_checkbox = _state.QCheckBox("Patchable only")
    _state.tuning_filter_edit = _state.QLineEdit()
    _state.tuning_filter_edit.setPlaceholderText("Filter tuning rows")
    _state.tuning_status_label = _state.QLabel("")
    _state.tuning_status_label.setWordWrap(True)
    _state.tuning_status_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Preferred)
    _state.tuning_toolbar.addWidget(_state.edit_tuning_value_button, 0, 0)
    _state.tuning_toolbar.addWidget(_state.tuning_editable_only_checkbox, 0, 1)
    _state.tuning_toolbar.addWidget(_state.tuning_filter_edit, 0, 2)
    _state.tuning_toolbar.addWidget(_state.tuning_status_label, 1, 0, 1, 3)
    _state.tuning_toolbar.setColumnStretch(2, 1)
    _state.tuning_layout.addLayout(_state.tuning_toolbar)
    _state.tuning_tree = _state.QTreeWidget()
    _state.tuning_tree.setColumnCount(8)
    _state.tuning_tree.setHeaderLabels(("Category", "Record", "Item", "Offset", "Name", "Value", "Confidence", "Description"))
    _state.tuning_tree.setAlternatingRowColors(True)
    _state.tuning_tree.setUniformRowHeights(True)
    _state.tuning_tree.setRootIsDecorated(True)
    _state.tuning_tree.setSortingEnabled(True)
    _state.tuning_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.tuning_layout.addWidget(_state.tuning_tree, stretch=1)
    _state.tuning_guidance_text = _state.QPlainTextEdit()
    _state.tuning_guidance_text.setReadOnly(True)
    _state.tuning_guidance_text.setMaximumHeight(132)
    _state.tuning_guidance_text.setLineWrapMode(_state.QPlainTextEdit.LineWrapMode.WidgetWidth)
    _state.tuning_guidance_text.setPlaceholderText("Select a tuning value to see plain-language effect, edit risk, and safe-change guidance.")
    _state.tuning_layout.addWidget(_state.tuning_guidance_text)
    _state.refresh_structured_button = _state.QPushButton("Refresh Structured View From XML")
    _state.tuning_layout.addWidget(_state.refresh_structured_button)
    _state.tab_widget.addTab(_state.tuning_page, "Patchable Values")

    _state.collision_page = _state.QWidget()
    _state.collision_layout = _state.QVBoxLayout(_state.collision_page)
    _state.collision_layout.setContentsMargins(0, 0, 0, 0)
    _state.collision_layout.setSpacing(6)
    _state.collision_hint = _state.QLabel(
        "Structured collision-shape editor. Edit the Value column only. Numeric rows patch fixed-size values; mesh primitive tuple rows accept four bytes such as '3 4 7 2' and only support winding/order changes that keep the same index set."
    )
    _state.collision_hint.setWordWrap(True)
    _state.collision_layout.addWidget(_state.collision_hint)
    _state.collision_toolbar = _state.QGridLayout()
    _state.collision_toolbar.setContentsMargins(0, 0, 0, 0)
    _state.collision_toolbar.setHorizontalSpacing(8)
    _state.collision_toolbar.setVerticalSpacing(4)
    _state.edit_collision_value_button = _state.QPushButton("Edit Selected Value...")
    _state.collision_filter_edit = _state.QLineEdit()
    _state.collision_filter_edit.setPlaceholderText("Filter collision rows")
    _state.collision_status_label = _state.QLabel("")
    _state.collision_status_label.setWordWrap(True)
    _state.collision_status_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Preferred)
    _state.collision_toolbar.addWidget(_state.edit_collision_value_button, 0, 0)
    _state.collision_toolbar.addWidget(_state.collision_filter_edit, 0, 1)
    _state.collision_toolbar.addWidget(_state.collision_status_label, 1, 0, 1, 2)
    _state.collision_toolbar.setColumnStretch(1, 1)
    _state.collision_layout.addLayout(_state.collision_toolbar)
    _state.collision_tree = _state.QTreeWidget()
    _state.collision_tree.setColumnCount(7)
    _state.collision_tree.setHeaderLabels(("Shape", "Field", "Row", "Component", "Value", "Confidence", "Description"))
    _state.collision_tree.setAlternatingRowColors(True)
    _state.collision_tree.setUniformRowHeights(True)
    _state.collision_tree.setRootIsDecorated(True)
    _state.collision_tree.setSortingEnabled(True)
    _state.collision_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.collision_layout.addWidget(_state.collision_tree, stretch=1)
    _state.refresh_collision_button = _state.QPushButton("Refresh Collision Shapes From XML")
    _state.collision_layout.addWidget(_state.refresh_collision_button)
    _state.tab_widget.addTab(_state.collision_page, "Collision Shapes")

    _state.object_layout_page = _state.QWidget()
    _state.object_layout_layout = _state.QVBoxLayout(_state.object_layout_page)
    _state.object_layout_layout.setContentsMargins(0, 0, 0, 0)
    _state.object_layout_layout.setSpacing(6)
    _state.object_layout_hint = _state.QLabel(
        "Read-only converter object layout. These rows expose decoded ITEM record fields, inferred references, and raw preserved byte ranges."
    )
    _state.object_layout_hint.setWordWrap(True)
    _state.object_layout_layout.addWidget(_state.object_layout_hint)
    _state.object_layout_tree = _state.QTreeWidget()
    _state.object_layout_tree.setColumnCount(9)
    _state.object_layout_tree.setHeaderLabels(
        ("Record", "Type", "Kind", "Offset", "Size", "Name", "Value", "Confidence", "Description")
    )
    _state.object_layout_tree.setAlternatingRowColors(True)
    _state.object_layout_tree.setUniformRowHeights(True)
    _state.object_layout_tree.setRootIsDecorated(True)
    _state.object_layout_tree.setSortingEnabled(True)
    _state.object_layout_layout.addWidget(_state.object_layout_tree, stretch=1)
    _state.refresh_object_layout_button = _state.QPushButton("Refresh Object Layout From XML")
    _state.object_layout_layout.addWidget(_state.refresh_object_layout_button)
    _state.tab_widget.addTab(_state.object_layout_page, "Object Layout")

    _state.context_page = _state.QWidget()
    _state.context_layout = _state.QVBoxLayout(_state.context_page)
    _state.context_layout.setContentsMargins(0, 0, 0, 0)
    _state.context_layout.setSpacing(6)
    _state.context_hint = _state.QLabel(
        "Read-only companion descriptor hints from referenced XML files. These rows can help name bodies, sockets, materials, damping, inertia, and angular-limit values; they are ignored on HKX import."
    )
    _state.context_hint.setWordWrap(True)
    _state.context_layout.addWidget(_state.context_hint)
    _state.context_tree = _state.QTreeWidget()
    _state.context_tree.setColumnCount(5)
    _state.context_tree.setHeaderLabels(("Source", "Category", "Name", "Value", "Description"))
    _state.context_tree.setAlternatingRowColors(True)
    _state.context_tree.setUniformRowHeights(True)
    _state.context_tree.setRootIsDecorated(True)
    _state.context_tree.setSortingEnabled(True)
    _state.context_layout.addWidget(_state.context_tree, stretch=1)
    _state.refresh_context_button = _state.QPushButton("Refresh Context Hints From XML")
    _state.context_layout.addWidget(_state.refresh_context_button)
    _state.tab_widget.addTab(_state.context_page, "Context Hints")

    _state.body_summary_page = _state.QWidget()
    _state.body_summary_layout = _state.QVBoxLayout(_state.body_summary_page)
    _state.body_summary_layout.setContentsMargins(0, 0, 0, 0)
    _state.body_summary_layout.setSpacing(6)

def _dialog_step_0005(_state):
    _state.body_summary_hint = _state.QLabel(
        "Read-only body summary decoded from HKX names and collision shapes. Use this to identify which body part a radius, capsule, or tuning value is likely tied to."
    )
    _state.body_summary_hint.setWordWrap(True)
    _state.body_summary_layout.addWidget(_state.body_summary_hint)
    _state.body_summary_tree = _state.QTreeWidget()
    _state.body_summary_tree.setColumnCount(8)
    _state.body_summary_tree.setHeaderLabels(("Body", "Shape", "Radius", "Length", "Socket / Context", "Editable Fields", "Confidence", "Description"))
    _state.body_summary_tree.setAlternatingRowColors(True)
    _state.body_summary_tree.setUniformRowHeights(True)
    _state.body_summary_tree.setRootIsDecorated(True)
    _state.body_summary_tree.setSortingEnabled(True)
    _state.body_summary_layout.addWidget(_state.body_summary_tree, stretch=1)
    _state.refresh_body_summary_button = _state.QPushButton("Refresh Body Summary From XML")
    _state.body_summary_layout.addWidget(_state.refresh_body_summary_button)
    _state.tab_widget.addTab(_state.body_summary_page, "Body Summary")

    _state.constraint_summary_page = _state.QWidget()
    _state.constraint_summary_layout = _state.QVBoxLayout(_state.constraint_summary_page)
    _state.constraint_summary_layout.setContentsMargins(0, 0, 0, 0)
    _state.constraint_summary_layout.setSpacing(6)
    _state.constraint_summary_hint = _state.QLabel(
        "Read-only constraint and motor summary. These rows help identify likely stiffness, damping, force, friction, and angular-limit controls; edit linked values in Patchable Values."
    )
    _state.constraint_summary_hint.setWordWrap(True)
    _state.constraint_summary_layout.addWidget(_state.constraint_summary_hint)
    _state.constraint_summary_tree = _state.QTreeWidget()
    _state.constraint_summary_tree.setColumnCount(8)
    _state.constraint_summary_tree.setHeaderLabels(("Constraint", "Type", "Constraint Record", "Motor Record", "Name / Slot", "Value", "Confidence", "Description"))
    _state.constraint_summary_tree.setAlternatingRowColors(True)
    _state.constraint_summary_tree.setUniformRowHeights(True)
    _state.constraint_summary_tree.setRootIsDecorated(True)
    _state.constraint_summary_tree.setSortingEnabled(True)
    _state.constraint_summary_layout.addWidget(_state.constraint_summary_tree, stretch=1)
    _state.focus_constraint_tuning_button = _state.QPushButton("Show in Patchable Values")
    _state.refresh_constraint_summary_button = _state.QPushButton("Refresh Constraint Summary From XML")
    _state.constraint_button_row = _state.QHBoxLayout()
    _state.constraint_button_row.addWidget(_state.focus_constraint_tuning_button)
    _state.constraint_button_row.addWidget(_state.refresh_constraint_summary_button)
    _state.constraint_button_row.addStretch(1)
    _state.constraint_summary_layout.addLayout(_state.constraint_button_row)
    _state.tab_widget.addTab(_state.constraint_summary_page, "Constraint Summary")

    _state.editable_catalog_page = _state.QWidget()
    _state.editable_catalog_layout = _state.QVBoxLayout(_state.editable_catalog_page)
    _state.editable_catalog_layout.setContentsMargins(0, 0, 0, 0)
    _state.editable_catalog_layout.setSpacing(6)
    _state.editable_catalog_hint = _state.QLabel(
        "Import-safe editable field catalog. This lists values the converter can route to a structured editor; explanations are ignored on import."
    )
    _state.editable_catalog_hint.setWordWrap(True)
    _state.editable_catalog_layout.addWidget(_state.editable_catalog_hint)
    _state.editable_catalog_toolbar = _state.QGridLayout()
    _state.editable_catalog_toolbar.setContentsMargins(0, 0, 0, 0)
    _state.editable_catalog_toolbar.setHorizontalSpacing(8)
    _state.editable_catalog_toolbar.setVerticalSpacing(4)
    _state.editable_catalog_filter_edit = _state.QLineEdit()
    _state.editable_catalog_filter_edit.setPlaceholderText("Filter editable catalog")
    _state.editable_catalog_status_label = _state.QLabel("")
    _state.editable_catalog_status_label.setWordWrap(True)
    _state.editable_catalog_status_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Preferred)
    _state.editable_catalog_toolbar.addWidget(_state.editable_catalog_filter_edit, 0, 0)
    _state.editable_catalog_toolbar.addWidget(_state.editable_catalog_status_label, 1, 0)
    _state.editable_catalog_toolbar.setColumnStretch(0, 1)
    _state.editable_catalog_layout.addLayout(_state.editable_catalog_toolbar)
    _state.editable_catalog_tree = _state.QTreeWidget()
    _state.editable_catalog_tree.setColumnCount(13)
    _state.editable_catalog_tree.setHeaderLabels(("Category", "Subject", "Editor", "Record", "Item", "Offset", "Name", "Value", "Effect", "Confidence", "Guidance", "Rules", "Description"))
    _state.editable_catalog_tree.setAlternatingRowColors(True)
    _state.editable_catalog_tree.setUniformRowHeights(True)
    _state.editable_catalog_tree.setRootIsDecorated(True)
    _state.editable_catalog_tree.setSortingEnabled(True)
    _state.editable_catalog_layout.addWidget(_state.editable_catalog_tree, stretch=1)
    _state.focus_catalog_button = _state.QPushButton("Show Selected Editor")
    _state.refresh_catalog_button = _state.QPushButton("Refresh Patchable Catalog From XML")
    _state.catalog_button_row = _state.QHBoxLayout()
    _state.catalog_button_row.addWidget(_state.focus_catalog_button)
    _state.catalog_button_row.addWidget(_state.refresh_catalog_button)
    _state.catalog_button_row.addStretch(1)
    _state.editable_catalog_layout.addLayout(_state.catalog_button_row)
    _state.tab_widget.addTab(_state.editable_catalog_page, "Patchable Catalog")

    _state.byte_map_page = _state.QWidget()
    _state.byte_map_layout = _state.QVBoxLayout(_state.byte_map_page)
    _state.byte_map_layout.setContentsMargins(0, 0, 0, 0)
    _state.byte_map_layout.setSpacing(6)
    _state.byte_map_hint = _state.QLabel(
        "Read-only byte patch map. These rows show exactly where editable XML values map back into the original HKX byte stream."
    )
    _state.byte_map_hint.setWordWrap(True)
    _state.byte_map_layout.addWidget(_state.byte_map_hint)
    _state.byte_map_toolbar = _state.QGridLayout()
    _state.byte_map_toolbar.setContentsMargins(0, 0, 0, 0)
    _state.byte_map_toolbar.setHorizontalSpacing(8)
    _state.byte_map_toolbar.setVerticalSpacing(4)
    _state.byte_map_filter_edit = _state.QLineEdit()
    _state.byte_map_filter_edit.setPlaceholderText("Filter byte map")
    _state.byte_map_status_label = _state.QLabel("")
    _state.byte_map_status_label.setWordWrap(True)
    _state.byte_map_status_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Preferred)
    _state.byte_map_toolbar.addWidget(_state.byte_map_filter_edit, 0, 0)
    _state.byte_map_toolbar.addWidget(_state.byte_map_status_label, 1, 0)
    _state.byte_map_toolbar.setColumnStretch(0, 1)
    _state.byte_map_layout.addLayout(_state.byte_map_toolbar)
    _state.byte_map_tree = _state.QTreeWidget()
    _state.byte_map_tree.setColumnCount(11)
    _state.byte_map_tree.setHeaderLabels(("Category", "Subject", "Path", "Record", "Item", "Row", "Component", "Relative", "Absolute", "Type", "Description"))
    _state.byte_map_tree.setAlternatingRowColors(True)
    _state.byte_map_tree.setUniformRowHeights(True)
    _state.byte_map_tree.setRootIsDecorated(True)
    _state.byte_map_tree.setSortingEnabled(True)
    _state.byte_map_layout.addWidget(_state.byte_map_tree, stretch=1)
    _state.refresh_byte_map_button = _state.QPushButton("Refresh Byte Map From XML")
    _state.byte_map_layout.addWidget(_state.refresh_byte_map_button)
    _state.tab_widget.addTab(_state.byte_map_page, "Byte Map")

    _state.connected_page = _state.QWidget()
    _state.connected_layout = _state.QVBoxLayout(_state.connected_page)
    _state.connected_layout.setContentsMargins(0, 0, 0, 0)

def _dialog_step_0006(_state):
    _state.connected_layout.setSpacing(6)
    _state.connected_hint = _state.QLabel(
        "Connected physics view. Select a 3D overlay shape/body/constraint or a navigator row to see linked body info, constraints, materials, byte offsets, and editable values together."
    )
    _state.connected_hint.setWordWrap(True)
    _state.connected_layout.addWidget(_state.connected_hint)
    _state.connected_toolbar = _state.QGridLayout()
    _state.connected_toolbar.setContentsMargins(0, 0, 0, 0)
    _state.connected_toolbar.setHorizontalSpacing(8)
    _state.connected_toolbar.setVerticalSpacing(4)
    _state.connected_open_button = _state.QPushButton("Open Linked Value")
    _state.connected_highlight_button = _state.QPushButton("Highlight 3D")
    _state.connected_workflow_combo = _state.QComboBox()
    _state.connected_workflow_combo.addItem("All connections", "")
    _state.connected_workflow_combo.addItem("Capsule size", "capsule radius endpoint shape body")
    _state.connected_workflow_combo.addItem("Joint stiffness", "constraint motor stiffness force torque angular limit strength")
    _state.connected_workflow_combo.addItem("Damping", "damping motion motor body angular linear")
    _state.connected_workflow_combo.addItem("Ragdoll body inspection", "ragdoll body shape material socket")
    _state.connected_workflow_combo.addItem("Hair / cloth labels", "hair cloth cloak cape skirt pbd material simulation jiggle")
    _state.connected_workflow_combo.addItem("Body part labels", "body breast chest bust butt hip pelvis thigh belly")
    _state.connected_workflow_combo.setToolTip("Context filters for common HKX physics labels and value families.")
    _state.connected_risk_combo = _state.QComboBox()
    _state.connected_risk_combo.addItem("All risk", "")
    _state.connected_risk_combo.addItem("Safe / Patchable", "safe")
    _state.connected_risk_combo.addItem("Inferred", "inferred")
    _state.connected_risk_combo.addItem("Experimental", "experimental")
    _state.connected_risk_combo.setToolTip("Filter by import safety and confidence: safe patchable rows, inferred rows, or experimental context.")
    _state.connected_target_filter_edit = _state.QLineEdit()
    _state.connected_target_filter_edit.setPlaceholderText("Filter connected physics")
    _state.connected_status_label = _state.QLabel("")
    _state.connected_status_label.setWordWrap(True)
    _state.connected_status_label.setSizePolicy(_state.QSizePolicy.Policy.Ignored, _state.QSizePolicy.Policy.Preferred)
    _state.connected_toolbar.addWidget(_state.connected_open_button, 0, 0)
    _state.connected_toolbar.addWidget(_state.connected_highlight_button, 0, 1)
    _state.connected_toolbar.addWidget(_state.connected_workflow_combo, 0, 2)
    _state.connected_toolbar.addWidget(_state.connected_risk_combo, 0, 3)
    _state.connected_toolbar.addWidget(_state.connected_target_filter_edit, 0, 4)
    _state.connected_toolbar.addWidget(_state.connected_status_label, 1, 0, 1, 5)
    _state.connected_toolbar.setColumnStretch(4, 1)
    _state.connected_layout.addLayout(_state.connected_toolbar)
    _state.connected_tree = _state.QTreeWidget()
    _state.connected_tree.setColumnCount(8)
    _state.connected_tree.setHeaderLabels(("Target", "Connected To", "Relation", "Value / Before -> After", "Confidence", "Risk", "Action", "Details"))
    _state.connected_tree.setAlternatingRowColors(True)
    _state.connected_tree.setUniformRowHeights(True)
    _state.connected_tree.setRootIsDecorated(True)
    _state.connected_tree.setSortingEnabled(True)
    _state.connected_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.connected_layout.addWidget(_state.connected_tree, stretch=1)
    _state.connected_detail_text = _state.QPlainTextEdit()
    _state.connected_detail_text.setReadOnly(True)
    _state.connected_detail_text.setMaximumHeight(138)
    _state.connected_detail_text.setLineWrapMode(_state.QPlainTextEdit.LineWrapMode.WidgetWidth)
    _state.connected_detail_text.setPlaceholderText(
        "Select a connected row or click a 3D HKX overlay target to see exact linked values, offsets, confidence, and before/after state."
    )
    _state.connected_layout.addWidget(_state.connected_detail_text)
    _state.tab_widget.addTab(_state.connected_page, "Connected Physics")

    _state.decoder_page = _state.QWidget()
    _state.decoder_layout = _state.QVBoxLayout(_state.decoder_page)
    _state.decoder_layout.setContentsMargins(0, 0, 0, 0)
    _state.decoder_layout.setSpacing(6)
    _state.decoder_status_label = _state.QLabel("")
    _state.decoder_status_label.setWordWrap(True)
    _state.decoder_layout.addWidget(_state.decoder_status_label)
    _state.decoder_tree = _state.QTreeWidget()
    _state.decoder_tree.setColumnCount(6)
    _state.decoder_tree.setHeaderLabels(("Class / Evidence", "Status", "Fields", "Refs", "Bytes", "Missing / Source"))
    _state.decoder_tree.setAlternatingRowColors(True)
    _state.decoder_tree.setUniformRowHeights(True)
    _state.decoder_tree.setRootIsDecorated(True)
    _state.decoder_tree.setSortingEnabled(True)
    _state.decoder_tree.setEditTriggers(_state.QAbstractItemView.NoEditTriggers)
    _state.decoder_layout.addWidget(_state.decoder_tree, stretch=1)
    _state.decoder_detail_text = _state.QPlainTextEdit()
    _state.decoder_detail_text.setReadOnly(True)
    _state.decoder_detail_text.setMaximumHeight(118)
    _state.decoder_detail_text.setLineWrapMode(_state.QPlainTextEdit.LineWrapMode.WidgetWidth)
    _state.decoder_detail_text.setPlaceholderText(
        "Select a decoder evidence row to see normalized fixup/link evidence and what semantics are still missing."
    )
    _state.decoder_layout.addWidget(_state.decoder_detail_text)
    _state.tab_widget.addTab(_state.decoder_page, "Decoder Evidence")

    try:
        _state.hkx_attachment_graph, _state._hkx_attachment_references = _state.self._archive_asset_family_graph_for_entry(_state.entry)
    except Exception:
        # Best effort: placement-chain evidence is optional for HKX inspection.
        _state.hkx_attachment_graph = _state.AssetFamilyGraph(
            root_path=_state.entry.path,
            family_key=_state.PurePosixPath(_state.entry.path.replace("\\", "/")).stem,
            summary="No placement chain",
        )

    _state.placement_page = _state.QWidget()
    _state.placement_layout = _state.QVBoxLayout(_state.placement_page)
    _state.placement_layout.setContentsMargins(0, 0, 0, 0)
    _state.placement_layout.setSpacing(6)
    _state.placement_hint = _state.QLabel(
        "Disabled - WIP. Prefab/socket placement workflow is paused here; HKX rows remain physics context in the other views."
    )
    _state.placement_hint.setWordWrap(True)
    _state.placement_layout.addWidget(_state.placement_hint)
    _state.placement_splitter = _state.QSplitter(_state.Qt.Orientation.Horizontal)
    _state.placement_left_panel = _state.QWidget()
    _state.placement_left_layout = _state.QVBoxLayout(_state.placement_left_panel)
    _state.placement_left_layout.setContentsMargins(0, 0, 8, 0)
    _state.placement_left_layout.setSpacing(6)
    _state.placement_status_label = _state.QLabel(str(getattr(_state.hkx_attachment_graph, "summary", "") or "No placement chain"))
    _state.placement_status_label.setObjectName("HintLabel")
    _state.placement_status_label.setWordWrap(True)
    _state.placement_left_layout.addWidget(_state.placement_status_label)
    _state.placement_left_splitter = _state.QSplitter(_state.Qt.Orientation.Vertical)
    _state.placement_tree = _state.QTreeWidget()
    _state.placement_tree.setColumnCount(5)
    _state.placement_tree.setHeaderLabels(["Chain / Field", "Socket / File", "Transform", "Evidence", "Status"])
    _state.placement_tree.setRootIsDecorated(True)

STEPS = (_dialog_step_0001, _dialog_step_0002, _dialog_step_0003, _dialog_step_0004, _dialog_step_0005, _dialog_step_0006,)
