from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAIN_WINDOW = ROOT / "cdmw" / "ui" / "main_window.py"
WIDGETS = ROOT / "cdmw" / "ui" / "widgets.py"
ARCHIVE_MODDING = ROOT / "cdmw" / "core" / "archive_modding.py"
STATIC_REPLACER = ROOT / "cdmw" / "modding" / "static_mesh_replacer.py"


def _main_window_source() -> str:
    return MAIN_WINDOW.read_text(encoding="utf-8")


def _widgets_source() -> str:
    return WIDGETS.read_text(encoding="utf-8")


def _archive_modding_source() -> str:
    return ARCHIVE_MODDING.read_text(encoding="utf-8")


def _static_replacer_source() -> str:
    return STATIC_REPLACER.read_text(encoding="utf-8")


class AlignmentDialogSourceGuardTests(unittest.TestCase):
    def test_alignment_dialog_qsize_runtime_dependency_is_imported(self) -> None:
        source = _main_window_source()
        self.assertIn("QSize(", source)
        self.assertIn("QSettings, QSize, Qt", source)

    def test_orientation_presets_are_explicit_apply_only(self) -> None:
        source = _main_window_source()
        self.assertIn("apply_orientation_preset_button.clicked.connect", source)
        self.assertNotIn("orientation_preset_combo.currentIndexChanged.connect(_apply_orientation_preset)", source)
        self.assertIn("reset_placement_button.clicked.connect(_reset_placement_values)", source)

    def test_manual_texture_override_uses_assignment_store(self) -> None:
        source = _main_window_source()
        self.assertIn("texture_override_assignments: Dict[Tuple[str, str, str], str] = {}", source)
        self.assertIn("selected_source_combo = QComboBox()", source)
        self.assertIn("selected_source_combo.currentIndexChanged.connect(_selected_texture_source_changed)", source)
        self.assertIn("def _texture_source_choices_for_row", source)
        self.assertIn("def _texture_row_effective_source", source)
        self.assertIn("def _sync_texture_row_assignment_state", source)
        self.assertIn("texture_override_assignments[row_key] = normalized_source_path", source)
        self.assertIn('texture_override_assignments[row_key] = ""', source)
        self.assertIn("_commit_texture_row_source(row_state, source_path)", source)
        self.assertIn("texture_override_tree.itemActivated.connect(_texture_table_item_activated)", source)
        self.assertIn(
            "def _refresh_texture_row_in_place(row_state: Dict[str, Any], *, sync_editor: bool = True)",
            source,
        )
        self.assertIn('row_state["checked"] = bool(normalized_source_path)', source)
        self.assertNotIn("selected_source_combo.activated.connect", source)
        self.assertNotIn("selected_source_combo.textActivated.connect", source)
        self.assertNotIn("_stage_selected_texture_source", source)

    def test_loose_export_builds_final_output_preview_after_commit(self) -> None:
        source = _main_window_source()
        self.assertIn("build_final_package_preview(", source)
        self.assertIn("final_preview: Optional[FinalPackagePreviewResult]", source)
        self.assertIn("Building final output preview from packaged sidecar/DDS payloads", source)
        self.assertIn("original_dds_resolver=_archive_dds_preview_source_for_path", source)
        self.assertIn("original_dds_basename_resolver=_archive_dds_preview_sources_for_basename", source)
        self.assertIn("copied_dds_specs", source)
        self.assertIn("show_texture_resolution_manifest_option=True", source)
        self.assertIn("create_texture_resolution_manifest=texture_resolution_manifest_checkbox.isChecked()", source)
        self.assertIn('texture_resolution_manifest_path = loose_result.package_root / "cdmw_texture_resolution_manifest.json"', source)
        self.assertIn('if not bool(getattr(export_options, "create_texture_resolution_manifest", False)):', source)
        self.assertIn("Removed stale texture resolution manifest", source)
        self.assertIn('if bool(getattr(export_options, "create_texture_resolution_manifest", False)):', source)
        self.assertIn("The preview is using final package texture paths where they could be validated.", source)

    def test_alignment_dialog_has_in_memory_test_build_preview(self) -> None:
        source = _main_window_source()
        self.assertIn('QPushButton("Test Build Preview")', source)
        self.assertIn('QPushButton("Back to Live Preview")', source)
        self.assertIn("Live alignment preview - fast geometry/material approximation", source)
        self.assertIn("Final Test Build Preview - not written", source)
        self.assertIn("more authoritative than the live replacement preview", source)
        self.assertIn("def _test_build_final_preview", source)
        self.assertIn("_build_static_options_from_dialog(show_messages=True)", source)
        self.assertIn("def _current_static_placement_snapshot", source)
        self.assertIn("def _static_options_from_placement_snapshot", source)
        self.assertIn("include_preview_only_independent_parts=False", source)
        self.assertIn("include_preview_only_independent_parts=True", source)
        self.assertIn("preview_result = build_mesh_import_preview(", source)
        self.assertIn("final_preview = build_final_package_preview(", source)
        self.assertIn("supplemental_file_specs=tuple(extra_supplemental_specs or ()) + tuple(preview_result.supplemental_file_specs or ())", source)
        self.assertIn("original_dds_resolver=_archive_dds_preview_source_for_path", source)
        self.assertIn("original_dds_basename_resolver=_archive_dds_preview_sources_for_basename", source)
        self.assertIn("final_model_for_display = final_preview.preview_model", source)
        self.assertIn("static_dialog_preview.set_model(final_model_for_display)", source)
        self.assertNotIn("_copy_final_texture_slots", source)
        self.assertIn("def _mark_final_test_preview_stale", source)
        self.assertIn("test_build_preview_button.clicked.connect(_test_build_final_preview)", source)

    def test_alignment_dialog_has_native_d3d11_accurate_preview_mode(self) -> None:
        source = _main_window_source()
        native_source = (ROOT / "native" / "cdmw_d3d11_preview" / "src" / "main.cpp").read_text(encoding="utf-8")
        self.assertIn('preview_renderer_combo.addItem("Native D3D11 accurate", "d3d11")', source)
        self.assertIn('preview_renderer_combo.addItem("Legacy OpenGL edit", "legacy")', source)
        self.assertIn("alignment_d3d11_preview_host = NativeD3D11PreviewHostFrame", source)
        self.assertIn("AlignmentD3D11PackageWorker", source)
        self.assertIn("write_isolated_d3d11_preview_package(", source)
        self.assertIn("ModelPreviewWidget.prepare_model_preview(", source)
        self.assertIn("def _alignment_d3d11_display_model", source)
        self.assertIn("def _side_by_side_alignment_preview_model", source)
        self.assertIn("Native D3D11 accurate preview. Mesh edit brush/vertex strokes and alignment handles run in D3D11", source)
        self.assertIn("alignment_d3d11_preview_host.set_mesh_edit_state(", source)
        self.assertIn("alignment_d3d11_preview_host.set_alignment_state(", source)
        self.assertIn("alignment_d3d11_preview_host.alignment_drag_finished.connect(_commit_alignment_preview_translation)", source)
        self.assertIn("alignment_d3d11_preview_host.alignment_rotation_finished.connect(_commit_alignment_preview_rotation)", source)
        self.assertIn("alignment_d3d11_preview_host.mesh_edit_stroke_started.connect(_mesh_edit_begin_stroke)", source)
        self.assertNotIn("Mesh Edit uses viewport strokes from Legacy OpenGL edit", source)
        self.assertIn("std::string alignment_axis_at", native_source)
        self.assertIn("draw_alignment_overlay_gdi", native_source)
        self.assertIn("send_alignment_vector_event(\"alignment_drag_finished\"", native_source)
        self.assertIn("send_alignment_vector_event(\"alignment_rotation_finished\"", native_source)
        self.assertIn("std::vector<EditorCandidate> mesh_edit_candidates_at", native_source)
        self.assertIn("send_mesh_edit_event(\"mesh_edit_stroke_started\"", native_source)
        self.assertIn("send_mesh_edit_event(\"mesh_edit_stroke_previewed\"", native_source)
        self.assertIn("source_vertex_weights", native_source)
        self.assertIn("identity_file", native_source)

    def test_alignment_dialog_build_mod_keeps_window_open_for_repeat_exports(self) -> None:
        source = _main_window_source()
        self.assertIn(
            "continue_build_callback: Optional[Callable[[StaticMeshReplacementOptions], bool]] = None",
            source,
        )
        self.assertIn('QPushButton("Build Mod" if continue_build_callback is not None else "Continue")', source)
        self.assertIn(
            "Build/export with the current alignment settings and keep this window open for more edits.",
            source,
        )
        self.assertIn('cancel_button = QPushButton("Cancel")', source)
        self.assertIn("started = bool(continue_build_callback(static_options))", source)
        self.assertIn("Started mesh replacement build. Alignment window remains open for more edits.", source)
        self.assertIn("                    return\n                dialog.accept()", source)
        self.assertIn("def _start_build_with_static_options(", source)
        self.assertIn("continue_build_callback=_start_build_with_static_options", source)
        self.assertIn("Mesh replacement build cancelled before export target selection.", source)
        self.assertIn("Mesh replacement build cancelled before related file selection.", source)
        self.assertIn("                return\n\n            _start_build_with_static_options(None)", source)

    def test_alignment_dialog_has_source_mixing_tray_without_new_top_level_tab(self) -> None:
        source = _main_window_source()
        self.assertIn('QGroupBox("Source Mixing")', source)
        self.assertIn('QPushButton("Add Archive Source")', source)
        self.assertIn('QPushButton("Add Loose Mod Folder")', source)
        self.assertIn('QPushButton("Add .pamt/.paz Mod")', source)
        self.assertIn("def _choose_loaded_archive_mesh_source_for_alignment", source)
        self.assertIn("def _choose_mod_archive_mesh_source_for_alignment", source)
        self.assertIn("def _choose_archive_mesh_source_dialog", source)
        self.assertIn("Search archive source by name, path, package, or role", source)
        self.assertIn("This does not rescan the archive.", source)
        self.assertIn('preview_title = QLabel("Source Preview")', source)
        self.assertIn('extension_combo.addItem("All supported", "")', source)
        self.assertIn('control_row.addWidget(QLabel("Extension"))', source)
        self.assertIn("QTimer.singleShot(0, _restart_source_picker_population)", source)
        self.assertIn('entries_by_extension = getattr(self, "archive_entries_by_extension", {}) or {}', source)
        self.assertIn('source_entries = mesh_entries or (getattr(self, "archive_entries", ()) or ())', source)
        self.assertIn("allowed_extensions=tuple(sorted(ARCHIVE_MESH_EXTENSIONS))", source)
        self.assertIn("excluded_entry=entry", source)
        self.assertIn("self._start_archive_in_game_mesh_swap(", source)
        self.assertIn("scan_loose_folder_source(Path(selected_dir))", source)
        self.assertIn("scan_mod_archive_source(Path(selected_path))", source)
        self.assertIn("Geometry same | Materials same | Render settings same | Camera synced", source)
        self.assertIn("Selection highlight preserves texture bindings", source)
        self.assertNotIn('self.main_tabs.addTab(self.mod_composer_tab', source)

    def test_archive_browser_has_source_mix_pair_overlay_export(self) -> None:
        source = _main_window_source()
        self.assertIn('menu.addAction("Build Loose Package From Sources...")', source)
        self.assertIn("def _open_archive_source_mix_package_dialog", source)
        self.assertIn("validate_source_mix_selections(selections)", source)
        self.assertIn("export_archive_payloads_to_mod_ready_loose(", source)
        self.assertIn("scan_loose_folder_source(", source)
        self.assertIn("scan_mod_archive_source(", source)
        self.assertIn("paired_counterpart_virtual_path(entry.path)", source)

    def test_source_mix_exports_sidecar_referenced_texture_payloads(self) -> None:
        source = _main_window_source()
        self.assertIn("def _source_mix_lookup_keys_for_texture_path", source)
        self.assertIn("def _source_mix_sidecar_referenced_payload_specs", source)
        self.assertIn("parse_texture_sidecar_bindings(sidecar_text", source)
        self.assertIn("Auto-included because selected sidecar", source)
        self.assertIn("extra_payloads_to_include=extra_payload_specs", source)
        self.assertIn("Auto-including {len(extra_payload_specs):,} sidecar-referenced texture payload(s)", source)

    def test_alignment_dialog_sidecar_toggles_flow_into_preview_build(self) -> None:
        source = _main_window_source()
        self.assertIn("rebuild_material_sidecar=bool(rebuild_sidecar_checkbox.isChecked())", source)
        self.assertIn("enable_missing_base_color_parameters=bool(inject_base_color_checkbox.isChecked())", source)
        self.assertIn("static_replacement_options=static_options", source)
        self.assertIn("extra_supplemental_specs=setup.extra_supplemental_specs", source)

    def test_modify_original_has_cross_original_material_source_flow(self) -> None:
        source = _main_window_source()
        archive_source = _archive_modding_source()
        static_source = _static_replacer_source()

        self.assertIn("class StaticDonorMaterialTextureBinding", static_source)
        self.assertIn("class StaticDonorMaterialPlan", static_source)
        self.assertIn("donor_material_plans: list[StaticDonorMaterialPlan]", static_source)
        self.assertIn('QGroupBox("Cross-Original Material Sources")', source)
        self.assertIn('QPushButton("Use Another Original Mesh...")', source)
        self.assertIn('QPushButton("Clear Selected Target")', source)
        self.assertIn('donor_material_plan_tree.setHeaderLabels(["Target", "Material source", "Donor", "Shader", "Status"])', source)
        self.assertIn("def _open_original_material_source_picker", source)
        self.assertIn("donor_preview = ModelPreviewWidget", source)
        self.assertIn('donor_part_tree.setHeaderLabels(["Donor part", "Shader", "Textures", "Emissive/glow"])', source)
        self.assertIn('donor_texture_tree.setHeaderLabels(["Role", "Parameter", "DDS", "Shader", "State"])', source)
        self.assertIn('donor_mode_combo.addItem("Donor material behavior", "material_behavior")', source)
        self.assertIn('donor_mode_combo.addItem("Donor textures", "donor_textures")', source)
        self.assertIn("uses compatible target .pac_xml texture parameters first", source)
        self.assertIn('state = "emissive/glow"', source)
        self.assertIn("StaticDonorMaterialTextureBinding(", source)
        self.assertIn("donor_material_plans_by_target[target_index] = StaticDonorMaterialPlan(", source)
        self.assertIn('"donor_material_plans": _current_donor_material_plan_payload()', source)
        self.assertIn('"donor_material_plans": _current_donor_material_plans()', source)
        self.assertIn("donor_material_plans=list(placement_snapshot.get", source)
        self.assertIn("donor_material_plans = tuple(getattr(static_replacement_options", archive_source)
        self.assertIn("or donor_material_plans", archive_source)
        self.assertIn("donor_material_plans=donor_material_plans", archive_source)

    def test_custom_item_icon_controls_flow_into_mesh_and_placement_exports(self) -> None:
        source = _main_window_source()
        static_source = _static_replacer_source()
        self.assertIn("from cdmw.core.item_icon import", source)
        self.assertIn('QGroupBox("Custom Item Icon")', source)
        self.assertIn('QCheckBox("Use custom item icon")', source)
        self.assertIn("def _alignment_custom_icon_override_spec", source)
        self.assertIn("def _placement_custom_icon_override_spec", source)
        self.assertIn('custom_icon_library_button = QPushButton("Library...")', source)
        self.assertIn("self._choose_item_icon_library_source(dialog)", source)
        self.assertIn("choose_item_icon_source(", source)
        self.assertIn("custom_item_icon_override=custom_item_icon_override", source)
        self.assertIn("kind=\"item_icon_generated\"", source)
        self.assertIn("custom_icon_specs", source)
        self.assertIn("requests_by_path[target_key] = ArchivePatchRequest(target_icon_entry, generated_icon_spec.payload_data)", source)
        self.assertIn("custom_item_icon_override: object | None = None", static_source)

    def test_modify_original_clone_uses_exact_geometry_preview_and_target_highlight(self) -> None:
        source = _main_window_source()
        self.assertIn("modify_original_clone_mode = (", source)
        self.assertIn("if modify_original_clone_mode:\n                    appended_geometry = int(source_geometry_revision.get", source)
        self.assertIn("if not appended_geometry:\n                        return 0", source)
        self.assertIn('confidence_label="exact-original-clone"', source)
        self.assertIn('alignment_mode_combo.findData("manual")', source)
        self.assertIn("selected_target_source_highlight_indices", source)
        self.assertIn("selected_target_original_highlight_indices", source)
        self.assertIn("selected_target_source_highlight_indices.add(source_index)", source)
        self.assertIn('part_inspector = QGroupBox("Selected Part")', source)
        self.assertIn("part_source_combo = QComboBox()", source)
        self.assertIn('part_enabled_checkbox = QCheckBox("Include in output")', source)
        self.assertIn('remove_part_button = QPushButton("Remove Part")', source)
        self.assertIn("parts_layout.addWidget(part_inspector, 0)", source)
        self.assertIn("source_tree.setSelectionMode(QAbstractItemView.ExtendedSelection)", source)
        self.assertIn("def _auto_fit_alignment_tree_columns(", source)
        self.assertIn("material_plan_tree,\n                        (72, 58, 150, 230, 58, 90)", source)
        self.assertIn("expand_columns=(3, 2, 5)", source)
        self.assertIn("texture_override_tree,\n                                    (120, 150, 90, 180, 220, 96, 180)", source)
        self.assertIn("def _selected_source_indices_from_tree", source)
        self.assertIn("duplicate_count = 0", source)
        self.assertIn("Transforms and Include apply to all selected parts", source)
        self.assertIn("source_tree.itemSelectionChanged.connect(_refresh_source_tree_selection_state)", source)
        self.assertIn("Use Uniform Scale for equal resizing, or Axis Scale for X/Y/Z-only changes.", source)
        self.assertIn("QDialog#MeshReplacementAlignmentDialog {\n                    font-size: 8px;", source)
        self.assertIn("QDialog#MeshReplacementAlignmentDialog QTreeWidget {\n                    font-size: 8px;", source)
        self.assertIn("QDialog#MeshReplacementAlignmentDialog QTextBrowser,\n                QDialog#MeshReplacementAlignmentDialog QTextEdit,\n                QDialog#MeshReplacementAlignmentDialog QPlainTextEdit", source)
        self.assertIn("setup_layout.setContentsMargins(3, 2, 3, 2)", source)
        self.assertIn("parts_layout.setContentsMargins(3, 2, 3, 2)", source)
        self.assertIn("textures_layout.setContentsMargins(3, 2, 3, 2)", source)
        self.assertIn("routing_layout.setContentsMargins(3, 2, 3, 2)", source)
        self.assertIn("header.setMinimumSectionSize(28)", source)
        self.assertIn("minimum_width=28", source)
        self.assertIn("restore_later=False", source)
        self.assertIn("persist_order=False", source)
        self.assertIn("sections_movable=False", source)
        self.assertIn('axis_scale_label = QLabel("Axis Scale")', source)
        self.assertIn('uniform_scale_label = QLabel("Uniform Scale")', source)
        self.assertIn('part_uniform_spin.setPrefix("All ")', source)
        self.assertIn("Non-uniform axis scale. 1.0 leaves this axis unchanged.", source)
        self.assertIn("original_texture_preview_default = bool(modify_original_clone_mode and not defer_original_texture_preview)", source)
        self.assertIn('original_texture_preview_state = {"enabled": original_texture_preview_default}', source)
        self.assertIn("def _preserve_modify_original_material_preview", source)
        self.assertIn('QCheckBox("Preview with original DDS/materials")', source)
        self.assertIn("original_texture_preview_group.setVisible(bool(modify_original_clone_mode))", source)
        self.assertIn("def _apply_original_material_preview", source)
        self.assertIn("def _preview_mesh_surface_matches", source)
        self.assertIn('source_submesh_index = int(getattr(preview_mesh, "source_submesh_index", -1))', source)
        self.assertIn("translation_delta: tuple[float, float, float] | None = None", source)
        self.assertIn("abs(delta[0] - translation_delta[0]) > epsilon", source)
        self.assertIn("copy_matching_surface=True", source)
        self.assertIn("and not _preserve_modify_original_material_preview()", source)
        self.assertIn("_apply_original_material_preview(", source)
        self.assertIn("if modify_original_clone_mode and mapped_preview:", source)
        self.assertIn("target_mesh_indices = _preview_target_mesh_indices(", source)
        self.assertIn("for mesh_index in target_mesh_indices:", source)
        self.assertIn("preview_meshes[mesh_index],\n                                    original_meshes[target_index],", source)
        self.assertIn('"preview_texture_image"', source)
        self.assertIn('"preview_debug_disable_support_maps"', source)
        self.assertIn("and not use_original_material_preview", source)
        self.assertNotIn("clear_textures=True", source)
        self.assertIn("alignment_preview_view_sync = {\"active\": False}", source)
        self.assertIn("def _sync_alignment_preview_view_state", source)
        self.assertIn("original_dialog_preview.view_state_changed.connect", source)
        self.assertIn("static_dialog_preview.view_state_changed.connect", source)

    def test_alignment_dialog_is_maximizable_and_keeps_controls_readable(self) -> None:
        source = _main_window_source()
        self.assertIn("dialog.setWindowFlag(Qt.WindowMaximizeButtonHint, True)", source)
        self.assertIn("dialog.setWindowFlag(Qt.WindowMinimizeButtonHint, True)", source)
        self.assertIn("alignment_control_min_width = 520", source)
        self.assertIn("alignment_control_content_min_width = 560", source)
        self.assertIn("content_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)", source)
        self.assertIn("content_scroll.setSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Expanding)", source)
        self.assertIn("content_container.setMinimumWidth(alignment_control_content_min_width)", source)
        self.assertIn("main_splitter.setChildrenCollapsible(False)", source)
        self.assertIn("preview_splitter.setChildrenCollapsible(False)", source)
        self.assertIn('alignment_dialog_layout_state = {"mode": ""}', source)
        self.assertIn("def _apply_alignment_dialog_responsive_layout(*, force_sizes: bool = False)", source)
        self.assertIn("_apply_alignment_dialog_responsive_layout(force_sizes=True)", source)

    def test_model_preview_draws_selected_part_outline_overlay(self) -> None:
        source = _widgets_source()
        self.assertIn("def _alignment_selected_batch_indices", source)
        self.assertIn("def _alignment_batch_mvp_matrix", source)
        self.assertIn("def _draw_alignment_selected_mesh_outlines", source)
        self.assertIn("Selected part outline", source)
        self.assertIn("self._draw_alignment_selected_mesh_outlines(painter)", source)

    def test_alignment_drag_commits_final_release_delta_before_clearing_live_transform(self) -> None:
        widget_source = _widgets_source()
        main_source = _main_window_source()
        self.assertIn("def _update_alignment_rotation_drag", widget_source)
        self.assertIn("def _update_alignment_axis_drag", widget_source)
        release_start = widget_source.index("if self._alignment_rotation_drag_active and event.button() == Qt.LeftButton:")
        release_end = widget_source.index("if self._drag_active and event.button() == Qt.LeftButton:", release_start)
        release_block = widget_source[release_start:release_end]
        self.assertLess(
            release_block.index("self._update_alignment_rotation_drag(event.position(), event.modifiers())\n            total = QVector3D"),
            release_block.index("self.alignment_rotation_finished.emit(float(total.x()), float(total.y()), float(total.z()))"),
        )
        self.assertLess(
            release_block.index("self.alignment_rotation_finished.emit(float(total.x()), float(total.y()), float(total.z()))"),
            release_block.index("self.clear_alignment_live_rotation()"),
        )
        self.assertLess(
            release_block.index("self._update_alignment_axis_drag(event.position(), event.modifiers())\n            total = QVector3D"),
            release_block.index("self.alignment_drag_finished.emit(float(total.x()), float(total.y()), float(total.z()))"),
        )
        self.assertLess(
            release_block.index("self.alignment_drag_finished.emit(float(total.x()), float(total.y()), float(total.z()))"),
            release_block.index("self.clear_alignment_live_translation()"),
        )
        translation_start = main_source.index("def _commit_alignment_preview_translation")
        rotation_start = main_source.index("def _commit_alignment_preview_rotation")
        commit_block = main_source[translation_start:main_source.index("reset_location_button.clicked.connect", rotation_start)]
        self.assertNotIn("QTimer.singleShot(0, _refresh_static_dialog_preview)", commit_block)
        self.assertIn("def _alignment_part_source_indices_for_commit", main_source)
        self.assertIn("selected_source_highlight_indices", main_source[main_source.index("def _alignment_part_source_indices_for_commit"):translation_start])
        self.assertIn("_apply_alignment_part_translation_delta(part_source_indices, (dx, dy, dz))", commit_block)
        self.assertIn("_apply_alignment_part_rotation_delta(part_source_indices, (dx, dy, dz))", commit_block)
        self.assertIn("_queue_global_transform_preview_update()", commit_block)
        self.assertIn("_queue_static_preview_rebuild()", commit_block)
        self.assertIn("preview_widget.alignment_rotation_finished.connect(_commit_alignment_preview_rotation)", main_source)
        self.assertIn("preview_widget.set_alignment_translation_sensitivity(0.85)", main_source)
        self.assertIn("def set_alignment_translation_sensitivity", widget_source)
        self.assertIn("def _alignment_source_units_per_pixel", widget_source)
        self.assertIn('self._alignment_drag_axis == "screen"', widget_source)

    def test_alignment_dialog_has_obj_mesh_edit_controls_and_revision_hooks(self) -> None:
        main_source = _main_window_source()
        widget_source = _widgets_source()
        archive_source = _archive_modding_source()
        static_source = _static_replacer_source()

        self.assertIn("mesh_edit_supported = bool(", main_source)
        self.assertIn("Mesh Edit needs a parsed static mesh source", main_source)
        self.assertIn('mesh_edit_group = QGroupBox("Mesh Edit")', main_source)
        self.assertIn('mesh_edit_enabled_checkbox = QCheckBox("Enable mesh edit")', main_source)
        self.assertIn('mesh_edit_target_combo = QComboBox()', main_source)
        self.assertIn('("Vertex Select", "vertex")', main_source)
        self.assertIn('("Grab", "grab")', main_source)
        self.assertIn('("Inflate", "inflate")', main_source)
        self.assertIn('("Pinch", "pinch")', main_source)
        self.assertIn('("Smooth", "smooth")', main_source)
        self.assertIn('("Vertex", "vertex")', main_source)
        self.assertIn('mesh_edit_mirror_checkbox = QCheckBox("Mirror X")', main_source)
        self.assertIn('mesh_edit_show_vertices_checkbox = QCheckBox("Show vertices")', main_source)
        self.assertIn('mesh_edit_select_brush_button = QPushButton("Select Brush")', main_source)
        self.assertIn('mesh_edit_clear_selection_button = QPushButton("Clear Selection")', main_source)
        self.assertIn('mesh_edit_undo_button = QPushButton("Undo")', main_source)
        self.assertIn('mesh_edit_redo_button = QPushButton("Redo")', main_source)
        self.assertIn('mesh_edit_reset_part_button = QPushButton("Reset Edited Part")', main_source)
        self.assertIn('mesh_edit_revision = {"value": 0}', main_source)
        self.assertIn('source_geometry_revision = {"value": 0}', main_source)
        self.assertIn("appended_source_indices: set[int] = set()", main_source)
        self.assertIn("independent_output_source_indices: set[int] = set()", main_source)
        self.assertIn("preview_only_source_indices: set[int] = set()", main_source)
        self.assertIn("source_overlay_preview_index_map: Dict[int, int] = {}", main_source)
        self.assertIn("mesh_edit_undo_stack: List[ParsedMesh] = []", main_source)
        self.assertIn("mesh_edit_redo_stack: List[ParsedMesh] = []", main_source)
        self.assertIn('"mesh_edit_revision": int(mesh_edit_revision.get("value", 0) or 0)', main_source)
        self.assertIn('"source_geometry_revision": int(source_geometry_revision.get("value", 0) or 0)', main_source)
        self.assertIn("static_preview_geometry_cache.clear()", main_source)
        self.assertIn("mesh_edit_active_stroke: Dict[str, object] = {}", main_source)
        self.assertIn("def _mesh_edit_begin_stroke", main_source)
        self.assertIn("def _mesh_edit_apply_preview_payload", main_source)
        self.assertIn("def _mesh_edit_finish_stroke", main_source)
        self.assertIn("def _mesh_edit_cancel_stroke", main_source)
        self.assertIn("mesh_edit_stroke_started.connect(_mesh_edit_begin_stroke)", main_source)
        self.assertIn("mesh_edit_stroke_previewed.connect(_mesh_edit_apply_preview_payload)", main_source)
        self.assertIn("mesh_edit_stroke_finished.connect(_mesh_edit_finish_stroke)", main_source)
        self.assertIn("mesh_edit_stroke_cancelled.connect(_mesh_edit_cancel_stroke)", main_source)
        self.assertIn("mesh_edit_selection_changed.connect(_mesh_edit_selection_changed)", main_source)
        self.assertIn("static_preview_geometry_cache.clear()", main_source)
        self.assertIn("_refresh_static_dialog_preview(live_mesh_edit=True)", main_source)
        self.assertIn("edited_source_mesh = None", main_source)
        self.assertIn("include_edited_source_mesh", main_source)
        self.assertIn('or int(placement_snapshot.get("source_geometry_revision", 0) or 0) > 0', main_source)
        self.assertIn("clone_mesh_for_editing(replacement_mesh_for_mapping)", main_source)
        self.assertIn("mesh.source_submesh_index = -1", main_source)
        self.assertIn("mesh.source_vertex_indices = []", main_source)

        self.assertIn("mesh_edit_stroke_finished = Signal(object)", widget_source)
        self.assertIn("mesh_edit_stroke_started = Signal(object)", widget_source)
        self.assertIn("mesh_edit_stroke_previewed = Signal(object)", widget_source)
        self.assertIn("mesh_edit_stroke_cancelled = Signal(object)", widget_source)
        self.assertIn("mesh_edit_selection_changed = Signal(object)", widget_source)
        self.assertIn("def set_mesh_editing_enabled", widget_source)
        self.assertIn("def set_model_preserving_view", widget_source)
        self.assertIn("def set_mesh_edit_target_mode", widget_source)
        self.assertIn("def set_mesh_edit_tool", widget_source)
        self.assertIn("def set_mesh_edit_brush_settings", widget_source)
        self.assertIn("def clear_mesh_edit_vertex_selection", widget_source)
        self.assertIn("def select_mesh_edit_brush_vertices", widget_source)
        self.assertIn("def _mesh_edit_screen_cache_entries_at", widget_source)
        self.assertIn("def _mesh_edit_candidate_screen_weight", widget_source)
        self.assertIn("source_vertex_weights", widget_source)
        self.assertIn("if vertex_selection_mode and selected_candidates:", widget_source)
        self.assertIn("Brush drags all vertices in radius", widget_source)
        self.assertIn("def _mesh_edit_emit_preview", widget_source)
        self.assertIn("def _mesh_edit_selected_candidates", widget_source)
        self.assertIn("self._draw_mesh_edit_overlay(painter)", widget_source)
        self.assertIn('"source_submesh_index": int(source_submesh_index)', widget_source)
        self.assertIn('"source_vertex_indices": ordered_indices', widget_source)
        self.assertIn('"source_vertex_weights": tuple((int(index), float(weights[index]))', widget_source)
        self.assertIn("Brush edits all editable vertices inside the brush radius", main_source)
        self.assertIn("vertex_weights=vertex_weights or None", main_source)

        self.assertIn("source_submesh_index=submesh_index", archive_source)
        self.assertIn("source_vertex_indices=list(range(len(submesh.vertices)))", archive_source)
        self.assertIn("edited_source_mesh: ParsedMesh | None = None", static_source)
        self.assertIn("class StaticIndependentPart", static_source)
        self.assertIn("independent_output_parts: list[StaticIndependentPart] = field(default_factory=list)", static_source)
        self.assertIn("additional_supplemental_files: list[object] = field(default_factory=list)", static_source)
        self.assertIn("def _replacement_mesh_from_options", static_source)

    def test_alignment_dialog_can_append_mesh_parts_in_geometry(self) -> None:
        source = _main_window_source()
        scene_source = Path("cdmw/modding/scene_importer.py").read_text(encoding="utf-8")

        self.assertIn('append_mesh_part_button = QPushButton("Add Mesh Part...")', source)
        self.assertIn("def _append_mesh_part_to_geometry", source)
        self.assertIn("append_scene_import_to_mesh(", source)
        self.assertIn("refresh_parsed_mesh_totals", source)
        self.assertIn("def _normalize_appended_part_to_work_area", source)
        self.assertIn("def _reference_vertices_for_appended_part", source)
        self.assertIn('preview_detail_combo.addItem("Auto detail", "auto")', source)
        self.assertIn('preview_detail_combo.addItem("Full geometry", "full")', source)
        self.assertIn("preview_detail_combo.currentIndexChanged.connect(_set_preview_detail)", source)
        self.assertIn("def _adaptive_alignment_preview_face_limit", source)
        self.assertIn("def _alignment_preview_detail_mode", source)
        self.assertIn("def _alignment_preview_widget_render_settings", source)
        self.assertIn("settings.disable_all_support_maps = True", source)
        self.assertIn("widget.set_high_quality_textures(not interactive_preview)", source)
        self.assertIn('mode in {"auto", "full", "fast"}', source)
        self.assertIn("def _alignment_preview_is_interactive", source)
        self.assertIn('if preview_detail_mode == "auto" and total_faces <= 120_000', source)
        self.assertIn('static_preview_interactive_until["time"] = time.monotonic() + 0.8', source)
        self.assertIn('"preview_detail": _alignment_preview_detail_mode()', source)
        self.assertIn("target_total_faces=75_000", source)
        self.assertIn("maximum=22_000", source)
        self.assertIn("def _alignment_preview_selected_source_face_limit", source)
        self.assertIn("def _alignment_preview_background_source_face_limit", source)
        self.assertIn("return 35_000", source)
        self.assertIn("needs_recenter = math.dist(source_center, reference_center)", source)
        self.assertIn("centered in the current asset work area", source)
        self.assertIn("scaled {scale:.4g}x for preview control", source)
        self.assertIn("appended_source_indices.update", source)
        self.assertIn("def _prompt_assign_appended_mesh_parts", source)
        self.assertIn("Assign Added Mesh Parts", source)
        self.assertIn("AssignmentSummary", source)
        self.assertIn("AssignmentTree", source)
        self.assertIn("def _highlight_assignment_source", source)
        self.assertIn("def _assignment_target_for_source", source)
        self.assertIn("selected_target_original_highlight_indices.add", source)
        self.assertIn("def _rollback_cancelled_appended_mesh_part_import", source)
        self.assertIn('assignment_action == "cancel"', source)
        self.assertIn("Geometry was unchanged", source)
        self.assertIn("preview_only_source_indices.update", source)
        self.assertIn("Default: attach to the selected target when one is selected.", source)
        self.assertNotIn('target_combo.addItem("Create new part", -2)', source)
        self.assertIn('target_combo.addItem("Preview only", -1)', source)
        self.assertIn("Detected {len(tuple(discovered_texture_files or ())):,} texture file(s)", source)
        self.assertIn("inject_base_color_checkbox.setChecked(True)", source)
        self.assertIn("Attach All To Current", source)
        self.assertIn("Assign By Order", source)
        self.assertIn('apply_button = QPushButton("Apply Attachments")', source)
        self.assertIn("Preview-only parts are visible in this session but are blocked from final PAC/PAM export.", source)
        self.assertIn("Attach to {_target_display_name(target_index)}", source)
        self.assertIn("row_target_combos", source)
        self.assertIn("assignments_by_target", source)
        self.assertIn("Open Textures", source)
        self.assertIn("Attach Added Mesh Parts", source)
        self.assertIn("def _maybe_reduce_high_density_scene_import", source)
        self.assertIn("def _maybe_flatten_scene_import_parts", source)
        self.assertIn("Mesh Contains Multiple Parts", source)
        self.assertIn("Flatten To One Part", source)
        self.assertIn("Keep Separate Parts", source)
        self.assertIn("Group By Material", source)
        self.assertIn("group_scene_import_result_parts_by_material(", source)
        self.assertIn("flatten_scene_import_result_parts(", source)
        self.assertIn("High Density Mesh Import", source)
        self.assertIn("Keep Full Quality", source)
        self.assertIn("Reduce For Performance/Size", source)
        self.assertIn("def _format_scene_import_byte_size", source)
        self.assertIn("def format_scene_import_file_size_summary", source)
        self.assertIn("linked mesh buffer(s)", source)
        self.assertNotIn("source_path.stat().st_size / (1024 * 1024):.1f", source)
        self.assertIn("reduce_scene_import_result_quality", source)
        self.assertIn("part {appended_ordinal}/{appended_source_count}", source)
        self.assertIn("def _append_unmapped_appended_source_overlays", source)
        self.assertIn("source_overlay_preview_index_map", source)
        self.assertIn("preview_submesh_index_map: Dict[int, int] = {}", source)
        self.assertIn("parsed_submesh_index_map: Dict[int, int] | None = None", source)
        self.assertIn("parsed_submesh_index_map[submesh_position] = len(preview_meshes) - 1", source)
        self.assertIn("mapped_index = preview_submesh_index_map.get(target_index)", source)
        self.assertIn("source_overlay_preview_index_map[int(independent_part.source_submesh_index)] = preview_index", source)
        self.assertIn("direct_source_indices_have_appended", source)
        self.assertIn("direct_source_indices_have_mapped", source)
        self.assertIn("_alignment_preview_background_source_face_limit(background_overlay_indices)", source)
        self.assertIn("global_transform_source_indices=_mapped_source_indices(current_mappings)", source)
        self.assertIn('"global_transform_exempt_source_indices": sorted(int(index) for index in appended_source_indices)', source)
        self.assertIn("appended_geometry = int(source_geometry_revision.get", source)
        self.assertIn("spin.setKeyboardTracking(False)", source)
        self.assertIn('part_nudge_step_spin = _part_spin(0.005, 0.00001, 1.0, 5, 0.0005)', source)
        self.assertIn('center_part_button = QPushButton("Center To Target")', source)
        self.assertIn("def _nudge_selected_part_axis", source)
        self.assertIn("def _center_selected_part_on_target", source)
        self.assertIn('QShortcut(QKeySequence("Ctrl+PageUp"), dialog)', source)
        self.assertIn("import_scene_mesh_with_report(source_path)", source)
        self.assertIn("source_geometry_revision[\"value\"]", source)
        self.assertIn("dialog_added_supplemental_files", source)
        self.assertIn("additional_supplemental_files=list(dialog_added_supplemental_files)", source)
        self.assertIn("FBX Import Deferred", source)
        self.assertIn("append_mesh_part_button.clicked.connect(_append_mesh_part_to_geometry)", source)
        self.assertIn("class SceneMeshAppendResult", scene_source)
        self.assertIn("def flatten_scene_import_result_parts", scene_source)
        self.assertIn("def append_scene_import_to_mesh", scene_source)

    def test_alignment_geometry_tab_uses_compact_source_parts_master_list(self) -> None:
        source = _main_window_source()
        self.assertIn('source_parts_group = QGroupBox("Source Parts")', source)
        self.assertIn("source_parts_layout.addWidget(source_tree, 0)", source)
        self.assertIn("parts_layout.addWidget(source_parts_group, 0)", source)
        self.assertIn('control_tabs.addTab(routing_tab, "Routing")', source)
        self.assertIn("routing_layout.addWidget(mapping_group, 1)", source)
        self.assertNotIn("routing_layout.setAlignment(Qt.AlignTop)", source)
        self.assertIn("mesh_edit_group.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)", source)
        self.assertIn("mesh_edit_layout.setColumnMinimumWidth(0, 72)", source)
        self.assertIn("mesh_edit_layout.addWidget(mesh_edit_tool_combo, 1, 3)", source)
        self.assertIn("source_mix_tray.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)", source)
        self.assertNotIn("source_mix_intro_row.addWidget", source)
        self.assertIn("parts_layout.addStretch(1)", source)
        self.assertIn("QTimer.singleShot(0, _refresh_static_dialog_preview)", source)
        self.assertIn("QTimer.singleShot(0, _clear_all_part_selections)", source)
        self.assertLess(
            source.index("QTimer.singleShot(0, _refresh_static_dialog_preview)"),
            source.index("QTimer.singleShot(0, _clear_all_part_selections)"),
        )

    def test_alignment_numeric_spinboxes_commit_typed_text(self) -> None:
        source = _main_window_source()
        self.assertIn("def _commit_spinbox_text", source)
        self.assertIn("spin.interpretText()", source)
        self.assertIn("part_spin.editingFinished.connect", source)
        self.assertIn("mesh_edit_radius_spin.editingFinished.connect", source)
        self.assertIn("def _commit_global_transform_spin", source)
        self.assertIn("spin.editingFinished.connect(lambda spin=spin: _commit_global_transform_spin(spin))", source)
        self.assertIn("texture_spin.editingFinished.connect", source)
        self.assertIn("def _commit_alignment_numeric_edits", source)
        self.assertIn("_commit_alignment_numeric_edits()", source)

    def test_alignment_transform_controls_are_debounced_and_slider_backed(self) -> None:
        source = _main_window_source()
        self.assertIn("QSlider", source)
        self.assertIn('slider.setObjectName("AlignmentTransformSlider")', source)
        self.assertIn('slider.setObjectName("AlignmentPartTransformSlider")', source)
        self.assertIn("wrapper_layout.addWidget(spin)", source)
        self.assertIn("spin.valueChanged.connect(_sync_slider_from_spin)", source)
        self.assertIn("slider.valueChanged.connect(_sync_spin_from_slider)", source)
        self.assertIn("spin.setKeyboardTracking(False)", source)
        self.assertIn("mesh_edit_radius_spin.setKeyboardTracking(False)", source)
        self.assertIn("mesh_edit_strength_spin.setKeyboardTracking(False)", source)
        self.assertIn("texture_transform_offset_u_spin = _new_uv_transform_spin", source)
        self.assertIn("texture_transform_scale_v_spin = _new_uv_transform_spin", source)

    def test_alignment_transform_preview_uses_fast_path_before_settled_rebuild(self) -> None:
        source = _main_window_source()
        self.assertIn("static_preview_batch_state", source)
        self.assertIn("mapping_edit_refresh_timer.setInterval(260)", source)
        self.assertIn("edit.editingFinished.connect(_flush_mapping_edit_refresh)", source)
        self.assertIn("_refresh_source_assignment_columns(lightweight=True)", source)
        self.assertIn("spin.valueChanged.connect(_queue_global_transform_preview_update)", source)
        self.assertIn("def _queue_global_transform_preview_update", source)
        self.assertIn("def _queue_part_transform_preview_update", source)
        self.assertIn("preview_widget.set_alignment_committed_preview_transform", source)
        self.assertIn("static_preview_settle_timer.start()", source)
        self.assertIn("_capture_static_preview_baked_transform_state(selected_preview_indices)", source)
        self.assertIn('preview_performance_label = QLabel("Preview timing: waiting for first refresh.")', source)
        self.assertIn("geometry_elapsed_ms", source)
        self.assertIn("prepared_elapsed_ms", source)
        self.assertIn("refreshed_preview_widgets: List[ModelPreviewWidget] = []", source)
        self.assertIn("for widget in refreshed_preview_widgets", source)
        self.assertIn("_last_gl_upload_ms", source)
        self.assertIn("def _set_global_fast_preview_edit_scope", source)
        self.assertIn("preview_widget.set_alignment_editable_mesh_range(0, -1)", source)
        self.assertIn("def _set_part_fast_preview_edit_scope", source)

    def test_alignment_fast_preview_does_not_replace_export_options(self) -> None:
        source = _main_window_source()
        static_source = _static_replacer_source()
        self.assertIn("def _current_static_alignment_transform() -> StaticReplacementTransform:", source)
        self.assertIn("rotate_xyz_degrees=(\n                            float(rotate_x_spin.value())", source)
        self.assertIn("offset_xyz=(\n                            float(offset_x_spin.value())", source)
        self.assertIn("placement_snapshot = _current_static_placement_snapshot", source)
        self.assertIn("include_preview_only_independent_parts=False", source)
        self.assertNotIn("set_alignment_committed_preview_transform", static_source)

    def test_alignment_dialog_clears_part_selection_when_leaving_geometry(self) -> None:
        source = _main_window_source()
        self.assertIn("def _clear_part_selections_when_leaving_geometry", source)
        self.assertIn("if control_tabs.widget(index) in {parts_tab, routing_tab}:", source)
        self.assertIn("selected_source_part[\"index\"] = -1", source)
        self.assertIn("selected_target_slot[\"index\"] = -1", source)
        self.assertIn("source_tree_hover_direct_indices.clear()", source)
        self.assertIn("control_tabs.currentChanged.connect(_clear_part_selections_when_leaving_geometry)", source)

    def test_alignment_geometry_can_duplicate_and_mirror_source_parts(self) -> None:
        source = _main_window_source()
        self.assertIn('duplicate_part_button = QPushButton("Duplicate Part")', source)
        self.assertIn('mirror_duplicate_part_button = QPushButton("Mirror Duplicate")', source)
        self.assertIn("def _duplicate_selected_part(*, mirrored: bool = False)", source)
        self.assertIn("def _mirror_submesh_x(source: object, plane_x: float)", source)
        self.assertIn("(int(face[0]), int(face[2]), int(face[1]))", source)
        self.assertIn("duplicate_part_button.clicked.connect(lambda _checked=False: _duplicate_selected_part(mirrored=False))", source)
        self.assertIn("mirror_duplicate_part_button.clicked.connect(lambda _checked=False: _duplicate_selected_part(mirrored=True))", source)

    def test_texture_plan_has_single_bulk_apply_action(self) -> None:
        source = _main_window_source()
        self.assertIn('QPushButton("Apply Suggested Overrides...")', source)
        self.assertIn('QPushButton("Use Selected Source Textures")', source)
        self.assertIn("selection_context_frame = QFrame(content_container)", source)
        self.assertIn("def _update_selection_context", source)
        self.assertIn("def _target_index_for_name", source)
        self.assertIn("def _highlight_texture_plan_item", source)
        self.assertIn("material_routing_tree.currentItemChanged.connect", source)
        self.assertIn("material_plan_tree.currentItemChanged.connect", source)
        self.assertIn("selected_target_original_highlight_indices.add(target_index)", source)
        self.assertIn("material_plan_advanced_section = CollapsibleSection(", source)
        self.assertIn('"Advanced: Routing and per-part texture details"', source)
        self.assertIn("expanded=True", source)
        self.assertNotIn('material_plan_advanced_checkbox = QCheckBox("Advanced features")', source)
        self.assertNotIn("material_plan_advanced_checkbox.toggled.connect(_sync_material_plan_advanced_visibility)", source)
        self.assertNotIn("def _sync_material_plan_advanced_visibility", source)
        self.assertIn("material_plan_advanced_section.body_layout.addWidget(material_routing_tree)", source)
        self.assertIn("material_plan_layout.addWidget(material_plan_tree)", source)
        self.assertIn("material_routing_tree = QTreeWidget()", source)
        self.assertIn("build_source_material_routing_plan", source)
        self.assertIn("is_static_replacement_helper_material_name", source)
        self.assertIn("Texture Contract:", source)
        self.assertIn("stock/shared shader layers and helper wrappers preserved by default", source)
        self.assertIn("def _apply_replacement_texture_plan_to_overrides", source)
        self.assertIn("def _apply_selected_source_material_textures", source)
        self.assertIn("apply_selected_source_textures_button.clicked.connect(_apply_selected_source_material_textures)", source)
        self.assertIn('QPushButton("Apply all Suggested for Override Source")', source)
        self.assertIn("def _apply_all_suggested_override_sources", source)
        self.assertIn("it is not a guarantee that the replacement will render correctly in game", source)
        self.assertIn("apply_all_suggested_overrides_button.clicked.connect(_apply_all_suggested_override_sources)", source)
        self.assertIn('QGroupBox("Texture Orientation / UV Transform")', source)
        self.assertIn("StaticTextureUvTransform", source)
        self.assertIn("def _current_texture_uv_transforms", source)
        self.assertIn('"texture_uv_transforms": _current_texture_uv_transforms()', source)
        self.assertIn('texture_uv_transforms=list(placement_snapshot.get("texture_uv_transforms", []) or [])', source)
        self.assertIn('added_texture_group = QGroupBox("Added Part Textures")', source)
        self.assertIn("added_texture_layout.setAlignment(Qt.AlignTop)", source)
        self.assertIn("added_texture_layout.addWidget(added_texture_tree, 0)", source)
        self.assertIn("def _sync_added_part_texture_group_size", source)
        self.assertIn("added_texture_group.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)", source)
        self.assertIn("added_texture_group.setMaximumHeight(360)", source)
        self.assertIn("def _refresh_added_part_texture_tree", source)
        self.assertIn("_sync_added_part_texture_group_size(has_rows)", source)
        self.assertIn("def _set_added_part_texture_override", source)
        self.assertIn('"source_material_texture_overrides": _current_source_material_texture_overrides()', source)
        self.assertIn('placement_snapshot.get("source_material_texture_overrides", [])', source)
        self.assertIn('CollapsibleSection("Advanced Original DDS Overrides", expanded=False)', source)
        self.assertLess(
            source.index("textures_layout.addWidget(material_plan_group, 0)"),
            source.index('CollapsibleSection("Advanced Original DDS Overrides", expanded=False)'),
        )
        self.assertIn("material_plan_layout.addWidget(texture_transform_group)", source)
        self.assertIn("texture_detail_browser.setMinimumWidth(300)", source)
        self.assertIn("QTextBrowser { font-size: 8px; line-height: 1.08; }", source)
        self.assertIn("material_plan_layout.setContentsMargins(5, 3, 5, 3)", source)
        self.assertIn("texture_transform_layout.setContentsMargins(5, 3, 5, 3)", source)
        self.assertIn("texture_workflow_layout.setSpacing(3)", source)
        self.assertIn("compact = Path(normalized).name or normalized", source)
        self.assertNotIn('CollapsibleSection("Texture Assignments", expanded=True)', source)
        self.assertNotIn("texture_override_tree.setCurrentItem(texture_override_tree.topLevelItem(0))", source)
        self.assertNotIn('QPushButton("Apply Suggested...")', source)
        self.assertNotIn('QPushButton("Assign Matching Role...")', source)

    def test_helmet_alignment_warns_about_head_hair_visibility(self) -> None:
        source = _main_window_source()
        self.assertIn("Helmet visibility", source)
        self.assertIn("It does not change whether the game hides the character head or hair.", source)
        self.assertIn("choose an original helmet with matching visibility rules", source)

    def test_alignment_routing_can_group_by_source_material(self) -> None:
        source = _main_window_source()
        self.assertIn('QPushButton("Group by Source Material")', source)
        self.assertIn("def _apply_source_material_grouped_routing", source)
        self.assertIn("def _texture_set_for_source_index", source)
        self.assertIn("Manual original-DDS override assignments can force the old slot layout", source)
        self.assertIn("The replacement has more source material group(s) than original target draw slot(s).", source)
        self.assertIn("group_materials_button.clicked.connect(_apply_source_material_grouped_routing)", source)

    def test_in_game_mesh_swap_reuses_alignment_import_path(self) -> None:
        source = _main_window_source()
        self.assertIn('QPushButton("Swap With In-Game Mesh...")', source)
        self.assertIn("pending_in_game_mesh_swap_target", source)
        self.assertIn("def _handle_archive_in_game_mesh_swap_entry", source)
        self.assertIn('"Start In-Game Mesh Swap..."', source)
        self.assertIn('"Use This as Swap Source..."', source)
        self.assertIn('"Use as Swap Source..."', source)
        self.assertIn("def _start_archive_in_game_mesh_swap", source)
        self.assertIn("def _load_archive_mesh_scene_import_result", source)
        self.assertIn("def _build_archive_swap_source_texture_evidence", source)
        self.assertIn("def _source_texture_relevance_score", source)
        self.assertIn('texture_entries_by_key: "OrderedDict[str, ArchiveEntry]"', source)
        self.assertIn("resolve_material_texture_graph(entry", source)
        self.assertIn("source_texture_evidence_by_local_path", source)
        self.assertIn("parse_material_sidecar_profile", source)
        self.assertIn("material_profile_label", source)
        self.assertIn("material_profile_shader", source)
        self.assertIn("target_shader_family", source)
        self.assertIn("def _source_sidecar_evidence_score", source)
        self.assertIn("Found {len(source_texture_paths):,} source DDS texture candidate(s) from source .pac_xml/sidecars.", source)
        self.assertIn("force_static_replacement=True", source)
        self.assertIn('placement_review_title="In-Game Mesh Swap Placement"', source)
        self.assertIn("swap_placement_note = (", source)
        self.assertIn("Review offset, rotation, scale, and part mapping before export.", source)
        self.assertIn("Replacement Preview is the candidate location/rotation/scale that will be written.", source)
        self.assertIn("Final loose export preview may differ if packaged material sidecar or DDS bindings resolve differently.", source)
        self.assertIn('CollapsibleSection("Import Notes", expanded=False)', source)
        self.assertIn('CollapsibleSection("Compatibility Details", expanded=False)', source)
        self.assertIn('placement_group = QWidget()', source)
        self.assertIn('QPushButton("Review Placement" if placement_context_note.strip() else "Continue")', source)
        self.assertIn("dialog_title=setup.placement_review_title or \"Mesh Replacement Alignment\"", source)
        self.assertIn("placement_context_note=setup.placement_context_note", source)
        self.assertIn("source_texture_evidence=setup.source_texture_evidence", source)
        self.assertIn("scene_import_result=setup.scene_import_result", source)
        self.assertIn("source_display_label=setup.source_label", source)
        self.assertNotIn("def _prompt_archive_in_game_mesh_source", source)
        self.assertIn("class InGameMeshSwapScopeSelection", source)
        self.assertIn("use_source_model_payload_directly", source)
        self.assertIn("retarget_source_family_files", source)
        self.assertIn('dialog.setWindowTitle("In-Game Mesh Swap Scope")', source)
        self.assertIn('QCheckBox("Use source model payload directly instead of rebuilding target geometry")', source)
        self.assertIn('QCheckBox("Retarget selected source item-family files to target paths")', source)
        self.assertIn('QPushButton("Select Item Family")', source)
        self.assertIn('QPushButton("Select Physics")', source)
        self.assertIn("same_weapon_folder", source)
        self.assertIn("cross-folder physics stays explicit", source)
        self.assertIn("preserve_source_contract_default", source)
        self.assertIn("_pbdSimulationMaterialName", source)
        self.assertIn("Donor material contract warning", source)
        self.assertIn("alignment/rebuild path writes target-slot geometry", source)
        self.assertIn("source_has_larger_material_contract", source)
        self.assertIn("replace_target_sidecar_with_source", source)
        self.assertIn("replace_target_appearance_with_source", source)
        self.assertIn("use_character_swap_plan", source)
        self.assertIn("def _archive_entry_is_equipment_model_for_swap", source)
        self.assertIn("def _archive_entries_allow_character_swap_scope", source)
        self.assertIn('"nude",', source)
        self.assertIn("candidate_tokens = _semantic_tokens(PurePosixPath(normalized_path).stem)", source)
        self.assertIn("return bool(candidate_tokens & part_markers)", source)
        self.assertIn("if allow_character_scope:", source)
        self.assertIn("Disabled for weapon/item swaps; this avoids pulling unrelated head/hair/beard appearance files.", source)
        self.assertIn("def _target_family_path_for_source_companion", source)
        self.assertIn("leading_zero_count", source)
        self.assertIn("def _start_archive_direct_source_model_swap", source)
        self.assertIn('import_mode="direct_source_model_swap"', source)
        self.assertIn("def _archive_entry_is_appearance_descriptor", source)
        self.assertIn("def _archive_character_app_graph_entries_for_swap", source)
        self.assertIn("def _archive_character_app_graph_texture_entries_for_swap", source)
        self.assertIn("def _target_appearance_path_for_source_appearance", source)
        self.assertIn("def _build_in_game_mesh_swap_extra_specs", source)
        self.assertIn("extra_supplemental_specs", source)
        self.assertIn("supplemental_specs_to_include = tuple(setup.extra_supplemental_specs or ()) + tuple(", source)
        self.assertIn("preferred_rebuild_material_sidecar", source)
        self.assertIn("def _archive_model_source_texture_entries_for_swap", source)
        self.assertIn("_archive_model_source_texture_entries_for_swap(source_entry)", source)
        self.assertIn("sidecar_texture_references=source_sidecar_bindings", source)
        self.assertIn("_extract_archive_sidecar_texture_lookup_paths(sidecar_text)", source)
        self.assertIn('str(candidate.extension or "").strip().lower() != ".dds"', source)
        self.assertIn("Checked rows are written as loose replacement payloads", source)
        self.assertIn("REPLACES this game file while enabled; rig/physics-sensitive", source)
        self.assertIn("Appearance descriptors are separate from material sidecars", source)
        self.assertIn("Can replace target appearance descriptor", source)
        self.assertIn('QPushButton("Select Graph Textures")', source)
        self.assertIn('QPushButton("Help: what should I choose?")', source)
        self.assertIn("Recommended character/body swap defaults", source)
        self.assertIn("What this row means", source)
        self.assertIn("def _select_character_graph_entries", source)
        self.assertIn("relationship_edges_by_key", source)
        self.assertIn("edge.include_policy in {ARCHIVE_REL_INCLUDE_REQUIRED, ARCHIVE_REL_INCLUDE_RECOMMENDED}", source)
        self.assertIn('basename.endswith((".app.xml", ".app_xml"))', source)
        self.assertIn('QCheckBox("Use Character Swap Plan (experimental)")', source)
        self.assertIn("character_swap_plan_checkbox.toggled.connect(_character_swap_plan_toggled)", source)
        self.assertIn("Surgical Character Swap Plan appearance patch", source)
        self.assertIn(".pab/.pabc skeleton and .hkx/.hkt physics rows are not merged", source)
        self.assertIn("Full character/body swaps often require matching <code>.app_xml</code>", source)
        self.assertIn("Use <b>Character Swap Plan</b> for experimental full-character/body swaps", source)

    def test_texture_suggestions_require_specific_character_part_tokens(self) -> None:
        source = _main_window_source()
        self.assertIn("def _part_specific_tokens", source)
        self.assertIn('result.add("hand")', source)
        self.assertIn('result.add("body")', source)
        self.assertIn('{"body", "torso", "nude", "skin", "chest", "waist"}', source)
        self.assertIn("target_part_specific = _part_specific_tokens", source)
        self.assertIn("candidate_specific = _part_specific_tokens(candidates[0].stem)", source)
        self.assertIn("if target_specific and candidate_specific and not (target_specific & candidate_specific):", source)
        self.assertIn("texture_files_by_basename", source)
        self.assertIn("texture_files_by_normalized_source_path", source)
        self.assertIn("exact_source_path = texture_files_by_normalized_source_path.get(normalized_target_texture_path)", source)
        self.assertIn("if target_part_specific:", source)
        self.assertIn("if file_part_specific and not (target_part_specific & file_part_specific):", source)
        self.assertIn("continue", source)
        self.assertIn("score -= 60.0", source)
        self.assertIn("score -= 90.0", source)

    def test_mesh_import_setup_dialog_is_compact(self) -> None:
        source = _main_window_source()
        self.assertIn('dialog.setObjectName("MeshImportSetupDialog")', source)
        self.assertIn("dialog.setMinimumSize(760, 460)", source)
        self.assertIn('QGroupBox("Import Summary")', source)
        self.assertIn('QGroupBox("Preflight & Files")', source)
        self.assertLess(
            source.index('summary_layout = QVBoxLayout(summary_group)'),
            source.index("summary_layout.addWidget(source_group)"),
        )
        self.assertIn('QLabel#MetricChip', source)
        self.assertIn('def _compact_path', source)
        self.assertIn("content_scroll = QScrollArea(dialog)", source)
        self.assertIn("def _fit_mesh_import_setup_dialog_to_screen", source)
        self.assertIn("dialog.setMaximumSize(max_width, max_height)", source)
        self.assertIn('preflight_tree = QTreeWidget()', source)
        self.assertIn('preflight_tree.setHeaderLabels(["Check", "Value"])', source)
        self.assertIn('preflight_tree.setMaximumHeight(128)', source)
        self.assertIn('supplemental_list.setMaximumHeight(112)', source)
        self.assertIn("<b>Live Alignment Preview</b> is the transform workspace.", source)
        self.assertIn("After loose export, the Archive Preview switches to a final-output view when possible", source)
        self.assertNotIn("Mesh Replacement automates common part and texture mappings, but some assets still need manual texture-slot review.", source)


if __name__ == "__main__":
    unittest.main()
