from pathlib import Path
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]
MAIN_WINDOW = REPO_ROOT / "cdmw" / "ui" / "main_window.py"


class ArchiveBrowserAssetUnderstandingUiSourceGuards(unittest.TestCase):
    def test_asset_map_tabs_and_preview_health_are_present(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("self.archive_asset_map_tabs = QTabWidget()", source)
        self.assertIn('self.archive_asset_family_button = QPushButton("Asset Family")', source)
        self.assertIn("self.archive_asset_family_button.clicked.connect(self._open_archive_asset_family_workspace_dialog)", source)
        self.assertIn("self.archive_asset_family_summary_label = QLabel", source)
        self.assertIn('self.archive_asset_map_tabs.addTab(self.archive_asset_map_tree, "Asset Family")', source)
        self.assertIn('self.archive_asset_map_tabs.addTab(self.archive_asset_uses_tree, "Uses")', source)
        self.assertIn('self.archive_asset_map_tabs.addTab(self.archive_asset_used_by_tree, "Used By")', source)
        self.assertIn('self.archive_asset_map_tabs.addTab(self.archive_asset_placement_tree, "Placement")', source)
        self.assertIn('self.archive_asset_map_tabs.addTab(self.archive_texture_refs_tree, "Raw Table")', source)
        self.assertIn("self.archive_preview_role_badge = QLabel", source)
        self.assertIn("self.archive_preview_health_label = QLabel", source)
        self.assertIn("def _archive_preview_health_text(", source)
        self.assertIn('"Preview OK"', source)
        self.assertIn('"Physics Metadata"', source)
        self.assertNotIn('"Physics Linked"', source)
        self.assertIn('"Name Inferred"', source)
        self.assertIn("Native Asset Family: schema=v", source)
        self.assertIn("python_graph = build_archive_asset_family_graph(source_entry, tuple(references))", source)
        self.assertIn('graph.attachment_evidence = tuple(getattr(python_graph, "attachment_evidence", ()) or ())', source)

    def test_asset_relationship_actions_use_direct_scope_and_no_live_scan(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("def _scope_current_archive_entry_only(self) -> None:", source)
        self.assertIn("def _current_archive_asset_set_entries(self, *, include_used_by: bool = False, include_hints: bool = False)", source)
        self.assertIn("def _scope_current_archive_asset_set(self, *, include_used_by: bool = False, include_hints: bool = False)", source)
        self.assertIn("def _scope_archive_asset_family_for_entry(self, entry: ArchiveEntry, *, include_hints: bool = False) -> None:", source)
        self.assertIn("def _export_archive_asset_family_for_entry(self, entry: ArchiveEntry, *, include_hints: bool = False) -> None:", source)
        self.assertIn("def _export_current_archive_asset_set(self) -> None:", source)
        self.assertIn("build_archive_item_icon_references_from_catalog(", source)
        self.assertIn('"Item Icons"', source)
        self.assertIn('reference_kind == "item_icon"', source)
        self.assertIn("def _show_archive_smart_actions_menu(self) -> None:", source)
        self.assertIn("self._apply_archive_direct_scope(", source)
        self.assertIn("Single-file scoped Archive Browser to:", source)
        self.assertIn("no full archive scan", source)
        self.assertIn('self.archive_texture_smart_actions_button = QPushButton("Family Actions")', source)
        self.assertIn('self.archive_texture_scope_all_button = QPushButton("Filter to Family")', source)
        self.assertIn('self.archive_texture_export_asset_set_button = QPushButton("Export Family...")', source)
        self.assertIn("def _set_action_button_state(", source)
        self.assertIn("Unavailable:", source)
        self.assertIn("setToolTipsVisible", source)
        self.assertIn('"Export every resolved raw referenced-file row. Use Export Family for the curated Asset Family package."', source)
        self.assertIn('show_asset_set_hints_action = menu.addAction("Show Family + Hints")', source)

    def test_archive_file_context_menu_exposes_role_aware_actions(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("def _show_archive_tree_context_menu(self, position) -> None:", source)
        self.assertIn('preview_action = menu.addAction("Preview")', source)
        self.assertIn('preview_window_action = menu.addAction("Open Preview Window...")', source)
        self.assertIn('export_file_action = menu.addAction("Export File...")', source)
        self.assertIn('extract_file_action = menu.addAction("Extract File...")', source)
        self.assertIn('family_action = menu.addAction("Asset Family...")', source)
        self.assertIn('placement_action = menu.addAction("Open Placement Workspace...")', source)
        self.assertIn('hkx_placement_action = menu.addAction("Open HKX Placement...")', source)
        self.assertIn("self._archive_hkx_placement_candidates_for_entry(entry)", source)
        self.assertIn("self._open_archive_hkx_placement_for_entry(current_entry)", source)
        self.assertIn('import_loose_mod_action = menu.addAction("Import Loose Mod Folder...")', source)
        self.assertIn('modify_original_action = menu.addAction("Modify Original...")', source)
        self.assertIn('texture_editor_action = menu.addAction("Open In Texture Editor...")', source)
        self.assertIn('edit_hkx_action = menu.addAction("Edit HKX...")', source)
        self.assertIn('inspect_sidecar_action = menu.addAction("Inspect Structured Data...")', source)
        self.assertIn('edit_material_action = menu.addAction("Edit Material Values...")', source)

    def test_character_dependency_export_plans_off_ui_thread(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")
        start = source.index("def _export_character_dependency_package_for_entry(")
        end = source.index("        @staticmethod\n        def _archive_entry_identity_key", start)
        body = source[start:end]

        self.assertIn("archive_entries = tuple(self.archive_entries)", body)
        self.assertIn("def task(on_log: Callable[[str], None]) -> object:", body)
        self.assertIn("return build_character_dependency_plan(", body)
        self.assertIn("self._run_utility_task(", body)
        self.assertIn("show_archive_progress=True", body)
        self.assertIn("QTimer.singleShot(", body)
        self.assertIn("def _handle_character_dependency_package_plan", body)
        self.assertNotIn("plan = build_character_dependency_plan(entry, self.archive_entries)", body)

    def test_modify_original_workspace_uses_safe_roundtrip_clone_path(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn('self.archive_model_modify_original_button = QPushButton("Modify Original...")', source)
        self.assertIn("self.archive_model_modify_original_button.clicked.connect(self._modify_current_archive_original_mesh)", source)
        self.assertIn('("Modify Original Mesh", self.archive_model_modify_original_button)', source)
        self.assertIn("def _start_archive_modify_original_workspace(self, entry: ArchiveEntry) -> None:", source)
        self.assertIn('export_archive_mesh(', source)
        self.assertIn("class ModifyOriginalWorkflowSelection:", source)
        self.assertIn('QRadioButton("Edit inside Mesh Replacement (no workspace export)")', source)
        self.assertIn('QRadioButton("Create editable workspace folder")', source)
        self.assertIn('"format": "cdmw_modify_original_workspace_v1"', source)
        self.assertIn('"workspace_mode": "user_workspace" if create_workspace else "internal_app_session"', source)
        self.assertIn('"create_workspace": create_workspace', source)
        self.assertIn('"policy": "safe_clone_workspace_imports_through_mesh_replacement_geometry_path"', source)
        self.assertIn("def _open_modify_original_mesh_setup(", source)
        self.assertIn("selection = self._prompt_archive_modify_original_workspace_options(entry)", source)
        self.assertIn("create_workspace = bool(selection.create_workspace)", source)
        self.assertIn("resolve_skeleton_for_obj=create_workspace", source)
        self.assertIn("session_root = self.settings_file_path.parent / \"modify_original_sessions\"", source)
        self.assertIn("def _cleanup_stale_modify_original_sessions(", source)
        self.assertNotIn("modify_original_auto", source)
        self.assertIn("force_static_replacement=True", source)
        self.assertIn("MeshImportSetupSelection(", source)
        self.assertIn('placement_review_title="Modify Original Geometry"', source)
        self.assertIn("self._start_archive_mesh_patch(", source)
        self.assertIn("MODIFY_ORIGINAL_README.txt", source)
        self.assertIn("find_available_output_path(parent_root / workspace_name)", source)

    def test_modify_original_in_app_clone_skips_obj_skeleton_resolution(self) -> None:
        archive_modding_source = (REPO_ROOT / "cdmw" / "core" / "archive_modding.py").read_text(encoding="utf-8")
        main_window_source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("resolve_skeleton_for_obj: bool = True", archive_modding_source)
        self.assertIn('export_kind == "fbx" or bool(resolve_skeleton_for_obj)', archive_modding_source)
        self.assertIn("resolve_skeleton_for_obj=create_workspace", main_window_source)

    def test_roles_name_evidence_and_grouping_are_user_facing(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn('self.archive_tree.setHeaderLabels(["Name", "Exact Name", "Name Evidence", "Role / Type"', source)
        self.assertIn('"Package", "State", "Path"', source)
        self.assertIn('self.archive_tree.setProperty("cdmw_disable_auto_column_fill", True)', source)
        self.assertIn('"ui/archive_tree_v4_column_widths"', source)
        self.assertIn('"ui/archive_tree_v4_column_order"', source)
        self.assertIn('"ui/archive_tree_v4_hidden_columns"', source)
        self.assertIn('"ui/archive_tree_v4_sort_column"', source)
        self.assertIn('"ui/archive_tree_v4_sort_order"', source)
        self.assertIn("archive_header.sectionClicked.connect(self._handle_archive_tree_header_clicked)", source)
        self.assertIn("def _handle_archive_tree_header_clicked(self, column: int) -> None:", source)
        self.assertIn("sort_archive_entries_for_browser(", source)
        self.assertIn("preserve_direct_file_order=self._archive_tree_sort_active()", source)
        self.assertNotIn("self.archive_tree.setSortingEnabled", source)
        self.assertNotIn("self.archive_tree.sortItems", source)
        self.assertNotIn('"ui/archive_tree_v2_column_widths"', source)
        self.assertIn("def _archive_entry_role_label(", source)
        self.assertIn("def _archive_asset_map_group_label(", source)
        self.assertIn("def _archive_known_used_by_references(", source)
        self.assertIn("def _archive_entry_override_state(", source)
        self.assertIn("active_archive_entry_for_virtual_path", source)
        self.assertIn('"Active mod"', source)
        self.assertIn('"Shadowed original"', source)
        self.assertIn('"Selected Model"', source)
        self.assertIn('"Attachment / Placement"', source)
        self.assertIn('"Physics / HKX"', source)
        self.assertIn('"MeshInfo"', source)
        self.assertIn('"Prefab / Metadata"', source)
        self.assertIn('"Exact localization"', source)
        self.assertIn('"Name hint: {first_related_name}"', source)
        self.assertIn("variant_count", source)

    def test_large_category_view_population_is_batched(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("browser_state[\"category_entry_indexes\"] = build_archive_category_entry_index", source)
        self.assertIn("build_browser_category_index = bool(", source)
        self.assertIn("startup_deferred_archive_load = bool(", source)
        self.assertIn("build_category_index=build_browser_category_index", source)
        self.assertIn("build_category_index=rebuild_category_index", source)
        self.assertIn("elif refresh_archive_browser:", source)
        self.assertIn("self.archive_tree_category_population_timer", source)
        self.assertIn("def _begin_archive_category_population(", source)
        self.assertIn("def _continue_archive_category_population(self) -> None:", source)
        self.assertIn("self._begin_archive_category_population(item, category, entry_indexes)", source)
        self.assertIn("category = str(value or \"\")", source)
        self.assertIn("collected_indexes.update(self._archive_category_entry_indexes().get(category, []))", source)
        self.assertIn("and not self._archive_category_index_ready()", source)
        self.assertIn('("category_index_s", "category_index")', source)
        self.assertNotIn("else build_archive_category_entry_index(self.archive_filtered_entries)", source)
        self.assertNotIn("self.archive_tree_category_entry_indexes = build_archive_category_entry_index(self.archive_filtered_entries)\n            return self.archive_tree_category_entry_indexes", source)
        self.assertNotIn("if kind == \"category\":\n                self._ensure_archive_category_item_populated(item)", source)
        self.assertIn("category_evidence", source)
        self.assertIn("Category evidence:", source)
        self.assertIn("Generated thumbnail from asset texture", source)

    def test_archive_startup_progress_is_coalesced_for_smooth_splash(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("self._archive_scan_progress_timer = QTimer(self)", source)
        self.assertIn("self._archive_scan_progress_min_interval_s = 1.0 / 30.0", source)
        self.assertIn("def _flush_archive_scan_progress(self) -> None:", source)
        self.assertIn("def _apply_archive_scan_progress(self, current: int, total: int, detail: str) -> None:", source)
        self.assertIn("self._archive_scan_progress_pending = (int(current or 0), int(total or 0), str(detail or \"Working...\"))", source)
        self.assertIn("self._archive_scan_progress_timer.start(delay_ms)", source)
        self.assertIn("self._flush_archive_scan_progress()", source)
        self.assertIn("self.archive_tree_population_time_budget_ms = 6.0", source)
        self.assertIn("self.archive_tree_population_timer.setInterval(12)", source)
        self.assertIn("self.archive_tree_category_population_timer.setInterval(12)", source)
        self.assertIn("return 420, 130", source)
        self.assertIn("current_item is not None and not defer_default_selection", source)

    def test_archive_startup_defers_enhanced_indexes_until_browser_ready(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")
        deferred_message = "Archive enhanced indexes are stale or missing; deferring item-name and name-search indexing until after the browser opens."
        self.assertIn(deferred_message, source)
        self.assertIn("class ArchiveEnhancedIndexWorker", source)
        self.assertIn('"enhanced_index_needs_build"', source)
        self.assertIn('self.archive_enhanced_index_state = "warming"', source)
        self.assertIn("self.archive_deferred_enhanced_index_start_pending = True", source)
        self.assertIn("self._schedule_archive_post_ready_background_work()", source)
        scan_start = source.index("class ArchiveScanWorker")
        scan_end = source.index("class ArchiveDerivedIndexCacheWriteWorker", scan_start)
        scan_body = source[scan_start:scan_end]
        self.assertIn("enhanced_index_needs_build = bool(entries and name_search_index is None)", scan_body)
        self.assertIn("enhanced_index_needs_build = bool(entries)", scan_body)
        self.assertIn('"enhanced_index_needs_build": enhanced_index_needs_build', scan_body)
        self.assertNotIn("build_archive_item_search_index(\n                            entries", scan_body)
        self.assertNotIn("name_search_index = build_archive_name_search_index(\n                        entries", scan_body)

    def test_placement_workspace_and_loose_overlay_review_are_present(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("def _open_archive_attachment_placement_workspace_dialog", source)
        self.assertIn("Placement Swap", source)
        self.assertIn("Placement is prefab/socket driven. HKX rows are physics context only.", source)
        self.assertIn("Choose Placement Source", source)
        self.assertIn("Direction: the asset opened here is the target that changes", source)
        self.assertIn("open a 2H sword, then choose a 1H sword as the placement source", source)
        self.assertIn("Bulk Placement Swap", source)
        self.assertIn("Each row is a target to change; choose one placement source for that row", source)
        self.assertIn("Build One Mod Folder", source)
        self.assertIn("same package rows as each single placement swap", source)
        self.assertIn("def _open_archive_attachment_donor_picker_dialog", source)
        self.assertIn("Search uses the already-built Archive Browser indexes", source)
        self.assertIn("Item Finder cache", source)
        self.assertIn("Basename index", source)
        self.assertIn("Current Archive Browser results", source)
        self.assertIn("class AutoTreeColumnWidthEventFilter(QObject)", source)
        self.assertIn("expand_tree_columns_to_available_width(tree)", source)
        self.assertIn('globals()["_cdmw_tree_column_width_filter_ref"]', source)
        self.assertIn("Add Loose Donor Folder", source)
        self.assertIn("Edit Socket Values", source)
        self.assertIn("Write Loose Socket XML", source)
        self.assertIn("def _open_archive_socket_xml_editor_dialog", source)
        self.assertIn("Numbered XML preview", source)
        self.assertIn("PreviewSyntaxHighlighter", source)
        self.assertIn("splitter = QSplitter(Qt.Vertical)", source)
        self.assertIn("QPlainTextEdit.LineWrapMode.WidgetWidth", source)
        self.assertIn('editor_tabs.addTab(compare_page, "Compare Socket XML")', source)
        self.assertIn('compare_archive_button = QPushButton("Load Archive Socket XML...")', source)
        self.assertIn('compare_copy_selected_button = QPushButton("Copy To Selected Socket")', source)
        self.assertIn("Search uses the cached Archive Browser basename index", source)
        self.assertIn('compare_group = QGroupBox("Socket Value Compare")', source)
        self.assertIn("Compare the actual recovered socket/prefab values", source)
        self.assertIn('target_socket_button = QPushButton("Open Target Socket XML")', source)
        self.assertIn('donor_socket_button = QPushButton("Open Source Socket XML")', source)
        self.assertIn('visual_group = QGroupBox("Visual Placement")', source)
        self.assertIn("Open Visual Placement Preview", source)
        self.assertIn("Import Placement Profile XML", source)
        self.assertIn("Patch PartInOut placement XML", source)
        self.assertIn("Patch character socket XML", source)
        self.assertIn("build_part_in_out_socket_profile_patch", source)
        self.assertIn("build_socket_bone_data_profile_patch", source)
        self.assertIn("Build Placement Copy Package", source)
        self.assertIn("Target that changes", source)
        self.assertIn("Placement source", source)
        self.assertIn("def _build_attachment_donor_package_plan", source)
        self.assertIn("def _attachment_package_target_support_entries", source)
        self.assertIn("def _attachment_package_item_icon_entries", source)
        self.assertIn("def _attachment_package_source_icon_override_rows", source)
        self.assertIn("def _attachment_package_target_prefab_entries_for_donor", source)
        self.assertIn("Target uses side-specific prefab variants", source)
        self.assertIn("Covers target side-specific prefab", source)
        self.assertIn("Copy source prefab bytes", source)
        self.assertIn("Include source socket XML dependency", source)
        self.assertIn("Copy source item icon bytes", source)
        self.assertIn("source icon is copied when resolved", source)
        self.assertIn("Preserve target PAC/model bytes", source)
        self.assertIn("Preserve target material sidecar bytes", source)
        self.assertIn("Preserve target item icon bytes", source)
        self.assertIn("Preserve target PAA/motion bytes", source)
        self.assertIn("Preserve target socket context XML", source)
        self.assertIn("Preserve target HKX/HKT physics bytes", source)
        self.assertIn("Cross weapon-class placement source detected", source)
        self.assertIn("raw source HKX/HKT is not copied", source)
        self.assertIn("Copy source HKX/HKT physics bytes", source)
        self.assertIn("Copy source PAA/motion bytes", source)
        self.assertIn("No original archives will be modified.", source)
        self.assertIn("keeps unproven binary prefab/PAA/HKX writes disabled", source)
        self.assertIn("proven same-length prefab socket-name rewrites", source)
        self.assertIn("build_prefab_socket_name_patch", source)
        self.assertIn("def _open_archive_loose_mod_overlay_dialog", source)
        self.assertIn("Loose Mod Overlay Review", source)
        self.assertIn("Select Exact Family", source)
        self.assertIn("Select All Families", source)
        self.assertIn("Select All Exact Matches", source)
        self.assertIn("Use as Mesh Replacement Source", source)
        self.assertIn("group_source_mix_candidates_by_family(candidates)", source)
        self.assertIn("def _resolve_source_mix_candidate_targets", source)
        self.assertIn("self.archive_entries_by_normalized_path.get(normalized", source)
        self.assertIn("self.archive_entries_by_basename.get(candidate_name", source)
        self.assertIn("candidates = scan_loose_folder_source(scan_root)", source)
        self.assertIn("candidates = self._resolve_source_mix_candidate_targets(candidates)", source)

    def test_relation_selection_covers_asset_map_uses_and_used_by(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("def _archive_reference_from_item(", source)
        self.assertIn('if source == "uses"', source)
        self.assertIn('if source == "used_by"', source)
        self.assertIn('if source == "family"', source)
        self.assertIn("self.current_archive_used_by_references", source)
        self.assertIn("self.current_archive_family_member_rows", source)
        self.assertIn("relation_tree.customContextMenuRequested.connect", source)
        self.assertIn("sender = self.sender()", source)
        self.assertIn("tree = sender if isinstance(sender, QTreeWidget) else self.archive_texture_refs_tree", source)

    def test_dds_asset_family_promotes_used_by_materials_and_models(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("texture_sidecars: List[ArchiveEntry] = []", source)
        self.assertIn("texture_stem_candidates: List[str] = []", source)
        self.assertIn("def add_texture_sidecar(candidate: ArchiveEntry, *, reason: str, confidence: str) -> None:", source)
        self.assertIn("def add_material_sidecar_candidates_for_stem(stem: str) -> None:", source)
        self.assertIn("def add_model_candidates_for_stem(stem: str, *, reason: str, confidence: str) -> None:", source)
        self.assertIn("Material sidecar references this exact texture path.", source)
        self.assertIn("Material sidecar shares the selected texture stem", source)
        self.assertIn("Model shares the selected texture stem in the current archive index", source)
        self.assertIn("Model candidate shares the basename with a material sidecar that references this texture", source)
        self.assertIn('if isinstance(current_entry, ArchiveEntry) and str(current_entry.extension or "").lower() == ".dds":', source)
        self.assertIn("family_references.extend(self.current_archive_used_by_references)", source)
        self.assertIn("asset_family_graph_for_view = build_archive_asset_family_graph(current_entry, tuple(family_references))", source)
        self.assertIn("raw_table_references = list(self.current_archive_model_texture_references)", source)
        self.assertIn('raw_table_sources.extend(("used_by", index) for index in range(len(self.current_archive_used_by_references)))', source)
        self.assertIn('if str(entry.extension or "").lower() == ".dds":', source)
        self.assertIn("combined_references.extend(self._archive_known_used_by_references(entry))", source)

    def test_asset_family_splitter_width_is_stable_across_preview_refresh(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("self.archive_asset_family_preferred_width = 420", source)
        self.assertIn("Preserve the user's Asset Family splitter width while loading or when a file", source)
        self.assertIn('getattr(self, "archive_asset_family_preferred_width", 420)', source)
        self.assertIn('not getattr(self, "_archive_preview_splitter_clamping", False)', source)
        self.assertIn("self.archive_asset_family_preferred_width = sizes[1]", source)
        self.assertIn("def _refresh_archive_asset_family_panel_layout(self, *, prefer_default: bool = False) -> None:", source)
        self.assertIn("def _schedule_archive_asset_family_panel_layout(self, *, prefer_default: bool = False) -> None:", source)
        self.assertIn("self._schedule_archive_asset_family_panel_layout(prefer_default=True)", source)
        self.assertIn("Keep Asset Family visible even in compact or freshly reflowed layouts.", source)
        self.assertIn("target_sizes = [preview_width, max(1, refs_width)]", source)
        self.assertNotIn("target_sizes = [total, 0]", source)

    def test_asset_family_trees_do_not_auto_scroll_horizontally_from_wheel(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("class TreeHorizontalWheelGuard(QObject):", source)
        self.assertIn("event.type() != QEvent.Type.Wheel", source)
        self.assertIn("has_horizontal_delta", source)
        self.assertIn("modifiers & Qt.ShiftModifier", source)
        self.assertIn("horizontal_bar.setValue(max(horizontal_bar.minimum(), min(previous_value, horizontal_bar.maximum())))", source)
        self.assertIn("def _install_tree_horizontal_wheel_guard(self, tree: QTreeWidget) -> None:", source)
        self.assertIn('tree.setProperty("cdmw_disable_auto_column_fill", True)', source)
        self.assertIn("tree.viewport().installEventFilter(guard)", source)
        self.assertIn("self._tree_horizontal_wheel_guards.append(guard)", source)
        self.assertIn("self._install_tree_horizontal_wheel_guard(self.archive_texture_refs_tree)", source)
        self.assertIn("self._install_tree_horizontal_wheel_guard(tree)", source)
        self.assertIn("horizontal_scroll_positions = [", source)

    def test_scope_banner_is_visible_for_direct_asset_scopes(self) -> None:
        source = MAIN_WINDOW.read_text(encoding="utf-8")

        self.assertIn("self.archive_scope_banner_label = QLabel", source)
        self.assertIn("Scope active: {scope_text}. Clear Scope returns to normal archive filtering.", source)
        self.assertIn("self.archive_scope_banner_label.setVisible(True)", source)
        self.assertIn("self.archive_scope_banner_label.setVisible(False)", source)


if __name__ == "__main__":
    unittest.main()
