import unittest
from pathlib import Path

from cdmw.ui.model_library_tab import model_library_texture_status_kind


class ModelLibraryUiSourceGuardTests(unittest.TestCase):
    def test_model_library_texture_status_classification_is_explicit(self) -> None:
        for status in ("Found (3)", "In ZIP (2)", "Resolved (4)"):
            self.assertEqual(model_library_texture_status_kind(status), "present")

        self.assertEqual(model_library_texture_status_kind("None found"), "missing")

        for status in ("Unknown", "Download to check", "Embedded/Unknown", "In ZIP", ""):
            self.assertEqual(model_library_texture_status_kind(status), "unknown")

    def test_main_window_registers_model_library_import_signal(self) -> None:
        source = Path("cdmw/ui/main_window.py").read_text(encoding="utf-8")

        self.assertIn("from cdmw.ui.model_library_tab import ModelLibraryTab", source)
        self.assertIn("self.model_library_tab = ModelLibraryTab", source)
        self.assertIn("import_mesh_requested.connect", source)
        self.assertIn("preview_mesh_requested.connect", source)
        self.assertIn("item_icon_source_generated.connect", source)
        self.assertIn("self._import_local_model_to_current_archive", source)
        self.assertIn("self._preview_model_library_mesh", source)
        self.assertIn("self._handle_model_library_item_icon_generated", source)
        self.assertIn("QMessageBox.information(self, \"Import Mesh\", message)", source)
        self.assertIn("_show_archive_d3d11_hard_failure", source)
        self.assertIn("def task(_log: Callable[[str], None]) -> object:", source)
        self.assertIn('"model_library"', source)
        self.assertIn("def _augment_model_library_scene_import_result", source)
        self.assertIn("def _discover_model_library_supplemental_files", source)
        self.assertIn("self._model_library_texture_search_roots(scene_path, metadata)", source)
        self.assertIn("Model Library companion scan added", source)
        self.assertIn("scene_import_result=scene_import_result", source)
        self.assertIn("Warning: No local texture files were found for this Model Library item.", source)
        self.assertNotIn("SketchfabLibraryTab", source)
        self.assertNotIn("Connect Sketchfab", source)

    def test_mesh_import_setup_warns_when_textures_are_absent_or_unchecked(self) -> None:
        source = Path("cdmw/ui/main_window.py").read_text(encoding="utf-8")

        self.assertIn('QLabel#WarningLabel', source)
        self.assertIn('supplemental_warning_label.setObjectName("WarningLabel")', source)
        self.assertIn("def _refresh_supplemental_warning() -> None:", source)
        self.assertIn("No local texture files were found for this source.", source)
        self.assertIn("Texture files are available, but none are checked.", source)
        self.assertIn("supplemental_list.itemChanged.connect(lambda _item: _refresh_supplemental_warning())", source)
        self.assertIn("_refresh_supplemental_warning()", source)

    def test_model_library_tab_scans_searches_and_shows_manual_file_urls(self) -> None:
        source = Path("cdmw/ui/model_library_tab.py").read_text(encoding="utf-8")

        self.assertIn("scan_local_model_files", source)
        self.assertIn("build_mirror_catalogue_index", source)
        self.assertIn("search_catalogue_records", source)
        self.assertIn("Mirror URL", source)
        self.assertIn("Preferred files", source)
        self.assertIn("preferred_format_checks", source)
        self.assertIn("glTF ZIP", source)
        self.assertIn("Original source ZIP (OBJ/FBX/etc.)", source)
        self.assertIn("_selected_preferred_formats", source)
        self.assertIn("_download_candidates_for_selected_formats", source)
        self.assertIn("Exclude creators", source)
        self.assertIn("creator_exclude_edit", source)
        self.assertIn("creator_excludes=creator_excludes", source)
        self.assertIn("Textures", source)
        self.assertIn("self.result_limit_spin.setRange(1, 5000)", source)
        self.assertIn("QProgressBar", source)
        self.assertIn("task_status_label", source)
        self.assertIn("active_task_label", source)
        self.assertIn("active_task_progress", source)
        self.assertIn("worker.progress.connect(self._handle_task_progress)", source)
        self.assertIn("def _handle_task_progress(self, message: str) -> None:", source)
        self.assertNotIn("worker.progress.connect(lambda", source)
        self.assertIn("def _update_active_task_progress", source)
        self.assertIn("empty_results_label", source)
        self.assertIn("setColumnCount(10)", source)
        self.assertIn("self.results_tree.setSortingEnabled(False)", source)
        self.assertIn("setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)", source)
        self.assertIn("setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerPixel)", source)
        self.assertIn("QHeaderView.ResizeMode.Interactive", source)
        self.assertIn("resizeSection(1, 260)", source)
        self.assertNotIn("setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)", source)
        self.assertIn("sectionClicked.connect(self._handle_results_header_clicked)", source)
        self.assertIn("def _sort_result_rows", source)
        self.assertIn("def _result_size_bytes", source)
        self.assertIn("def _use_result_source_order", source)
        self.assertIn("self._use_result_source_order()", source)
        self.assertIn("self._result_sort_column", source)
        self.assertIn("Qt.SortOrder.DescendingOrder if column == 6", source)
        self.assertIn("item = QTreeWidgetItem(", source)
        self.assertIn("def _mirror_size_bytes", source)
        self.assertNotIn("class _ModelLibraryResultItem", source)
        self.assertNotIn("setSortingEnabled(True)", source)
        self.assertIn("Hide downloaded", source)
        self.assertIn("model_library/hide_downloaded", source)
        self.assertIn("_handle_hide_downloaded_toggled", source)
        self.assertIn("_filtered_result_rows", source)
        self.assertIn("_mirror_payload_downloaded", source)
        self.assertIn("Build Search Index", source)
        self.assertIn("Build index from current search/filter only", source)
        self.assertIn("model_library/index_current_search", source)
        self.assertIn("index_query=index_query", source)
        self.assertIn("clear_existing=index_current_search", source)
        self.assertIn("Scoped to", source)
        self.assertIn("Mirror Catalogue", source)
        self.assertIn("Local Library", source)
        self.assertIn('QGroupBox("Mirror Index Source")', source)
        self.assertIn("self.mirror_group.setVisible(self._active_results_view == \"mirror\")", source)
        self.assertIn("self.results_search_label = QLabel(\"Mirror search\")", source)
        self.assertIn("self.results_filter_field_combo = QComboBox()", source)
        self.assertIn("self.results_filter_field_combo.addItem(\"Creator\", \"creator\")", source)
        self.assertIn("self.results_filter_field_combo.addItem(\"Path / URL\", \"path\")", source)
        self.assertIn("self.apply_results_query_button = QPushButton(\"Search\")", source)
        self.assertIn("self.clear_results_query_button = QPushButton(\"Clear\")", source)
        self.assertIn("def _apply_active_results_query", source)
        self.assertIn("def _clear_active_results_query", source)
        self.assertIn("def _local_payload_matches_filter", source)
        self.assertIn("model_library/local_search_query", source)
        self.assertIn("model_library/local_search_field", source)
        self.assertIn("local_texture_filter_combo", source)
        self.assertIn('addItem("Has textures", "has")', source)
        self.assertIn('addItem("No textures found", "missing")', source)
        self.assertIn("model_library/local_texture_filter", source)
        self.assertIn("MODEL_LIBRARY_FILTER_COLUMNS", source)
        self.assertIn("results_column_filter_edits", source)
        self.assertIn("_save_column_filters_for_active_view", source)
        self.assertIn("_load_column_filters_for_active_view", source)
        self.assertIn("model_library/local_column_filters_json", source)
        self.assertIn("model_library/mirror_column_filters_json", source)
        self.assertIn("_filter_result_rows_by_columns", source)
        self.assertIn("_payload_matches_column_filters", source)
        self.assertIn("Show Local Models", source)
        self.assertIn("Search Mirror", source)
        self.assertIn("Popular", source)
        self.assertIn("Refresh", source)
        self.assertIn("QButtonGroup", source)
        self.assertIn("QScrollArea", source)
        self.assertIn("_set_active_results_view", source)
        self.assertIn("QTimer.singleShot(0, self.search_mirror)", source)
        self.assertIn("self.catalogue_db_path().is_file()", source)
        self.assertIn("refresh_active_results_view", source)
        self.assertIn("download_mirror_model_candidate", source)
        self.assertIn("Download Checked", source)
        self.assertIn("Downloading...", source)
        self.assertIn("Downloaded {index:,} / {total:,}", source)
        self.assertIn("Downloaded {len(successes):,} file(s)", source)
        self.assertIn("Select at least one preferred file type", source)
        self.assertIn("Download + Import", source)
        self.assertIn("More Actions", source)
        self.assertIn("Delete Local", source)
        self.assertIn("Delete No-Texture Downloads", source)
        self.assertIn("delete_no_texture_downloads", source)
        self.assertIn("_visible_no_texture_download_payloads", source)
        self.assertIn("_no_texture_download_delete_target_for_payload", source)
        self.assertIn("_downloaded_model_folder_target_for_payload", source)
        self.assertIn("_confirm_delete_no_texture_download_targets", source)
        self.assertIn("return self._downloaded_model_folder_target_for_payload(payload)", source)
        self.assertIn("Standalone local model files are never included", source)
        self.assertIn("Delete Local Copy", source)
        self.assertIn("_local_delete_payloads", source)
        self.assertIn("_local_delete_target_for_payload", source)
        self.assertIn("_confirm_delete_local_targets", source)
        self.assertIn("QMessageBox", source)
        self.assertIn("shutil.rmtree", source)
        self.assertIn('QGroupBox("Actions")', source)
        self.assertIn('QGroupBox("Selection")', source)
        self.assertIn('QGroupBox("Model Preview")', source)
        self.assertIn('QPushButton("Preview")', source)
        self.assertIn("D3D11 Preview", source)
        self.assertIn("Preview In Archive Browser", source)
        self.assertNotIn("Import Local Model", source)
        self.assertIn("Generate Icon", source)
        self.assertIn("Generate Icon From Preview", source)
        self.assertIn("item_icon_source_generated", source)
        self.assertNotIn("grabFramebuffer", source)
        self.assertIn("generated_icons", source)
        self.assertIn("_model_preview_icon_image", source)
        self.assertIn("NativePreviewPanel", source)
        self.assertNotIn("WebGlPbrPreviewHostFrame", source)
        self.assertNotIn("WEBGL_PBR_RENDERER_BACKEND", source)
        self.assertNotIn("webgl_pbr", source)
        self.assertIn("def _inline_preview_renderer_backend", source)
        self.assertIn('return "native_d3d11"', source)
        self.assertNotIn("inline_green_up", source)
        self.assertIn("self.inline_preview_stack", source)
        self.assertIn('inline_render_settings.visible_texture_mode = "sidecar_visible_first"', source)
        self.assertIn('inline_render_settings.render_diagnostic_mode = "base_direct"', source)
        self.assertIn("inline_render_settings.disable_all_support_maps = True", source)
        self.assertIn("self.inline_preview_widget.set_render_settings(inline_render_settings)", source)
        self.assertIn("self.inline_preview_widget.set_use_textures(True)", source)
        self.assertIn("self.inline_preview_widget.set_high_quality_textures(True)", source)
        self.assertIn('QCheckBox("Flip V")', source)
        self.assertIn('QPushButton("Reset")', source)
        self.assertIn("self.inline_preview_flip_v_checkbox.toggled.connect(self._handle_inline_preview_flip_v_toggled)", source)
        self.assertIn("def _handle_inline_preview_flip_v_toggled", source)
        self.assertIn("settings.flip_texture_v = bool(checked)", source)
        self.assertIn("def _reload_inline_preview_for_orientation", source)
        self.assertIn("reset_orientation=False", source)
        self.assertIn('== "native_d3d11"', source)
        self.assertIn("self._inline_preview_loaded_texture_count", source)
        self.assertIn("preview_render_settings = self.inline_preview_widget.render_settings()", source)
        self.assertIn("render_settings=preview_render_settings", source)
        self.assertIn("enable_material_combiner=False", source)
        self.assertIn("resolve_preview_batch_material_channels", source)
        self.assertIn("def _inline_preview_material_channel_summary", source)
        self.assertIn('"material_channel_summary": material_channel_summary', source)
        self.assertIn("channels: {material_channel_summary}", source)
        self.assertIn("import_scene_mesh_with_report", source)
        self.assertIn("parsed_mesh_to_preview_model", source)
        self.assertIn("_attach_inline_preview_textures", source)
        self.assertIn("_texture_status_for_payload", source)
        self.assertIn("_count_zip_texture_members", source)
        self.assertIn("Download to check", source)
        self.assertIn("Embedded/Unknown", source)
        self.assertIn("None found", source)
        self.assertIn("All {hidden:,} mirror result(s) are hidden", source)
        self.assertIn("SCENE_TEXTURE_SOURCE_EXTENSIONS", source)
        self.assertIn("Show File URLs", source)
        self.assertIn("Open File URL", source)
        self.assertIn("Select All", source)
        self.assertIn("Select None", source)
        self.assertIn("QMenu", source)
        self.assertIn("customContextMenuRequested", source)
        self.assertIn("Qt.CheckState.Checked", source)
        self.assertIn("_checked_payloads", source)
        self.assertIn("_batch_action_payloads", source)
        self.assertIn("Local", source)
        self.assertIn("_ensure_download_root_registered", source)
        self.assertIn("resolve_importable_model_path", source)
        self.assertIn("zip_contains_importable_model", source)
        self.assertIn("_normalize_local_model_rows", source)
        self.assertIn("_download_group_local_row", source)
        self.assertIn('"source": "Downloaded"', source)
        self.assertIn("require_importable = import_after or preview_after", source)
        self.assertIn("mirror_url_ready", source)
        self.assertIn("Preview", source)
        self.assertIn("status_label.setVisible(False)", source)
        self.assertNotIn("Open Catalogue", source)
        self.assertNotIn("preferred_format_combo", source)

    def test_model_library_auto_preview_resolves_zip_off_ui_thread(self) -> None:
        source = Path("cdmw/ui/model_library_tab.py").read_text(encoding="utf-8")

        preview_start = source.index("    def preview_selected_model_here")
        preview_body = source[preview_start: source.index("    def _inline_preview_renderer_backend", preview_start)]
        self.assertIn("_inline_preview_source_path_for_payload(payload)", preview_body)
        self.assertNotIn("_resolve_payload_import_path", preview_body)
        self.assertNotIn("resolve_importable_model_path", preview_body)

        load_start = source.index("    def _load_inline_model_preview")
        task_start = source.index("        def task(", load_start)
        task_body = source[task_start: source.index("        def complete(", task_start)]
        self.assertIn("resolved_import_path = resolve_importable_model_path(", task_body)
        self.assertIn("import_scene_mesh_with_report(resolved_import_path)", task_body)

        complete_start = source.index("        def complete(", load_start)
        complete_body = source[complete_start: source.index("        def handle_error(", complete_start)]
        self.assertIn("payload[\"import_path\"] = str(resolved_import_path)", complete_body)
        self.assertIn("self._refresh_result_row_status(payload)", complete_body)
        self.assertNotIn("self._refresh_result_row_statuses()", complete_body)


if __name__ == "__main__":
    unittest.main()
