from __future__ import annotations

from collections.abc import Sequence
from types import SimpleNamespace

from cdmw.ui.archive_browser.static_replacement_source_parts_state import (
    part_inspector_loading_initial_state,
    selected_source_indices_state,
    selected_source_part_name_text,
    selected_source_part_target_text,
    source_part_added_export_blocker_message,
    source_part_added_export_blocker_title,
    source_part_added_import_message_lines,
    source_part_add_mesh_part_failed_title,
    source_part_added_mesh_part_status,
    source_part_adjustment_apply_state,
    source_part_adjustment_values_changed,
    source_part_append_display_override,
    source_part_append_file_route_state,
    source_part_append_index_state,
    source_part_append_imported_state,
    source_part_append_mesh_file_dialog_text,
    source_part_append_material_label,
    source_part_append_ordinal_suffix,
    source_part_append_presentations,
    source_part_append_role_hint_text,
    source_part_append_rollback_snapshot,
    source_part_append_texture_control_state,
    source_part_appended_work_area_fit_state,
    source_part_assignment_apply_state,
    source_part_assignment_button_state,
    source_part_assignment_dialog_text,
    source_part_assignment_highlight_state,
    source_part_assignment_import_state,
    source_part_assignment_primary_target,
    source_part_assignment_route_state,
    source_part_assignment_row_specs,
    source_part_assignment_summary_state,
    source_part_assignment_target_for_source,
    source_part_assignment_target_index,
    source_part_assignment_tree_headers,
    source_part_cancel_import_status,
    source_part_center_on_target_state,
    source_part_check_toggle_state,
    source_part_control_load_state,
    source_part_control_state,
    source_part_context_menu_text,
    source_part_copied_texture_action_state,
    source_part_copied_texture_controls_state,
    source_part_copied_texture_status_text,
    source_part_delete_index_map_state,
    source_part_delete_selection_state,
    source_part_delete_status_text,
    source_part_deleted_pending_reason,
    source_part_deleted_status,
    source_part_duplicate_available,
    source_part_duplicate_copy_suffix,
    source_part_duplicate_display_override,
    source_part_duplicate_output_route,
    source_part_duplicate_presentation_state,
    source_part_duplicate_role_override,
    source_part_duplicate_route_state,
    source_part_duplicate_status,
    source_part_duplicate_undo_label,
    source_part_edit_undo_label,
    source_part_fit_size_state,
    source_part_format_mesh_density_counts,
    source_part_glow_color_action_state,
    source_part_glow_color_controls_state,
    source_part_glow_color_button_text,
    source_part_glow_emissive_update_states,
    source_part_glow_emissive_update_states_for_sources,
    source_part_glow_reason_text,
    source_part_glow_selection_state,
    source_part_glow_rgb,
    source_part_group_routing_overflow_message,
    source_part_group_routing_text,
    source_part_group_initial_target_counts,
    source_part_group_items,
    source_part_material_groups,
    source_part_group_source_texts,
    source_part_group_target_score,
    source_part_high_density_import_action,
    source_part_high_density_reduction_limits,
    source_part_high_density_prompt_state,
    source_part_mapping_indices_for_target,
    source_part_nudge_delta,
    source_part_normalized_target_indices,
    source_part_output_action_state,
    source_part_pair_action_available,
    source_part_pair_action_state,
    source_part_high_density_import_message,
    source_part_inspector_control_text,
    source_part_include_exclude_pending_reason,
    source_part_map_to_target_state,
    source_part_multipart_import_action,
    source_part_multipart_import_message,
    source_part_multipart_import_state,
    source_part_multipart_prompt_state,
    source_part_properties_control_text,
    source_part_properties_inspector_state,
    source_part_properties_label_html,
    source_part_material_properties_text,
    source_part_properties_output_text,
    source_part_source_properties_dds_text,
    source_part_source_properties_warning,
    source_part_target_properties_warning,
    source_part_reduction_result_message,
    source_part_role_action_state,
    source_part_role_export_flush_states,
    source_part_role_override_state,
    source_part_routing_preview_action,
    source_part_scene_import_appendable_part_count,
    source_part_scene_import_is_high_density,
    source_part_scene_import_prompt_text,
    source_part_assign_groups_to_targets,
    source_part_assign_material_groups_to_targets,
    source_part_selected_target_index,
    source_part_source_combo_selection_state,
    source_part_target_button_state,
    source_part_target_combo_selection_state,
    source_part_selection_context_label_text,
    source_part_selection_context_state,
    source_part_selection_context_tooltip,
    source_part_selection_added_texture_context_text,
    source_part_selection_added_texture_text,
    source_part_selection_texture_fallback,
    source_part_selection_texture_row_context_text,
    source_part_selection_texture_row_text,
    source_part_should_be_preview_only_after_unmap,
    source_part_target_choice,
    source_part_target_sources_initial_state,
    source_part_transform_control_text,
    source_part_unmap_target_states,
    source_part_unmapped_indices_for_target,
    source_part_unsupported_mesh_part_message,
    source_part_valid_indices,
    source_parts_action_control_text,
    source_parts_apply_initial_state,
    source_parts_apply_pending_presentation,
    source_parts_clear_apply_pending,
    source_parts_clear_apply_pending_presentation,
    source_parts_mark_apply_pending,
    source_parts_mark_preview_rebuild_pending,
    source_parts_preview_rebuild_pending_presentation,
    source_parts_preview_rebuild_pending,
    source_parts_selection_pending_presentation,
)


def _properties_state(selection: dict[str, object], **overrides: object):
    kwargs = {
        "output_counts": (2, 3, 1, 4, "prune removed"),
        "target_source_indices": lambda target_index: (0, 2) if target_index == 5 else (),
        "target_outliner_state": lambda target_index, source_indices: (
            ("Removed", "#fb923c") if not tuple(source_indices) else ("Mapped", "#3fb950")
        ),
        "format_source_indices": lambda indices: ", ".join(f"src {index}" for index in indices) or "-",
        "format_target_indices": lambda indices: ", ".join(f"target {index}" for index in indices) or "-",
        "target_dds_label": lambda target_index: f"TargetMat{target_index}" if target_index >= 0 else "",
        "target_texture_status_text": lambda target_name: f"Tex {target_name}",
        "source_assigned_target_indices": lambda source_index: (5,) if source_index == 2 else (),
        "source_outliner_state": lambda source_index, mapped_targets: (
            ("Assigned", "#3fb950") if tuple(mapped_targets) else ("Unassigned", "#d29922")
        ),
        "source_material_name": lambda source_index: f"Material{source_index}",
    }
    kwargs.update(overrides)
    return source_part_properties_inspector_state(selection, **kwargs)


def test_source_part_append_rollback_snapshot_normalizes_mutable_state() -> None:
    adjustments = {1: SimpleNamespace(value=["keep"])}
    redo_adjustments = [SimpleNamespace(value=["redo"])]

    snapshot = source_part_append_rollback_snapshot(
        replacement_mesh="mesh",
        replacement_base_mesh="base",
        appended_source_indices=(2, "bad", 2),
        independent_output_source_indices=(3,),
        preview_only_source_indices=(4,),
        source_role_overrides={2: "role"},
        source_display_overrides={2: "display"},
        source_part_adjustments=adjustments,
        dialog_added_supplemental_files=["sidecar"],
        texture_files_for_mapping=["tex"],
        source_material_texture_override_assignments={"slot": "path"},
        mesh_edit_redo_stack=["redo"],
        mesh_edit_redo_adjustment_stack=redo_adjustments,
        source_geometry_revision="12",
        selected_source_index="2",
        selected_source_indices=(2, 3),
        selected_target_index="4",
        selected_original_index="5",
        selected_source_highlights=(2,),
        selected_target_source_highlights=(4,),
        transform_source_indices=(2, 3),
        selected_original_highlights=(5,),
        selected_target_original_highlights=(6,),
    )

    adjustments[1].value.append("changed")
    redo_adjustments[0].value.append("changed")

    assert snapshot.appended_source_indices == (2,)
    assert snapshot.source_geometry_revision == 12
    assert snapshot.selected_source_index == 2
    assert snapshot.selected_source_indices == (2, 3)
    assert snapshot.source_part_adjustments[1].value == ["keep"]
    assert snapshot.mesh_edit_redo_adjustment_stack[0].value == ["redo"]
