from __future__ import annotations

# Generated static compatibility data; implementation remains in focused owners.
ARCHIVE_MODDING_EXPORTS_2: dict[str, tuple[str, str]] = {
    'build_archive_audio_patch_payload': ('cdmw.core.archive_audio', 'build_archive_audio_patch_payload'),
    'build_archive_texture_payload_from_dds': ('cdmw.core.archive_patching', 'build_archive_texture_payload_from_dds'),
    'build_archive_texture_payload_from_png': ('cdmw.core.archive_patching', 'build_archive_texture_payload_from_png'),
    'build_hkx_converter_corpus_csv': ('cdmw.core.archive_hkx', 'build_hkx_converter_corpus_csv'),
    'build_hkx_converter_corpus_json': ('cdmw.core.archive_hkx', 'build_hkx_converter_corpus_json'),
    'build_hkx_converter_corpus_report': ('cdmw.core.archive_hkx', 'build_hkx_converter_corpus_report'),
    'build_hkx_corpus_evidence_from_report': ('cdmw.core.archive_hkx', 'build_hkx_corpus_evidence_from_report'),
    'build_hkx_descriptor_hint_from_xml_text': ('cdmw.core.archive_hkx', 'build_hkx_descriptor_hint_from_xml_text'),
    'build_hkx_editable_geometry_document': ('cdmw.core.archive_hkx', 'build_hkx_editable_geometry_document'),
    'build_hkx_editable_geometry_json': ('cdmw.core.archive_hkx', 'build_hkx_editable_geometry_json'),
    'build_hkx_editable_geometry_xml': ('cdmw.core.archive_hkx', 'build_hkx_editable_geometry_xml'),
    'build_hkx_havok_xml_view_xml': ('cdmw.core.archive_hkx', 'build_hkx_havok_xml_view_xml'),
    'build_hkx_model_preview_from_document': ('cdmw.core.archive_hkx', 'build_hkx_model_preview_from_document'),
    'build_hkx_physics_overlay_from_document': ('cdmw.core.archive_hkx', 'build_hkx_physics_overlay_from_document'),
    'build_hkx_preview': ('cdmw.core.archive_hkx', 'build_hkx_preview'),
    'build_mesh': ('cdmw.modding.mesh_importer', 'build_mesh'),
    'build_mesh_import_preview': ('cdmw.core.archive_mesh_import_preview', 'build_mesh_import_preview'),
    'build_mesh_preview_from_bytes': ('cdmw.core.archive_mesh_import_preview', 'build_mesh_preview_from_bytes'),
    'build_pab_preview': ('cdmw.core.archive_hkx', 'build_pab_preview'),
    'build_skin_binding_map': ('cdmw.core.skeleton_resolver', 'build_skin_binding_map'),
    'build_static_mesh_replacement': ('cdmw.modding.static_mesh_replacer', 'build_static_mesh_replacement'),
    'build_texture_replacement_payloads': ('cdmw.modding.material_replacer', 'build_texture_replacement_payloads'),
    'discover_scene_texture_files': ('cdmw.modding.scene_importer', 'discover_scene_texture_files'),
    'effective_static_replacement_source_mesh': ('cdmw.modding.static_mesh_replacer', 'effective_static_replacement_source_mesh'),
    'export_archive_audio_as_wav': ('cdmw.core.archive_audio', 'export_archive_audio_as_wav'),
    'export_archive_mesh': ('cdmw.core.archive_mesh_export', 'export_archive_mesh'),
    'export_archive_mesh_payloads_to_mod_ready_loose': ('cdmw.core.archive_loose_export', 'export_archive_mesh_payloads_to_mod_ready_loose'),
    'export_archive_payloads_to_mod_ready_loose': ('cdmw.core.archive_loose_export', 'export_archive_payloads_to_mod_ready_loose'),
    'export_fbx': ('cdmw.modding.mesh_exporter', 'export_fbx'),
    'export_fbx_with_skeleton': ('cdmw.modding.mesh_exporter', 'export_fbx_with_skeleton'),
    'export_obj': ('cdmw.modding.mesh_exporter', 'export_obj'),
    'get_archive_texture_patch_blocker': ('cdmw.core.archive_patching', 'get_archive_texture_patch_blocker'),
    'hidden_subprocess_kwargs': ('cdmw.core.common', 'hidden_subprocess_kwargs'),
    'import_scene_mesh': ('cdmw.modding.scene_importer', 'import_scene_mesh'),
    'import_scene_mesh_with_report': ('cdmw.modding.scene_importer', 'import_scene_mesh_with_report'),
    'iter_pab_candidate_basenames': ('cdmw.modding.skeleton_parser', 'iter_pab_candidate_basenames'),
    'list_archive_patch_backups': ('cdmw.core.archive_patching', 'list_archive_patch_backups'),
    'load_hkx_corpus_evidence_json': ('cdmw.core.archive_hkx', 'load_hkx_corpus_evidence_json'),
    'merge_hkx_physics_overlays': ('cdmw.core.archive_hkx', 'merge_hkx_physics_overlays'),
    'mesh_import_runtime_sibling_mesh_candidates': ('cdmw.core.archive_mesh_import_preview', 'mesh_import_runtime_sibling_mesh_candidates'),
    'parse_hkx_tagfile_summary': ('cdmw.core.archive_hkx', 'parse_hkx_tagfile_summary'),
    'parse_mesh': ('cdmw.modding.mesh_parser', 'parse_mesh'),
    'parse_pab': ('cdmw.modding.skeleton_parser', 'parse_pab'),
    'parsed_mesh_to_preview_model': ('cdmw.core.archive_mesh_import_preview', 'parsed_mesh_to_preview_model'),
    'patch_archive_entries': ('cdmw.core.archive_patching', 'patch_archive_entries'),
    'raise_if_cancelled': ('cdmw.core.common', 'raise_if_cancelled'),
    'read_archive_entry_baseline_data': ('cdmw.core.mesh_baseline', 'read_archive_entry_baseline_data'),
    'request_app_temp_cache_prune': ('cdmw.core.temp_cache', 'request_app_temp_cache_prune'),
    'resolve_skeleton_for_model': ('cdmw.core.skeleton_resolver', 'resolve_skeleton_for_model'),
    'restore_archive_patch_backup': ('cdmw.core.archive_patching', 'restore_archive_patch_backup'),
    'run_process_with_cancellation': ('cdmw.core.common', 'run_process_with_cancellation'),
    'scene_import_normalizes_texture_v': ('cdmw.core.model_preview_orientation', 'scene_import_normalizes_texture_v'),
    'suggest_static_submesh_mappings': ('cdmw.modding.static_mesh_replacer', 'suggest_static_submesh_mappings'),
    'transfer_pam_edit_to_pamlod_mesh': ('cdmw.modding.mesh_importer', 'transfer_pam_edit_to_pamlod_mesh'),
    'write_roundtrip_manifest': ('cdmw.modding.mesh_exporter', 'write_roundtrip_manifest'),
}

__all__ = ['ARCHIVE_MODDING_EXPORTS_2']
