from __future__ import annotations

import json
import math
import struct
import time
from bisect import bisect_right
from copy import deepcopy
from functools import lru_cache
from pathlib import Path
from typing import Callable, Mapping, Optional, Sequence, TypeVar

from cdmw.core.common import raise_if_cancelled
from cdmw.core.archive_attachment_patches import (
    build_prefab_attachment_profile_patch,
    inspect_prefab_attachment_profile_fields,
)
from cdmw.core.crimson_formats import decode_prefab, rebuild_prefab_no_edit
from cdmw.core.prefab_json import (
    PrefabEditJsonError,
    apply_prefab_edit_document,
    build_prefab_edit_document,
    rebuild_prefab_no_edit_from_edit_document,
)
from cdmw.models import ArchiveEntry
from cdmw.core.prefab_corpus_contracts import (
    EDIT_PROBES_DISABLED_REASON,
    NO_SAFE_PLACEMENT_LENGTH_PROBE_REASON,
    NO_SAFE_RESOURCE_LENGTH_PROBE_REASON,
    OVERLAPPING_OFFSET_CANDIDATES_REASON,
    PREFAB_JSON_IMPORT_CORPUS_FORMAT,
    T,
)


def _build_audit_success_row_part_0(state) -> dict[str, object]:
    result = {}
    result.update({'path': state['virtual_path']})
    result.update({'status': 'passed' if state['ok'] else 'failed'})
    result.update({'byte_length': len(state['payload'])})
    result.update({'prefab_header': {'magic': state['decoded'].header.magic, 'version': state['decoded'].header.version, 'prefix_byte_length': state['decoded'].header.prefix_byte_length, 'first_string_offset': state['decoded'].header.first_string_offset}})
    result.update({'prefab_layout': {'span_count': len(state['decoded'].layout.spans), 'string_span_count': state['decoded'].layout.string_span_count, 'preserved_span_count': state['decoded'].layout.preserved_span_count, 'parsed_string_byte_count': state['decoded'].layout.parsed_string_byte_count, 'preserved_byte_count': state['decoded'].layout.preserved_byte_count, 'accounted_byte_count': state['decoded'].layout.accounted_byte_count, 'fully_accounted': state['decoded'].layout.fully_accounted}})
    result.update({'declared_field_count': len(state['decoded'].declared_fields)})
    result.update({'member_declaration_count': len(state['decoded'].member_declarations)})
    result.update({'member_descriptor_bytes': state['member_descriptor_bytes']})
    result.update({'descriptor_tail_member_kind_counts': state['descriptor_tail_kind_metrics']['member_counts']})
    result.update({'descriptor_tail_byte_kind_counts': state['descriptor_tail_kind_metrics']['byte_counts']})
    result.update({'descriptor_tail_member_detail_counts': state['descriptor_tail_member_detail_counts']})
    result.update({'transform_member_count': state['transform_member_count']})
    result.update({'decoded_transform_payload_value_rows': state['decoded_transform_payload_value_rows']})
    result.update({'transform_members_without_payload_values': state['transform_members_without_payload_values']})
    result.update({'transform_members_with_descriptor_tail_bytes': state['transform_descriptor_tail_metrics']['member_count']})
    result.update({'transform_descriptor_tail_bytes': state['transform_descriptor_tail_metrics']['tail_byte_count']})
    result.update({'transform_name_only_member_count': state['transform_name_only_member_count']})
    result.update({'transform_descriptor_signature_counts': state['transform_descriptor_signature_counts']})
    result.update({'transform_descriptor_signature_offset_candidate_counts': state['transform_descriptor_signature_offset_candidate_counts']})
    result.update({'transform_nonzero_word3_offset_candidate_status_counts': state['transform_nonzero_word3_offset_candidate_status_counts']})
    result.update({'transform_descriptor_signature_offset_candidate_target_counts': state['transform_descriptor_signature_offset_candidate_target_counts']})
    result.update({'transform_nonzero_word3_offset_candidate_target_counts': state['transform_nonzero_word3_offset_candidate_target_counts']})
    result.update({'transform_descriptor_word0_value_counts': state['transform_descriptor_word0_value_counts']})
    result.update({'transform_descriptor_word1_value_counts': state['transform_descriptor_word1_value_counts']})
    result.update({'transform_descriptor_word2_value_counts': state['transform_descriptor_word2_value_counts']})
    result.update({'transform_descriptor_word3_value_counts': state['transform_descriptor_word3_value_counts']})
    result.update({'transform_theoretical_payload_shape_counts': state['transform_theoretical_payload_shape_counts']})
    result.update({'transform_theoretical_payload_member_rows': state['transform_theoretical_payload_span_fit_metrics']['member_rows']})
    result.update({'transform_theoretical_payload_byte_count': state['transform_theoretical_payload_span_fit_metrics']['byte_count']})
    result.update({'transform_theoretical_payload_exact_preserved_span_rows': state['transform_theoretical_payload_span_fit_metrics']['exact_preserved_span_rows']})
    result.update({'transform_theoretical_payload_later_preserved_span_fit_rows': state['transform_theoretical_payload_span_fit_metrics']['later_preserved_span_fit_rows']})
    result.update({'transform_theoretical_payload_no_preserved_span_fit_rows': state['transform_theoretical_payload_span_fit_metrics']['no_preserved_span_fit_rows']})
    result.update({'transform_theoretical_payload_immediate_window_string_span_overlap_rows': state['transform_theoretical_payload_span_fit_metrics']['immediate_window_string_span_overlap_rows']})
    result.update({'transform_theoretical_payload_immediate_window_string_span_overlap_count': state['transform_theoretical_payload_span_fit_metrics']['immediate_window_string_span_overlap_count']})
    result.update({'transform_theoretical_payload_immediate_window_string_span_role_counts': state['transform_theoretical_payload_span_fit_metrics']['immediate_window_string_span_role_counts']})
    result.update({'transform_theoretical_payload_immediate_window_string_span_relation_counts': state['transform_theoretical_payload_span_fit_metrics']['immediate_window_string_span_relation_counts']})
    result.update({'transform_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows': state['transform_theoretical_payload_span_fit_metrics']['later_fit_with_intervening_string_or_declaration_rows']})
    result.update({'transform_theoretical_payload_later_fit_gap_string_span_relation_counts': state['transform_theoretical_payload_span_fit_metrics']['later_fit_gap_string_span_relation_counts']})
    result.update({'transform_theoretical_payload_later_fit_gap_member_descriptor_relation_counts': state['transform_theoretical_payload_span_fit_metrics']['later_fit_gap_member_descriptor_relation_counts']})
    result.update({'array_member_count': state['array_member_count']})
    result.update({'array_member_stride_hint_count': state['array_stride_hint_count']})
    result.update({'array_member_count_hint_count': state['array_count_hint_count']})
    result.update({'array_descriptor_signature_counts': state['array_descriptor_signature_counts']})
    result.update({'array_descriptor_signature_offset_candidate_counts': state['array_descriptor_signature_offset_candidate_counts']})
    result.update({'array_descriptor_signature_offset_candidate_target_counts': state['array_descriptor_signature_offset_candidate_target_counts']})
    result.update({'array_nonzero_word3_offset_candidate_target_counts': state['array_nonzero_word3_offset_candidate_target_counts']})
    result.update({'array_descriptor_word0_value_counts': state['array_descriptor_word0_value_counts']})
    result.update({'array_descriptor_word1_value_counts': state['array_descriptor_word1_value_counts']})
    result.update({'array_descriptor_word2_value_counts': state['array_descriptor_word2_value_counts']})
    result.update({'array_descriptor_word3_value_counts': state['array_descriptor_word3_value_counts']})
    result.update({'array_stride_hint_type_counts': state['array_stride_hint_type_counts']})
    result.update({'array_count_hint_type_counts': state['array_count_hint_type_counts']})
    result.update({'array_count_hint_member_counts': state['array_count_hint_member_counts']})
    result.update({'array_word3_relation_counts': state['array_word3_relation_counts']})
    result.update({'array_theoretical_payload_shape_counts': state['array_theoretical_payload_shape_counts']})
    return result


def _build_audit_success_row_part_1(state) -> dict[str, object]:
    result = {}
    result.update({'array_theoretical_payload_member_rows': state['array_theoretical_payload_span_fit_metrics']['member_rows']})
    result.update({'array_theoretical_payload_byte_count': state['array_theoretical_payload_span_fit_metrics']['byte_count']})
    result.update({'array_theoretical_payload_non_tiny_member_rows': state['array_theoretical_payload_span_fit_metrics']['non_tiny_member_rows']})
    result.update({'array_theoretical_payload_non_tiny_byte_count': state['array_theoretical_payload_span_fit_metrics']['non_tiny_byte_count']})
    result.update({'array_theoretical_payload_exact_preserved_span_rows': state['array_theoretical_payload_span_fit_metrics']['exact_preserved_span_rows']})
    result.update({'array_theoretical_payload_later_preserved_span_fit_rows': state['array_theoretical_payload_span_fit_metrics']['later_preserved_span_fit_rows']})
    result.update({'array_theoretical_payload_no_preserved_span_fit_rows': state['array_theoretical_payload_span_fit_metrics']['no_preserved_span_fit_rows']})
    result.update({'array_theoretical_payload_immediate_window_string_span_overlap_rows': state['array_theoretical_payload_span_fit_metrics']['immediate_window_string_span_overlap_rows']})
    result.update({'array_theoretical_payload_immediate_window_string_span_overlap_count': state['array_theoretical_payload_span_fit_metrics']['immediate_window_string_span_overlap_count']})
    result.update({'array_theoretical_payload_immediate_window_string_span_role_counts': state['array_theoretical_payload_span_fit_metrics']['immediate_window_string_span_role_counts']})
    result.update({'array_theoretical_payload_immediate_window_string_span_relation_counts': state['array_theoretical_payload_span_fit_metrics']['immediate_window_string_span_relation_counts']})
    result.update({'array_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows': state['array_theoretical_payload_span_fit_metrics']['later_fit_with_intervening_string_or_declaration_rows']})
    result.update({'array_theoretical_payload_later_fit_gap_string_span_relation_counts': state['array_theoretical_payload_span_fit_metrics']['later_fit_gap_string_span_relation_counts']})
    result.update({'array_theoretical_payload_later_fit_gap_member_descriptor_relation_counts': state['array_theoretical_payload_span_fit_metrics']['later_fit_gap_member_descriptor_relation_counts']})
    result.update({'array_word2_delta_member_counts': state['array_word2_delta_member_counts']})
    result.update({'array_word2_delta_word3_member_counts': state['array_word2_delta_word3_member_counts']})
    result.update({'array_word2_delta_word3_member_offset_candidate_counts': state['array_word2_delta_word3_member_offset_candidate_counts']})
    result.update({'array_nonzero_word3_offset_candidate_status_counts': state['array_nonzero_word3_offset_candidate_status_counts']})
    result.update({'array_classification_source_counts': state['array_classification_source_counts']})
    result.update({'array_word3_category_counts': state['array_word3_category_counts']})
    result.update({'decoded_array_payload_element_rows': state['decoded_array_payload_element_rows']})
    result.update({'array_members_without_payload_elements': state['array_members_without_payload_elements']})
    result.update({'array_members_with_descriptor_tail_bytes': state['array_descriptor_tail_metrics']['member_count']})
    result.update({'array_descriptor_tail_bytes': state['array_descriptor_tail_metrics']['tail_byte_count']})
    result.update({'reference_member_count': state['reference_member_count']})
    result.update({'reference_members_without_descriptor_semantics': state['reference_members_without_descriptor_semantics']})
    result.update({'reference_members_with_descriptor_tail_bytes': state['reference_descriptor_tail_metrics']['member_count']})
    result.update({'reference_descriptor_tail_bytes': state['reference_descriptor_tail_metrics']['tail_byte_count']})
    result.update({'reference_descriptor_signature_counts': state['reference_descriptor_signature_counts']})
    result.update({'reference_descriptor_tail_record_shape_counts': state['reference_descriptor_tail_record_shape_counts']})
    result.update({'reference_descriptor_tail_offset_candidate_mod_counts': state['reference_descriptor_tail_offset_candidate_mod_counts']})
    result.update({'reference_descriptor_tail_record_profile_counts': state['reference_descriptor_tail_record_profile_counts']})
    result.update({'reference_descriptor_tail_numeric_profile_counts': state['reference_descriptor_tail_numeric_profile_counts']})
    result.update({'reference_descriptor_tail_column_profile_counts': state['reference_descriptor_tail_column_profile_counts']})
    result.update({'reference_descriptor_signature_offset_candidate_counts': state['reference_descriptor_signature_offset_candidate_counts']})
    result.update({'reference_nonzero_word3_offset_candidate_status_counts': state['reference_nonzero_word3_offset_candidate_status_counts']})
    result.update({'reference_descriptor_signature_offset_candidate_target_counts': state['reference_descriptor_signature_offset_candidate_target_counts']})
    result.update({'reference_nonzero_word3_offset_candidate_target_counts': state['reference_nonzero_word3_offset_candidate_target_counts']})
    result.update({'scalar_or_bool_descriptor_signature_counts': state['scalar_or_bool_descriptor_signature_counts']})
    result.update({'scalar_or_bool_descriptor_signature_offset_candidate_counts': state['scalar_or_bool_descriptor_signature_offset_candidate_counts']})
    result.update({'scalar_or_bool_nonzero_word3_offset_candidate_status_counts': state['scalar_or_bool_nonzero_word3_offset_candidate_status_counts']})
    result.update({'scalar_or_bool_descriptor_signature_offset_candidate_target_counts': state['scalar_or_bool_descriptor_signature_offset_candidate_target_counts']})
    result.update({'scalar_or_bool_nonzero_word3_offset_candidate_target_counts': state['scalar_or_bool_nonzero_word3_offset_candidate_target_counts']})
    result.update({'string_descriptor_signature_counts': state['string_descriptor_signature_counts']})
    result.update({'string_descriptor_signature_offset_candidate_counts': state['string_descriptor_signature_offset_candidate_counts']})
    result.update({'string_nonzero_word3_offset_candidate_status_counts': state['string_nonzero_word3_offset_candidate_status_counts']})
    result.update({'string_descriptor_signature_offset_candidate_target_counts': state['string_descriptor_signature_offset_candidate_target_counts']})
    result.update({'string_nonzero_word3_offset_candidate_target_counts': state['string_nonzero_word3_offset_candidate_target_counts']})
    result.update({'generic_descriptor_signature_counts': state['generic_descriptor_signature_counts']})
    result.update({'generic_descriptor_signature_offset_candidate_counts': state['generic_descriptor_signature_offset_candidate_counts']})
    result.update({'generic_nonzero_word3_offset_candidate_status_counts': state['generic_nonzero_word3_offset_candidate_status_counts']})
    result.update({'generic_descriptor_signature_offset_candidate_target_counts': state['generic_descriptor_signature_offset_candidate_target_counts']})
    result.update({'generic_nonzero_word3_offset_candidate_target_counts': state['generic_nonzero_word3_offset_candidate_target_counts']})
    result.update({'descriptor_kind_nonzero_word3_offset_candidate_status_counts': state['descriptor_kind_nonzero_word3_offset_candidate_status_counts']})
    result.update({'descriptor_kind_nonzero_word3_offset_candidate_target_counts': state['descriptor_kind_nonzero_word3_offset_candidate_target_counts']})
    return result


def _build_audit_success_row_part_2(state) -> dict[str, object]:
    result = {}
    result.update({'descriptor_owner_kind_offset_candidate_counts': state['descriptor_owner_kind_offset_candidate_counts']})
    result.update({'descriptor_owner_kind_offset_candidate_target_counts': state['descriptor_owner_kind_offset_candidate_target_counts']})
    result.update({'offset_candidate_count': state['offset_candidate_count']})
    result.update({'offset_candidate_overlap_count': state['offset_candidate_overlap_count']})
    result.update({'offset_candidate_aligned_count': state['offset_candidate_metrics']['aligned_count']})
    result.update({'offset_candidate_unaligned_count': state['offset_candidate_metrics']['unaligned_count']})
    result.update({'offset_candidate_overlap_group_count': state['offset_candidate_metrics']['overlap_group_count']})
    result.update({'offset_candidate_overlapping_window_count': state['offset_candidate_metrics']['overlapping_window_count']})
    result.update({'offset_candidate_isolated_count': state['offset_candidate_metrics']['isolated_count']})
    result.update({'offset_candidate_aligned_isolated_count': state['offset_candidate_metrics']['aligned_isolated_count']})
    result.update({'offset_candidate_unaligned_isolated_count': state['offset_candidate_metrics']['unaligned_isolated_count']})
    result.update({'offset_candidate_unaligned_or_overlapping_count': state['offset_candidate_metrics']['unaligned_or_overlapping_count']})
    result.update({'offset_candidate_target_string_length_prefix_count': state['offset_candidate_metrics']['target_string_length_prefix_count']})
    result.update({'offset_candidate_target_string_value_count': state['offset_candidate_metrics']['target_string_value_count']})
    result.update({'offset_candidate_target_string_end_count': state['offset_candidate_metrics']['target_string_end_count']})
    result.update({'offset_candidate_in_member_descriptor_count': state['offset_candidate_descriptor_metrics']['in_member_descriptor_count']})
    result.update({'offset_candidate_outside_member_descriptor_count': state['offset_candidate_descriptor_metrics']['outside_member_descriptor_count']})
    result.update({'offset_candidate_in_array_descriptor_count': state['offset_candidate_descriptor_metrics']['in_array_descriptor_count']})
    result.update({'offset_candidate_in_transform_descriptor_count': state['offset_candidate_descriptor_metrics']['in_transform_descriptor_count']})
    result.update({'offset_candidate_in_reference_descriptor_count': state['offset_candidate_descriptor_metrics']['in_reference_descriptor_count']})
    result.update({'offset_candidate_in_scalar_or_bool_descriptor_count': state['offset_candidate_descriptor_metrics']['in_scalar_or_bool_descriptor_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_count': state['offset_candidate_outside_descriptor_metrics']['aligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_count': state['offset_candidate_outside_descriptor_metrics']['unaligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_overlap_group_count': state['offset_candidate_outside_descriptor_metrics']['overlap_group_count']})
    result.update({'offset_candidate_outside_member_descriptor_overlapping_window_count': state['offset_candidate_outside_descriptor_metrics']['overlapping_window_count']})
    result.update({'offset_candidate_outside_member_descriptor_isolated_count': state['offset_candidate_outside_descriptor_metrics']['isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_count': state['offset_candidate_outside_descriptor_metrics']['aligned_isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_isolated_count': state['offset_candidate_outside_descriptor_metrics']['unaligned_isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_or_overlapping_count': state['offset_candidate_outside_descriptor_metrics']['unaligned_or_overlapping_count']})
    result.update({'offset_candidate_outside_member_descriptor_target_string_length_prefix_count': state['offset_candidate_outside_descriptor_metrics']['target_string_length_prefix_count']})
    result.update({'offset_candidate_outside_member_descriptor_target_string_value_count': state['offset_candidate_outside_descriptor_metrics']['target_string_value_count']})
    result.update({'offset_candidate_outside_member_descriptor_target_string_end_count': state['offset_candidate_outside_descriptor_metrics']['target_string_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_candidate_offset_mod4_counts': state['offset_candidate_outside_descriptor_mod4_counts']['candidate_offset_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_target_value_mod4_counts': state['offset_candidate_outside_descriptor_mod4_counts']['target_value_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_string_value_candidate_offset_mod4_counts': state['offset_candidate_outside_descriptor_mod4_counts']['string_value_candidate_offset_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_string_value_target_value_mod4_counts': state['offset_candidate_outside_descriptor_mod4_counts']['string_value_target_value_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_neighbor_byte_class_counts': state['offset_candidate_outside_descriptor_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_target_role_counts': state['offset_candidate_outside_descriptor_target_role_counts']['target_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_string_value_target_role_counts': state['offset_candidate_outside_descriptor_target_role_counts']['string_value_target_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_target_role_kind_counts': state['offset_candidate_outside_descriptor_aligned_isolated_role_kind_counts']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_count': state['offset_candidate_outside_descriptor_aligned_isolated_span_metrics']['in_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_outside_preserved_span_count': state['offset_candidate_outside_descriptor_aligned_isolated_span_metrics']['outside_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_exact_4_count': state['offset_candidate_outside_descriptor_aligned_isolated_span_metrics']['preserved_span_exact_4_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_le_8_count': state['offset_candidate_outside_descriptor_aligned_isolated_span_metrics']['preserved_span_le_8_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_start_count': state['offset_candidate_outside_descriptor_aligned_isolated_span_metrics']['at_preserved_span_start_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_end_count': state['offset_candidate_outside_descriptor_aligned_isolated_span_metrics']['at_preserved_span_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_middle_count': state['offset_candidate_outside_descriptor_aligned_isolated_span_metrics']['in_preserved_span_middle_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_aligned_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['aligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_unaligned_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['unaligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_isolated_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_unaligned_or_overlapping_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['unaligned_or_overlapping_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_length_prefix_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['target_string_length_prefix_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_value_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['target_string_value_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_end_count': state['offset_candidate_outside_descriptor_resource_reference_metrics']['target_string_end_count']})
    return result


def _build_audit_success_row_part_3(state) -> dict[str, object]:
    result = {}
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_aligned_count': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['group_metrics']['aligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_unaligned_count': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['group_metrics']['unaligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_isolated_count': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['group_metrics']['isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_unaligned_or_overlapping_count': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['group_metrics']['unaligned_or_overlapping_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_length_prefix_count': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['group_metrics']['target_string_length_prefix_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_value_count': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['group_metrics']['target_string_value_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_end_count': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['group_metrics']['target_string_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_counts': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['target_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_counts': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['target_role_kind_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_span_position_counts': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['target_role_kind_span_position_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_neighbor_byte_class_counts': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['target_role_kind_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_span_position_neighbor_byte_class_counts': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['target_role_kind_span_position_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_signed_distance_counts': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['target_role_kind_signed_distance_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_span_byte_length_counts': state['offset_candidate_outside_descriptor_preserved_middle_metrics']['span_byte_length_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_candidate_offset_mod4_counts': state['offset_candidate_resource_reference_mod4_counts']['candidate_offset_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_value_mod4_counts': state['offset_candidate_resource_reference_mod4_counts']['target_value_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_neighbor_byte_class_counts': state['offset_candidate_resource_reference_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_counts': state['offset_candidate_resource_reference_alignment_target_kind_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_extension_counts': state['offset_candidate_resource_reference_alignment_target_kind_extension_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_role_counts': state['offset_candidate_resource_reference_alignment_target_kind_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_span_bucket_counts': state['offset_candidate_resource_reference_alignment_target_kind_span_bucket_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_span_position_counts': state['offset_candidate_resource_reference_alignment_target_kind_span_position_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_profile_span_position_counts': state['offset_candidate_resource_reference_target_profile_span_position_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_profile_distance_counts': state['offset_candidate_resource_reference_target_profile_distance_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_profile_neighbor_byte_class_counts': state['offset_candidate_resource_reference_target_profile_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_in_preserved_span_count': state['offset_candidate_resource_reference_span_metrics']['in_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_outside_preserved_span_count': state['offset_candidate_resource_reference_span_metrics']['outside_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_preserved_span_exact_4_count': state['offset_candidate_resource_reference_span_metrics']['preserved_span_exact_4_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_preserved_span_le_8_count': state['offset_candidate_resource_reference_span_metrics']['preserved_span_le_8_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_at_preserved_span_start_count': state['offset_candidate_resource_reference_span_metrics']['at_preserved_span_start_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_at_preserved_span_end_count': state['offset_candidate_resource_reference_span_metrics']['at_preserved_span_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_in_preserved_span_middle_count': state['offset_candidate_resource_reference_span_metrics']['in_preserved_span_middle_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_span_byte_length_counts': state['offset_candidate_resource_reference_span_byte_length_counts']})
    result.update({'offset_candidate_in_preserved_span_count': state['offset_candidate_span_metrics']['in_preserved_span_count']})
    result.update({'offset_candidate_outside_preserved_span_count': state['offset_candidate_span_metrics']['outside_preserved_span_count']})
    result.update({'offset_candidate_preserved_span_exact_4_count': state['offset_candidate_span_metrics']['preserved_span_exact_4_count']})
    result.update({'offset_candidate_preserved_span_le_8_count': state['offset_candidate_span_metrics']['preserved_span_le_8_count']})
    result.update({'offset_candidate_at_preserved_span_start_count': state['offset_candidate_span_metrics']['at_preserved_span_start_count']})
    result.update({'offset_candidate_at_preserved_span_end_count': state['offset_candidate_span_metrics']['at_preserved_span_end_count']})
    result.update({'offset_candidate_in_preserved_span_middle_count': state['offset_candidate_span_metrics']['in_preserved_span_middle_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_exact_4_count': state['offset_candidate_span_metrics']['outside_member_descriptor_preserved_span_exact_4_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_le_8_count': state['offset_candidate_span_metrics']['outside_member_descriptor_preserved_span_le_8_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_count': state['offset_candidate_span_metrics']['outside_member_descriptor_preserved_span_middle_count']})
    result.update({'largest_preserved_span_byte_count': state['preserved_span_metrics']['largest_preserved_span_byte_count']})
    result.update({'preserved_span_with_offset_candidate_count': state['preserved_span_metrics']['preserved_span_with_offset_candidate_count']})
    result.update({'preserved_span_without_offset_candidate_count': state['preserved_span_metrics']['preserved_span_without_offset_candidate_count']})
    result.update({'member_descriptor_preserved_bytes': state['preserved_span_metrics']['member_descriptor_preserved_byte_count']})
    result.update({'member_descriptor_header_preserved_bytes': state['preserved_span_metrics']['member_descriptor_header_preserved_byte_count']})
    result.update({'member_descriptor_tail_preserved_bytes': state['preserved_span_metrics']['member_descriptor_tail_preserved_byte_count']})
    result.update({'preserved_unknown_bytes_excluding_member_descriptors': state['preserved_span_metrics']['preserved_unknown_byte_count_excluding_member_descriptors']})
    result.update({'preserved_unknown_bytes_excluding_member_descriptor_headers': state['preserved_span_metrics']['preserved_unknown_byte_count_excluding_member_descriptor_headers']})
    result.update({'preserved_unknown_bytes_without_block_semantics': state['preserved_unknown_bytes_without_block_semantics']})
    result.update({'preserved_span_with_member_descriptor_count': state['preserved_span_metrics']['preserved_span_with_member_descriptor_count']})
    result.update({'preserved_span_without_member_descriptor_count': state['preserved_span_metrics']['preserved_span_without_member_descriptor_count']})
    result.update({'preserved_span_with_member_descriptor_header_count': state['preserved_span_metrics']['preserved_span_with_member_descriptor_header_count']})
    return result


def _build_audit_success_row_part_4(state) -> dict[str, object]:
    result = {}
    result.update({'preserved_span_with_member_descriptor_tail_count': state['preserved_span_metrics']['preserved_span_with_member_descriptor_tail_count']})
    result.update({'reference_count': len(state['decoded'].references)})
    result.update({'editable_reference_count': len(state['rows']) if isinstance(state['rows'], list) else 0})
    result.update({'editable_placement_field_count': len(state['placement_rows']) if isinstance(state['placement_rows'], list) else 0})
    result.update({'resource_resize_impact_offset_candidate_count': state['resource_resize_impact_count']})
    result.update({'placement_resize_impact_offset_candidate_count': state['placement_resize_impact_count']})
    result.update({'resource_resize_impact_target_role_kind_counts': state['resource_resize_impact_target_role_kind_counts']})
    result.update({'placement_resize_impact_target_role_kind_counts': state['placement_resize_impact_target_role_kind_counts']})
    result.update({'resource_resize_impact_owner_kind_target_counts': state['resource_resize_impact_owner_kind_target_counts']})
    result.update({'placement_resize_impact_owner_kind_target_counts': state['placement_resize_impact_owner_kind_target_counts']})
    result.update({'resource_resize_impact_resource_reference_target_profile_distance_counts': state['resource_resize_impact_resource_reference_target_profile_distance_counts']})
    result.update({'placement_resize_impact_resource_reference_target_profile_distance_counts': state['placement_resize_impact_resource_reference_target_profile_distance_counts']})
    result.update({'resource_resize_impact_resource_reference_target_profile_span_position_counts': state['resource_resize_impact_resource_reference_target_profile_span_position_counts']})
    result.update({'placement_resize_impact_resource_reference_target_profile_span_position_counts': state['placement_resize_impact_resource_reference_target_profile_span_position_counts']})
    result.update({'resource_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts': state['resource_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts']})
    result.update({'placement_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts': state['placement_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts']})
    result.update({'resource_resize_impact_unique_offset_candidate_count': state['resource_resize_impact_unique_offset_candidate_count']})
    result.update({'placement_resize_impact_unique_offset_candidate_count': state['placement_resize_impact_unique_offset_candidate_count']})
    result.update({'resource_resize_impact_unique_target_role_kind_counts': state['resource_resize_impact_unique_target_role_kind_counts']})
    result.update({'placement_resize_impact_unique_target_role_kind_counts': state['placement_resize_impact_unique_target_role_kind_counts']})
    result.update({'resource_resize_impact_unique_owner_kind_target_counts': state['resource_resize_impact_unique_owner_kind_target_counts']})
    result.update({'placement_resize_impact_unique_owner_kind_target_counts': state['placement_resize_impact_unique_owner_kind_target_counts']})
    result.update({'resource_resize_impact_unique_candidate_profile_counts': state['resource_resize_impact_unique_candidate_profile_counts']})
    result.update({'placement_resize_impact_unique_candidate_profile_counts': state['placement_resize_impact_unique_candidate_profile_counts']})
    result.update({'resource_resize_impact_unique_overlap_profile_counts': state['resource_resize_impact_unique_overlap_profile_counts']})
    result.update({'placement_resize_impact_unique_overlap_profile_counts': state['placement_resize_impact_unique_overlap_profile_counts']})
    result.update({'resource_resize_impact_unique_overlap_group_profile_counts': state['resource_resize_impact_unique_overlap_group_profile_counts']})
    result.update({'placement_resize_impact_unique_overlap_group_profile_counts': state['placement_resize_impact_unique_overlap_group_profile_counts']})
    result.update({'resource_resize_impact_unique_overlap_group_target_identity_counts': state['resource_resize_impact_unique_overlap_group_target_identity_counts']})
    result.update({'placement_resize_impact_unique_overlap_group_target_identity_counts': state['placement_resize_impact_unique_overlap_group_target_identity_counts']})
    result.update({'resource_resize_impact_unique_same_target_overlap_collapse_counts': state['resource_resize_impact_unique_same_target_overlap_collapse_counts']})
    result.update({'placement_resize_impact_unique_same_target_overlap_collapse_counts': state['placement_resize_impact_unique_same_target_overlap_collapse_counts']})
    result.update({'resource_resize_impact_unique_same_target_overlap_shift_conflict_counts': state['resource_resize_impact_unique_same_target_overlap_shift_conflict_counts']})
    result.update({'placement_resize_impact_unique_same_target_overlap_shift_conflict_counts': state['placement_resize_impact_unique_same_target_overlap_shift_conflict_counts']})
    result.update({'resource_resize_impact_unique_same_target_shift_conflict_group_detail_counts': state['resource_resize_impact_unique_same_target_shift_conflict_group_detail_counts']})
    result.update({'placement_resize_impact_unique_same_target_shift_conflict_group_detail_counts': state['placement_resize_impact_unique_same_target_shift_conflict_group_detail_counts']})
    result.update({'resource_resize_impact_unique_same_target_resource_alias_counts': state['resource_resize_impact_unique_same_target_resource_alias_counts']})
    result.update({'placement_resize_impact_unique_same_target_resource_alias_counts': state['placement_resize_impact_unique_same_target_resource_alias_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_shift_conflict_counts': state['resource_resize_impact_unique_mixed_target_overlap_shift_conflict_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_shift_conflict_counts': state['placement_resize_impact_unique_mixed_target_overlap_shift_conflict_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_profile_counts': state['resource_resize_impact_unique_mixed_target_shift_consistent_profile_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_profile_counts': state['placement_resize_impact_unique_mixed_target_shift_consistent_profile_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_identity_counts': state['resource_resize_impact_unique_mixed_target_shift_consistent_identity_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_identity_counts': state['placement_resize_impact_unique_mixed_target_shift_consistent_identity_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_shape_counts': state['resource_resize_impact_unique_mixed_target_shift_consistent_shape_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_shape_counts': state['placement_resize_impact_unique_mixed_target_shift_consistent_shape_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts': state['resource_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts': state['placement_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts': state['resource_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts': state['placement_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_blocker_profile_counts': state['resource_resize_impact_unique_mixed_target_overlap_blocker_profile_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_blocker_profile_counts': state['placement_resize_impact_unique_mixed_target_overlap_blocker_profile_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts': state['resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts': state['placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary': state['resource_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary']})
    return result


def _build_audit_success_row_part_5(state) -> dict[str, object]:
    result = {}
    result.update({'placement_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary': state['placement_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts': state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts': state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts']})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_impacted_shape_counts': state['resource_resize_impact_unique_mixed_target_overlap_impacted_shape_counts']})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_impacted_shape_counts': state['placement_resize_impact_unique_mixed_target_overlap_impacted_shape_counts']})
    result.update({'resource_resize_impact_unique_resource_reference_target_profile_distance_counts': state['resource_resize_impact_unique_resource_reference_target_profile_distance_counts']})
    result.update({'placement_resize_impact_unique_resource_reference_target_profile_distance_counts': state['placement_resize_impact_unique_resource_reference_target_profile_distance_counts']})
    result.update({'resource_resize_impact_unique_overlap_counts': state['resource_resize_impact_unique_overlap_counts']})
    result.update({'placement_resize_impact_unique_overlap_counts': state['placement_resize_impact_unique_overlap_counts']})
    result.update({'resource_resize_impact_unique_resource_reference_overlap_counts': state['resource_resize_impact_unique_resource_reference_overlap_counts']})
    result.update({'placement_resize_impact_unique_resource_reference_overlap_counts': state['placement_resize_impact_unique_resource_reference_overlap_counts']})
    result.update({'policy_resize_readiness': state['policy_resize_readiness']})
    result.update({'length_change_tail_only_candidate_count': state['length_change_plan_counts']['tail_only_candidate_count']})
    result.update({'length_change_downstream_rebuild_row_count': state['length_change_plan_counts']['downstream_rebuild_row_count']})
    result.update({'length_change_offset_rebuild_row_count': state['length_change_plan_counts']['offset_rebuild_row_count']})
    result.update({'layout_rebuild_byte_identical': state['rebuild_ok']})
    result.update({'json_layout_rebuild_byte_identical': state['json_rebuild_ok']})
    result.update({'no_edit_roundtrip_byte_identical': state['import_ok']})
    result.update({'same_length_resource_edit_probe': state['edit_probe']})
    result.update({'same_length_placement_edit_probe': state['placement_probe']})
    result.update({'experimental_length_change_resource_rebuild_probe': state['experimental_length_probe']})
    result.update({'experimental_length_change_placement_rebuild_probe': state['experimental_placement_length_probe']})
    result.update({'report_only_array_count_hint_mutation_probe': state['array_count_hint_mutation_probe']})
    result.update({'report_only_transform_word3_mutation_probe': state['transform_word3_mutation_probe']})
    result.update({'report_only_reference_word3_mutation_probe': state['reference_word3_mutation_probe']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe': state['preserved_unknown_byte_mutation_probe']})
    result.update({'report_only_descriptor_word3_mutation_probe': state['descriptor_word3_mutation_probe']})
    result.update({'elapsed_ms': round((time.perf_counter() - state['started']) * 1000, 3)})
    result.update({'error': '' if state['ok'] else 'Prefab JSON import, layout rebuild, or same-length edit probe failed.'})
    return result


def _build_audit_success_row(state) -> dict[str, object]:
    result: dict[str, object] = {}
    result.update(_build_audit_success_row_part_0(state))
    result.update(_build_audit_success_row_part_1(state))
    result.update(_build_audit_success_row_part_2(state))
    result.update(_build_audit_success_row_part_3(state))
    result.update(_build_audit_success_row_part_4(state))
    result.update(_build_audit_success_row_part_5(state))
    return result


def _build_audit_error_row_part_0(state, exc) -> dict[str, object]:
    result = {}
    result.update({'path': state['virtual_path']})
    result.update({'status': 'failed'})
    result.update({'byte_length': len(state['payload'])})
    result.update({'prefab_header': {}})
    result.update({'prefab_layout': {}})
    result.update({'declared_field_count': 0})
    result.update({'member_declaration_count': 0})
    result.update({'member_descriptor_bytes': 0})
    result.update({'descriptor_tail_member_kind_counts': {}})
    result.update({'descriptor_tail_byte_kind_counts': {}})
    result.update({'descriptor_tail_member_detail_counts': {}})
    result.update({'transform_member_count': 0})
    result.update({'decoded_transform_payload_value_rows': 0})
    result.update({'transform_members_without_payload_values': 0})
    result.update({'transform_members_with_descriptor_tail_bytes': 0})
    result.update({'transform_descriptor_tail_bytes': 0})
    result.update({'transform_name_only_member_count': 0})
    result.update({'transform_descriptor_signature_counts': {}})
    result.update({'transform_descriptor_signature_offset_candidate_counts': {}})
    result.update({'transform_nonzero_word3_offset_candidate_status_counts': {'with_offset_candidate': 0, 'without_offset_candidate': 0}})
    result.update({'transform_descriptor_signature_offset_candidate_target_counts': {}})
    result.update({'transform_nonzero_word3_offset_candidate_target_counts': {}})
    result.update({'transform_descriptor_word0_value_counts': {}})
    result.update({'transform_descriptor_word1_value_counts': {}})
    result.update({'transform_descriptor_word2_value_counts': {}})
    result.update({'transform_descriptor_word3_value_counts': {}})
    result.update({'transform_theoretical_payload_shape_counts': {}})
    result.update({'transform_theoretical_payload_member_rows': 0})
    result.update({'transform_theoretical_payload_byte_count': 0})
    result.update({'transform_theoretical_payload_exact_preserved_span_rows': 0})
    result.update({'transform_theoretical_payload_later_preserved_span_fit_rows': 0})
    result.update({'transform_theoretical_payload_no_preserved_span_fit_rows': 0})
    result.update({'transform_theoretical_payload_immediate_window_string_span_overlap_rows': 0})
    result.update({'transform_theoretical_payload_immediate_window_string_span_overlap_count': 0})
    result.update({'transform_theoretical_payload_immediate_window_string_span_role_counts': {}})
    result.update({'transform_theoretical_payload_immediate_window_string_span_relation_counts': {}})
    result.update({'transform_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows': 0})
    result.update({'transform_theoretical_payload_later_fit_gap_string_span_relation_counts': {}})
    result.update({'transform_theoretical_payload_later_fit_gap_member_descriptor_relation_counts': {}})
    result.update({'array_member_count': 0})
    result.update({'decoded_array_payload_element_rows': 0})
    result.update({'array_members_without_payload_elements': 0})
    result.update({'array_members_with_descriptor_tail_bytes': 0})
    result.update({'array_descriptor_tail_bytes': 0})
    result.update({'array_member_stride_hint_count': 0})
    result.update({'array_member_count_hint_count': 0})
    result.update({'array_descriptor_signature_counts': {}})
    result.update({'array_descriptor_signature_offset_candidate_counts': {}})
    result.update({'array_descriptor_signature_offset_candidate_target_counts': {}})
    result.update({'array_nonzero_word3_offset_candidate_target_counts': {}})
    result.update({'array_descriptor_word0_value_counts': {}})
    result.update({'array_descriptor_word1_value_counts': {}})
    result.update({'array_descriptor_word2_value_counts': {}})
    result.update({'array_descriptor_word3_value_counts': {}})
    result.update({'array_stride_hint_type_counts': {}})
    return result


def _build_audit_error_row_part_1(state, exc) -> dict[str, object]:
    result = {}
    result.update({'array_count_hint_type_counts': {}})
    result.update({'array_count_hint_member_counts': {}})
    result.update({'array_word3_relation_counts': {'array_rows': 0, 'with_count_hint_rows': 0, 'with_stride_hint_rows': 0, 'word3_zero_rows': 0, 'word3_nonzero_rows': 0, 'word3_equals_count_hint_rows': 0, 'word3_nonzero_equals_count_hint_rows': 0, 'count_hint_positive_word3_equals_count_hint_rows': 0, 'count_hint_positive_word3_not_count_hint_rows': 0, 'word3_equals_stride_hint_rows': 0, 'word3_equals_word2_delta_rows': 0, 'word3_nonzero_without_count_hint_rows': 0, 'word3_nonzero_without_stride_hint_rows': 0}})
    result.update({'array_theoretical_payload_shape_counts': {}})
    result.update({'array_theoretical_payload_member_rows': 0})
    result.update({'array_theoretical_payload_byte_count': 0})
    result.update({'array_theoretical_payload_non_tiny_member_rows': 0})
    result.update({'array_theoretical_payload_non_tiny_byte_count': 0})
    result.update({'array_theoretical_payload_exact_preserved_span_rows': 0})
    result.update({'array_theoretical_payload_later_preserved_span_fit_rows': 0})
    result.update({'array_theoretical_payload_no_preserved_span_fit_rows': 0})
    result.update({'array_theoretical_payload_immediate_window_string_span_overlap_rows': 0})
    result.update({'array_theoretical_payload_immediate_window_string_span_overlap_count': 0})
    result.update({'array_theoretical_payload_immediate_window_string_span_role_counts': {}})
    result.update({'array_theoretical_payload_immediate_window_string_span_relation_counts': {}})
    result.update({'array_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows': 0})
    result.update({'array_theoretical_payload_later_fit_gap_string_span_relation_counts': {}})
    result.update({'array_theoretical_payload_later_fit_gap_member_descriptor_relation_counts': {}})
    result.update({'array_word2_delta_member_counts': {}})
    result.update({'array_word2_delta_word3_member_counts': {}})
    result.update({'array_word2_delta_word3_member_offset_candidate_counts': {}})
    result.update({'array_nonzero_word3_offset_candidate_status_counts': {'with_offset_candidate': 0, 'without_offset_candidate': 0}})
    result.update({'array_classification_source_counts': {'type_vector_count': 0, 'type_brackets_count': 0, 'name_list_flag_count': 0}})
    result.update({'array_word3_category_counts': {'zero_count': 0, 'one_count': 0, 'power_of_two_gt_one_count': 0, 'other_nonzero_count': 0, 'nonzero_with_stride_hint_count': 0, 'nonzero_without_stride_hint_count': 0}})
    result.update({'reference_member_count': 0})
    result.update({'reference_members_without_descriptor_semantics': 0})
    result.update({'reference_members_with_descriptor_tail_bytes': 0})
    result.update({'reference_descriptor_tail_bytes': 0})
    result.update({'reference_descriptor_signature_counts': {}})
    result.update({'reference_descriptor_tail_record_shape_counts': {}})
    result.update({'reference_descriptor_tail_offset_candidate_mod_counts': {}})
    result.update({'reference_descriptor_tail_record_profile_counts': {'exact_tail_members': 0, 'record_count_total': 0, 'unique_record_count_total': 0, 'duplicate_record_count_total': 0, 'offset_candidate_record_count_total': 0, 'offset_candidate_free_record_count_total': 0, 'offset_candidate_multi_kind_record_count_total': 0, 'max_offset_candidates_per_record': 0}})
    result.update({'reference_descriptor_tail_numeric_profile_counts': {}})
    result.update({'reference_descriptor_tail_column_profile_counts': {'exact_tail_members': 0, 'record_count_total': 0, 'u32_columns_total': 0, 'constant_u32_columns': 0, 'variable_u32_columns': 0, 'all_zero_u32_columns': 0, 'mostly_zero_u32_columns': 0, 'offset_candidate_u32_columns': 0, 'offset_candidate_free_u32_columns': 0, 'unique_u32_value_total': 0, 'max_unique_u32_values_per_column': 0, 'unaligned_offset_candidate_rows': 0}})
    result.update({'reference_descriptor_signature_offset_candidate_counts': {}})
    result.update({'reference_nonzero_word3_offset_candidate_status_counts': {'with_offset_candidate': 0, 'without_offset_candidate': 0}})
    result.update({'reference_descriptor_signature_offset_candidate_target_counts': {}})
    result.update({'reference_nonzero_word3_offset_candidate_target_counts': {}})
    result.update({'scalar_or_bool_descriptor_signature_counts': {}})
    result.update({'scalar_or_bool_descriptor_signature_offset_candidate_counts': {}})
    result.update({'scalar_or_bool_nonzero_word3_offset_candidate_status_counts': {'with_offset_candidate': 0, 'without_offset_candidate': 0}})
    result.update({'scalar_or_bool_descriptor_signature_offset_candidate_target_counts': {}})
    result.update({'scalar_or_bool_nonzero_word3_offset_candidate_target_counts': {}})
    result.update({'string_descriptor_signature_counts': {}})
    result.update({'string_descriptor_signature_offset_candidate_counts': {}})
    result.update({'string_nonzero_word3_offset_candidate_status_counts': {'with_offset_candidate': 0, 'without_offset_candidate': 0}})
    result.update({'string_descriptor_signature_offset_candidate_target_counts': {}})
    result.update({'string_nonzero_word3_offset_candidate_target_counts': {}})
    result.update({'generic_descriptor_signature_counts': {}})
    result.update({'generic_descriptor_signature_offset_candidate_counts': {}})
    result.update({'generic_nonzero_word3_offset_candidate_status_counts': {'with_offset_candidate': 0, 'without_offset_candidate': 0}})
    result.update({'generic_descriptor_signature_offset_candidate_target_counts': {}})
    result.update({'generic_nonzero_word3_offset_candidate_target_counts': {}})
    result.update({'descriptor_owner_kind_offset_candidate_counts': {}})
    result.update({'descriptor_owner_kind_offset_candidate_target_counts': {}})
    return result


def _build_audit_error_row_part_2(state, exc) -> dict[str, object]:
    result = {}
    result.update({'offset_candidate_count': 0})
    result.update({'offset_candidate_overlap_count': 0})
    result.update({'offset_candidate_aligned_count': 0})
    result.update({'offset_candidate_unaligned_count': 0})
    result.update({'offset_candidate_overlap_group_count': 0})
    result.update({'offset_candidate_overlapping_window_count': 0})
    result.update({'offset_candidate_isolated_count': 0})
    result.update({'offset_candidate_aligned_isolated_count': 0})
    result.update({'offset_candidate_unaligned_isolated_count': 0})
    result.update({'offset_candidate_unaligned_or_overlapping_count': 0})
    result.update({'offset_candidate_target_string_length_prefix_count': 0})
    result.update({'offset_candidate_target_string_value_count': 0})
    result.update({'offset_candidate_target_string_end_count': 0})
    result.update({'offset_candidate_in_member_descriptor_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_count': 0})
    result.update({'offset_candidate_in_array_descriptor_count': 0})
    result.update({'offset_candidate_in_transform_descriptor_count': 0})
    result.update({'offset_candidate_in_reference_descriptor_count': 0})
    result.update({'offset_candidate_in_scalar_or_bool_descriptor_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_overlap_group_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_overlapping_window_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_isolated_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_isolated_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_or_overlapping_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_target_string_length_prefix_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_target_string_value_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_target_string_end_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_candidate_offset_mod4_counts': {'0': 0, '1': 0, '2': 0, '3': 0}})
    result.update({'offset_candidate_outside_member_descriptor_target_value_mod4_counts': {'0': 0, '1': 0, '2': 0, '3': 0}})
    result.update({'offset_candidate_outside_member_descriptor_string_value_candidate_offset_mod4_counts': {'0': 0, '1': 0, '2': 0, '3': 0}})
    result.update({'offset_candidate_outside_member_descriptor_string_value_target_value_mod4_counts': {'0': 0, '1': 0, '2': 0, '3': 0}})
    result.update({'offset_candidate_outside_member_descriptor_neighbor_byte_class_counts': {'ascii_like': 0, 'binary_like': 0, 'empty': 0, 'nul_rich': 0}})
    result.update({'offset_candidate_outside_member_descriptor_target_role_counts': {'resource_reference_count': 0, 'member_name_count': 0, 'member_type_count': 0, 'other_string_count': 0}})
    result.update({'offset_candidate_outside_member_descriptor_string_value_target_role_counts': {'resource_reference_count': 0, 'member_name_count': 0, 'member_type_count': 0, 'other_string_count': 0}})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_target_role_kind_counts': {}})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_outside_preserved_span_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_exact_4_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_le_8_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_start_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_end_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_middle_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_aligned_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_unaligned_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_isolated_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_unaligned_or_overlapping_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_length_prefix_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_value_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_end_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_aligned_count': 0})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_unaligned_count': 0})
    return result
