from __future__ import annotations

import json
import math
import struct
import time
from bisect import bisect_right
from copy import deepcopy
from functools import lru_cache
from pathlib import Path
from typing import Callable, Mapping, Optional, Sequence, TypeVar

from cdmw.core.common import raise_if_cancelled
from cdmw.core.archive_attachment_patches import (
    build_prefab_attachment_profile_patch,
    inspect_prefab_attachment_profile_fields,
)
from cdmw.core.crimson_formats import decode_prefab, rebuild_prefab_no_edit
from cdmw.core.prefab_json import (
    PrefabEditJsonError,
    apply_prefab_edit_document,
    build_prefab_edit_document,
    rebuild_prefab_no_edit_from_edit_document,
)
from cdmw.models import ArchiveEntry
from cdmw.core.prefab_corpus_contracts import (
    EDIT_PROBES_DISABLED_REASON,
    NO_SAFE_PLACEMENT_LENGTH_PROBE_REASON,
    NO_SAFE_RESOURCE_LENGTH_PROBE_REASON,
    OVERLAPPING_OFFSET_CANDIDATES_REASON,
    PREFAB_JSON_IMPORT_CORPUS_FORMAT,
    T,
)


def _audit_prefab_json_import_sample_stage_0(state: Mapping[str]) -> dict[str, object]:
    from cdmw.core.prefab_corpus_candidate_roles import _resize_impact_offset_candidate_owner_kind_target_counts, _resize_impact_offset_candidate_target_role_kind_counts, _resize_impact_unique_offset_candidate_count, _resize_impact_unique_offset_candidate_owner_kind_target_counts
    from cdmw.core.prefab_corpus_candidate_roles import _resize_impact_unique_offset_candidate_target_role_kind_counts
    from cdmw.core.prefab_corpus_probe_metrics import _policy_resize_readiness
    from cdmw.core.prefab_corpus_probe_values import _resize_impact_offset_candidate_count
    from cdmw.core.prefab_corpus_resize_impact_0 import _resize_impact_unique_offset_candidate_mixed_target_overlap_blocker_profile_counts, _resize_impact_unique_offset_candidate_mixed_target_overlap_shift_conflict_counts, _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_group_detail_counts, _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_identity_counts
    from cdmw.core.prefab_corpus_resize_impact_0 import _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_metadata_collision_counts, _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_profile_counts, _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_shape_counts, _resize_impact_unique_offset_candidate_overlap_group_profile_counts
    from cdmw.core.prefab_corpus_resize_impact_0 import _resize_impact_unique_offset_candidate_overlap_group_target_identity_counts, _resize_impact_unique_offset_candidate_overlap_profile_counts, _resize_impact_unique_offset_candidate_profile_counts, _resize_impact_unique_offset_candidate_same_target_overlap_collapse_counts
    from cdmw.core.prefab_corpus_resize_impact_0 import _resize_impact_unique_offset_candidate_same_target_overlap_shift_conflict_counts, _resize_impact_unique_offset_candidate_same_target_resource_alias_counts, _resize_impact_unique_offset_candidate_same_target_shift_conflict_group_detail_counts
    from cdmw.core.prefab_corpus_resize_impact_1 import _identity_repeat_summary, _resize_impact_resource_reference_target_profile_distance_counts, _resize_impact_resource_reference_target_profile_neighbor_byte_class_counts, _resize_impact_resource_reference_target_profile_span_position_counts
    from cdmw.core.prefab_corpus_resize_impact_1 import _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_collapse_counts, _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_identity_counts, _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_profile_counts, _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts
    from cdmw.core.prefab_corpus_resize_impact_1 import _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_role_counts, _resize_impact_unique_offset_candidate_mixed_target_overlap_impacted_identity_counts
    payload, virtual_path = (state['payload'], state['virtual_path'])
    document = build_prefab_edit_document(payload, virtual_path)
    patched = apply_prefab_edit_document(payload, document, virtual_path=virtual_path)
    rebuilt = rebuild_prefab_no_edit(payload)
    json_rebuilt = rebuild_prefab_no_edit_from_edit_document(payload, document, virtual_path=virtual_path)
    decoded = decode_prefab(payload)
    rows = document.get('editable', {}).get('resource_references', [])
    placement_rows = document.get('editable', {}).get('placement_fields', [])
    policy_resize_readiness = _policy_resize_readiness(document)
    resource_resize_impact_count = _resize_impact_offset_candidate_count(rows)
    placement_resize_impact_count = _resize_impact_offset_candidate_count(placement_rows)
    resource_resize_impact_target_role_kind_counts = _resize_impact_offset_candidate_target_role_kind_counts(decoded, rows)
    placement_resize_impact_target_role_kind_counts = _resize_impact_offset_candidate_target_role_kind_counts(decoded, placement_rows)
    resource_resize_impact_owner_kind_target_counts = _resize_impact_offset_candidate_owner_kind_target_counts(decoded, rows)
    placement_resize_impact_owner_kind_target_counts = _resize_impact_offset_candidate_owner_kind_target_counts(decoded, placement_rows)
    resource_resize_impact_resource_reference_target_profile_distance_counts = _resize_impact_resource_reference_target_profile_distance_counts(decoded, rows)
    placement_resize_impact_resource_reference_target_profile_distance_counts = _resize_impact_resource_reference_target_profile_distance_counts(decoded, placement_rows)
    resource_resize_impact_resource_reference_target_profile_span_position_counts = _resize_impact_resource_reference_target_profile_span_position_counts(decoded, rows)
    placement_resize_impact_resource_reference_target_profile_span_position_counts = _resize_impact_resource_reference_target_profile_span_position_counts(decoded, placement_rows)
    resource_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts = _resize_impact_resource_reference_target_profile_neighbor_byte_class_counts(decoded, rows, payload)
    placement_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts = _resize_impact_resource_reference_target_profile_neighbor_byte_class_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_offset_candidate_count = _resize_impact_unique_offset_candidate_count(decoded, rows)
    placement_resize_impact_unique_offset_candidate_count = _resize_impact_unique_offset_candidate_count(decoded, placement_rows)
    resource_resize_impact_unique_target_role_kind_counts = _resize_impact_unique_offset_candidate_target_role_kind_counts(decoded, rows)
    placement_resize_impact_unique_target_role_kind_counts = _resize_impact_unique_offset_candidate_target_role_kind_counts(decoded, placement_rows)
    resource_resize_impact_unique_owner_kind_target_counts = _resize_impact_unique_offset_candidate_owner_kind_target_counts(decoded, rows)
    placement_resize_impact_unique_owner_kind_target_counts = _resize_impact_unique_offset_candidate_owner_kind_target_counts(decoded, placement_rows)
    resource_resize_impact_unique_candidate_profile_counts = _resize_impact_unique_offset_candidate_profile_counts(decoded, rows, payload)
    placement_resize_impact_unique_candidate_profile_counts = _resize_impact_unique_offset_candidate_profile_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_overlap_profile_counts = _resize_impact_unique_offset_candidate_overlap_profile_counts(decoded, rows, payload)
    placement_resize_impact_unique_overlap_profile_counts = _resize_impact_unique_offset_candidate_overlap_profile_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_overlap_group_profile_counts = _resize_impact_unique_offset_candidate_overlap_group_profile_counts(decoded, rows)
    placement_resize_impact_unique_overlap_group_profile_counts = _resize_impact_unique_offset_candidate_overlap_group_profile_counts(decoded, placement_rows)
    resource_resize_impact_unique_overlap_group_target_identity_counts = _resize_impact_unique_offset_candidate_overlap_group_target_identity_counts(decoded, rows)
    placement_resize_impact_unique_overlap_group_target_identity_counts = _resize_impact_unique_offset_candidate_overlap_group_target_identity_counts(decoded, placement_rows)
    resource_resize_impact_unique_same_target_overlap_collapse_counts = _resize_impact_unique_offset_candidate_same_target_overlap_collapse_counts(decoded, rows)
    placement_resize_impact_unique_same_target_overlap_collapse_counts = _resize_impact_unique_offset_candidate_same_target_overlap_collapse_counts(decoded, placement_rows)
    resource_resize_impact_unique_same_target_overlap_shift_conflict_counts = _resize_impact_unique_offset_candidate_same_target_overlap_shift_conflict_counts(decoded, rows, payload)
    placement_resize_impact_unique_same_target_overlap_shift_conflict_counts = _resize_impact_unique_offset_candidate_same_target_overlap_shift_conflict_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_same_target_shift_conflict_group_detail_counts = _resize_impact_unique_offset_candidate_same_target_shift_conflict_group_detail_counts(decoded, rows, payload)
    placement_resize_impact_unique_same_target_shift_conflict_group_detail_counts = _resize_impact_unique_offset_candidate_same_target_shift_conflict_group_detail_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_same_target_resource_alias_counts = _resize_impact_unique_offset_candidate_same_target_resource_alias_counts(decoded, rows, payload)
    placement_resize_impact_unique_same_target_resource_alias_counts = _resize_impact_unique_offset_candidate_same_target_resource_alias_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_overlap_shift_conflict_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_shift_conflict_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_overlap_shift_conflict_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_shift_conflict_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_shift_consistent_profile_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_profile_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_shift_consistent_profile_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_profile_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_shift_consistent_identity_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_identity_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_shift_consistent_identity_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_identity_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_shift_consistent_shape_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_shape_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_shift_consistent_shape_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_shape_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_group_detail_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_group_detail_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_metadata_collision_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts = _resize_impact_unique_offset_candidate_mixed_target_shift_consistent_metadata_collision_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_overlap_blocker_profile_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_blocker_profile_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_overlap_blocker_profile_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_blocker_profile_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_impacted_identity_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_impacted_identity_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary = _identity_repeat_summary(resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts)
    placement_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary = _identity_repeat_summary(placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_collapse_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_collapse_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_profile_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_profile_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_identity_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_identity_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_role_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_role_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts(decoded, placement_rows, payload)
    result = {}
    result.update({'decoded': decoded, 'document': document, 'json_rebuilt': json_rebuilt, 'patched': patched, 'placement_resize_impact_count': placement_resize_impact_count})
    result.update({'placement_resize_impact_owner_kind_target_counts': placement_resize_impact_owner_kind_target_counts, 'placement_resize_impact_resource_reference_target_profile_distance_counts': placement_resize_impact_resource_reference_target_profile_distance_counts, 'placement_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts': placement_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts, 'placement_resize_impact_resource_reference_target_profile_span_position_counts': placement_resize_impact_resource_reference_target_profile_span_position_counts, 'placement_resize_impact_target_role_kind_counts': placement_resize_impact_target_role_kind_counts})
    result.update({'placement_resize_impact_unique_candidate_profile_counts': placement_resize_impact_unique_candidate_profile_counts, 'placement_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts, 'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts, 'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts, 'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts, 'placement_resize_impact_unique_mixed_target_overlap_blocker_profile_counts': placement_resize_impact_unique_mixed_target_overlap_blocker_profile_counts, 'placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts': placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts, 'placement_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary': placement_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary, 'placement_resize_impact_unique_mixed_target_overlap_shift_conflict_counts': placement_resize_impact_unique_mixed_target_overlap_shift_conflict_counts})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts': placement_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts, 'placement_resize_impact_unique_mixed_target_shift_consistent_identity_counts': placement_resize_impact_unique_mixed_target_shift_consistent_identity_counts, 'placement_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts': placement_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts, 'placement_resize_impact_unique_mixed_target_shift_consistent_profile_counts': placement_resize_impact_unique_mixed_target_shift_consistent_profile_counts, 'placement_resize_impact_unique_mixed_target_shift_consistent_shape_counts': placement_resize_impact_unique_mixed_target_shift_consistent_shape_counts})
    result.update({'placement_resize_impact_unique_offset_candidate_count': placement_resize_impact_unique_offset_candidate_count, 'placement_resize_impact_unique_overlap_group_profile_counts': placement_resize_impact_unique_overlap_group_profile_counts, 'placement_resize_impact_unique_overlap_group_target_identity_counts': placement_resize_impact_unique_overlap_group_target_identity_counts, 'placement_resize_impact_unique_overlap_profile_counts': placement_resize_impact_unique_overlap_profile_counts, 'placement_resize_impact_unique_owner_kind_target_counts': placement_resize_impact_unique_owner_kind_target_counts})
    result.update({'placement_resize_impact_unique_same_target_overlap_collapse_counts': placement_resize_impact_unique_same_target_overlap_collapse_counts, 'placement_resize_impact_unique_same_target_overlap_shift_conflict_counts': placement_resize_impact_unique_same_target_overlap_shift_conflict_counts, 'placement_resize_impact_unique_same_target_resource_alias_counts': placement_resize_impact_unique_same_target_resource_alias_counts, 'placement_resize_impact_unique_same_target_shift_conflict_group_detail_counts': placement_resize_impact_unique_same_target_shift_conflict_group_detail_counts, 'placement_resize_impact_unique_target_role_kind_counts': placement_resize_impact_unique_target_role_kind_counts})
    result.update({'placement_rows': placement_rows, 'policy_resize_readiness': policy_resize_readiness, 'rebuilt': rebuilt, 'resource_resize_impact_count': resource_resize_impact_count, 'resource_resize_impact_owner_kind_target_counts': resource_resize_impact_owner_kind_target_counts})
    result.update({'resource_resize_impact_resource_reference_target_profile_distance_counts': resource_resize_impact_resource_reference_target_profile_distance_counts, 'resource_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts': resource_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts, 'resource_resize_impact_resource_reference_target_profile_span_position_counts': resource_resize_impact_resource_reference_target_profile_span_position_counts, 'resource_resize_impact_target_role_kind_counts': resource_resize_impact_target_role_kind_counts, 'resource_resize_impact_unique_candidate_profile_counts': resource_resize_impact_unique_candidate_profile_counts})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts, 'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts, 'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts, 'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts, 'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_blocker_profile_counts': resource_resize_impact_unique_mixed_target_overlap_blocker_profile_counts, 'resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts': resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts, 'resource_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary': resource_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary, 'resource_resize_impact_unique_mixed_target_overlap_shift_conflict_counts': resource_resize_impact_unique_mixed_target_overlap_shift_conflict_counts, 'resource_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts': resource_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_identity_counts': resource_resize_impact_unique_mixed_target_shift_consistent_identity_counts, 'resource_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts': resource_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts, 'resource_resize_impact_unique_mixed_target_shift_consistent_profile_counts': resource_resize_impact_unique_mixed_target_shift_consistent_profile_counts, 'resource_resize_impact_unique_mixed_target_shift_consistent_shape_counts': resource_resize_impact_unique_mixed_target_shift_consistent_shape_counts, 'resource_resize_impact_unique_offset_candidate_count': resource_resize_impact_unique_offset_candidate_count})
    result.update({'resource_resize_impact_unique_overlap_group_profile_counts': resource_resize_impact_unique_overlap_group_profile_counts, 'resource_resize_impact_unique_overlap_group_target_identity_counts': resource_resize_impact_unique_overlap_group_target_identity_counts, 'resource_resize_impact_unique_overlap_profile_counts': resource_resize_impact_unique_overlap_profile_counts, 'resource_resize_impact_unique_owner_kind_target_counts': resource_resize_impact_unique_owner_kind_target_counts, 'resource_resize_impact_unique_same_target_overlap_collapse_counts': resource_resize_impact_unique_same_target_overlap_collapse_counts})
    result.update({'resource_resize_impact_unique_same_target_overlap_shift_conflict_counts': resource_resize_impact_unique_same_target_overlap_shift_conflict_counts, 'resource_resize_impact_unique_same_target_resource_alias_counts': resource_resize_impact_unique_same_target_resource_alias_counts, 'resource_resize_impact_unique_same_target_shift_conflict_group_detail_counts': resource_resize_impact_unique_same_target_shift_conflict_group_detail_counts, 'resource_resize_impact_unique_target_role_kind_counts': resource_resize_impact_unique_target_role_kind_counts, 'rows': rows})
    return result


def _audit_prefab_json_import_sample_stage_1(state: Mapping[str]) -> dict[str, object]:
    from cdmw.core.prefab_corpus_array_metrics import _array_classification_source_counts, _array_count_hint_member_counts, _array_count_hint_type_counts, _array_descriptor_signature_counts
    from cdmw.core.prefab_corpus_array_metrics import _array_descriptor_signature_offset_candidate_counts, _array_descriptor_signature_offset_candidate_target_counts, _array_descriptor_word_value_counts, _array_exact_payload_owner_counts
    from cdmw.core.prefab_corpus_array_metrics import _array_nonzero_word3_offset_candidate_status_counts, _array_stride_hint_type_counts, _array_theoretical_payload_shape_counts, _array_theoretical_payload_span_fit_metrics
    from cdmw.core.prefab_corpus_array_metrics import _array_word2_delta_member_counts, _array_word2_delta_word3_member_counts, _array_word2_delta_word3_member_offset_candidate_counts, _array_word3_category_counts
    from cdmw.core.prefab_corpus_array_metrics import _array_word3_relation_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _descriptor_tail_kind_metrics, _descriptor_tail_member_detail_counts, _descriptor_tail_metrics, _nonzero_word3_offset_candidate_status_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _nonzero_word3_offset_candidate_target_counts, _reference_descriptor_signature_counts, _reference_descriptor_tail_offset_candidate_mod_counts, _reference_descriptor_tail_record_shape_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _transform_descriptor_signature_counts, _transform_descriptor_signature_offset_candidate_counts, _transform_descriptor_signature_offset_candidate_target_counts, _transform_descriptor_word_value_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _transform_exact_payload_owner_counts, _transform_theoretical_payload_shape_counts, _transform_theoretical_payload_span_fit_metrics
    from cdmw.core.prefab_corpus_probe_values import _length_change_plan_counts
    from cdmw.core.prefab_corpus_resize_impact_0 import _resize_impact_unique_offset_candidate_overlap_counts
    from cdmw.core.prefab_corpus_resize_impact_1 import _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts, _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts, _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_shape_counts, _resize_impact_unique_offset_candidate_mixed_target_overlap_impacted_shape_counts
    from cdmw.core.prefab_corpus_resize_impact_1 import _resize_impact_unique_resource_reference_target_profile_distance_counts
    decoded, payload, placement_rows = (state['decoded'], state['payload'], state['placement_rows'])
    rows, = (state['rows'],)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts(decoded, rows)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts(decoded, placement_rows)
    resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_shape_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts = _resize_impact_unique_offset_candidate_mixed_target_high_repeat_identity_remaining_shape_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_mixed_target_overlap_impacted_shape_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_impacted_shape_counts(decoded, rows, payload)
    placement_resize_impact_unique_mixed_target_overlap_impacted_shape_counts = _resize_impact_unique_offset_candidate_mixed_target_overlap_impacted_shape_counts(decoded, placement_rows, payload)
    resource_resize_impact_unique_resource_reference_target_profile_distance_counts = _resize_impact_unique_resource_reference_target_profile_distance_counts(decoded, rows)
    placement_resize_impact_unique_resource_reference_target_profile_distance_counts = _resize_impact_unique_resource_reference_target_profile_distance_counts(decoded, placement_rows)
    resource_resize_impact_unique_overlap_counts = _resize_impact_unique_offset_candidate_overlap_counts(decoded, rows)
    placement_resize_impact_unique_overlap_counts = _resize_impact_unique_offset_candidate_overlap_counts(decoded, placement_rows)
    resource_resize_impact_unique_resource_reference_overlap_counts = _resize_impact_unique_offset_candidate_overlap_counts(decoded, rows, target_role='resource_reference')
    placement_resize_impact_unique_resource_reference_overlap_counts = _resize_impact_unique_offset_candidate_overlap_counts(decoded, placement_rows, target_role='resource_reference')
    resource_length_change_plan_counts = _length_change_plan_counts(rows)
    placement_length_change_plan_counts = _length_change_plan_counts(placement_rows)
    length_change_plan_counts = {key: resource_length_change_plan_counts[key] + placement_length_change_plan_counts[key] for key in resource_length_change_plan_counts}
    member_descriptor_bytes = sum((declaration.descriptor_byte_length for declaration in decoded.member_declarations))
    descriptor_tail_kind_metrics = _descriptor_tail_kind_metrics(decoded.member_declarations)
    descriptor_tail_member_detail_counts = _descriptor_tail_member_detail_counts(decoded.member_declarations)
    transform_member_count = sum((1 for declaration in decoded.member_declarations if declaration.is_transform))
    transform_payload_owner_counts = _transform_exact_payload_owner_counts(decoded)
    decoded_transform_payload_value_rows = transform_payload_owner_counts['value_rows']
    transform_members_without_payload_values = max(0, transform_member_count - transform_payload_owner_counts['member_rows'])
    transform_descriptor_tail_metrics = _descriptor_tail_metrics(decoded.member_declarations, 'transform')
    transform_name_only_member_count = sum((1 for declaration in decoded.member_declarations if not declaration.is_transform and 'transform' in str(declaration.name or '').lower()))
    transform_descriptor_signature_counts = _transform_descriptor_signature_counts(decoded.member_declarations)
    transform_descriptor_signature_offset_candidate_counts = _transform_descriptor_signature_offset_candidate_counts(decoded)
    transform_nonzero_word3_offset_candidate_status_counts = _nonzero_word3_offset_candidate_status_counts(transform_descriptor_signature_offset_candidate_counts)
    transform_descriptor_signature_offset_candidate_target_counts = _transform_descriptor_signature_offset_candidate_target_counts(decoded)
    transform_nonzero_word3_offset_candidate_target_counts = _nonzero_word3_offset_candidate_target_counts(transform_descriptor_signature_offset_candidate_target_counts)
    transform_descriptor_word0_value_counts = _transform_descriptor_word_value_counts(decoded.member_declarations, 0)
    transform_descriptor_word1_value_counts = _transform_descriptor_word_value_counts(decoded.member_declarations, 1)
    transform_descriptor_word2_value_counts = _transform_descriptor_word_value_counts(decoded.member_declarations, 2)
    transform_descriptor_word3_value_counts = _transform_descriptor_word_value_counts(decoded.member_declarations, 3)
    transform_theoretical_payload_shape_counts = _transform_theoretical_payload_shape_counts(decoded.member_declarations)
    transform_theoretical_payload_span_fit_metrics = _transform_theoretical_payload_span_fit_metrics(decoded)
    array_member_count = sum((1 for declaration in decoded.member_declarations if declaration.is_array))
    array_payload_owner_counts = _array_exact_payload_owner_counts(decoded)
    decoded_array_payload_element_rows = array_payload_owner_counts['element_rows']
    array_members_without_payload_elements = max(0, array_member_count - array_payload_owner_counts['member_rows'])
    array_descriptor_tail_metrics = _descriptor_tail_metrics(decoded.member_declarations, 'array')
    array_stride_hint_count = sum((1 for declaration in decoded.member_declarations if declaration.is_array and declaration.array_stride_hint > 0))
    array_count_hint_count = sum((1 for declaration in decoded.member_declarations if declaration.is_array and declaration.array_count_hint > 0))
    array_descriptor_signature_counts = _array_descriptor_signature_counts(decoded.member_declarations)
    array_descriptor_signature_offset_candidate_counts = _array_descriptor_signature_offset_candidate_counts(decoded)
    array_descriptor_signature_offset_candidate_target_counts = _array_descriptor_signature_offset_candidate_target_counts(decoded)
    array_nonzero_word3_offset_candidate_target_counts = _nonzero_word3_offset_candidate_target_counts(array_descriptor_signature_offset_candidate_target_counts)
    array_descriptor_word0_value_counts = _array_descriptor_word_value_counts(decoded.member_declarations, 0)
    array_descriptor_word1_value_counts = _array_descriptor_word_value_counts(decoded.member_declarations, 1)
    array_descriptor_word2_value_counts = _array_descriptor_word_value_counts(decoded.member_declarations, 2)
    array_descriptor_word3_value_counts = _array_descriptor_word_value_counts(decoded.member_declarations, 3)
    array_stride_hint_type_counts = _array_stride_hint_type_counts(decoded.member_declarations)
    array_count_hint_type_counts = _array_count_hint_type_counts(decoded.member_declarations)
    array_count_hint_member_counts = _array_count_hint_member_counts(decoded.member_declarations)
    array_word3_relation_counts = _array_word3_relation_counts(decoded.member_declarations)
    array_theoretical_payload_shape_counts = _array_theoretical_payload_shape_counts(decoded.member_declarations)
    array_theoretical_payload_span_fit_metrics = _array_theoretical_payload_span_fit_metrics(decoded)
    array_word2_delta_member_counts = _array_word2_delta_member_counts(decoded.member_declarations)
    array_word2_delta_word3_member_counts = _array_word2_delta_word3_member_counts(decoded.member_declarations)
    array_word2_delta_word3_member_offset_candidate_counts = _array_word2_delta_word3_member_offset_candidate_counts(decoded)
    array_nonzero_word3_offset_candidate_status_counts = _array_nonzero_word3_offset_candidate_status_counts(array_word2_delta_word3_member_offset_candidate_counts)
    array_classification_source_counts = _array_classification_source_counts(decoded.member_declarations)
    array_word3_category_counts = _array_word3_category_counts(decoded.member_declarations)
    reference_member_count = sum((1 for declaration in decoded.member_declarations if declaration.is_reference))
    reference_members_without_descriptor_semantics = reference_member_count
    reference_descriptor_tail_metrics = _descriptor_tail_metrics(decoded.member_declarations, 'reference')
    reference_descriptor_signature_counts = _reference_descriptor_signature_counts(decoded.member_declarations)
    reference_descriptor_tail_record_shape_counts = _reference_descriptor_tail_record_shape_counts(decoded.member_declarations)
    reference_descriptor_tail_offset_candidate_mod_counts = _reference_descriptor_tail_offset_candidate_mod_counts(decoded)
    result = {}
    result.update({'array_classification_source_counts': array_classification_source_counts, 'array_count_hint_count': array_count_hint_count, 'array_count_hint_member_counts': array_count_hint_member_counts, 'array_count_hint_type_counts': array_count_hint_type_counts, 'array_descriptor_signature_counts': array_descriptor_signature_counts})
    result.update({'array_descriptor_signature_offset_candidate_counts': array_descriptor_signature_offset_candidate_counts, 'array_descriptor_signature_offset_candidate_target_counts': array_descriptor_signature_offset_candidate_target_counts, 'array_descriptor_tail_metrics': array_descriptor_tail_metrics, 'array_descriptor_word0_value_counts': array_descriptor_word0_value_counts, 'array_descriptor_word1_value_counts': array_descriptor_word1_value_counts})
    result.update({'array_descriptor_word2_value_counts': array_descriptor_word2_value_counts, 'array_descriptor_word3_value_counts': array_descriptor_word3_value_counts, 'array_member_count': array_member_count, 'array_members_without_payload_elements': array_members_without_payload_elements, 'array_nonzero_word3_offset_candidate_status_counts': array_nonzero_word3_offset_candidate_status_counts})
    result.update({'array_nonzero_word3_offset_candidate_target_counts': array_nonzero_word3_offset_candidate_target_counts, 'array_stride_hint_count': array_stride_hint_count, 'array_stride_hint_type_counts': array_stride_hint_type_counts, 'array_theoretical_payload_shape_counts': array_theoretical_payload_shape_counts, 'array_theoretical_payload_span_fit_metrics': array_theoretical_payload_span_fit_metrics})
    result.update({'array_word2_delta_member_counts': array_word2_delta_member_counts, 'array_word2_delta_word3_member_counts': array_word2_delta_word3_member_counts, 'array_word2_delta_word3_member_offset_candidate_counts': array_word2_delta_word3_member_offset_candidate_counts, 'array_word3_category_counts': array_word3_category_counts, 'array_word3_relation_counts': array_word3_relation_counts})
    result.update({'decoded_array_payload_element_rows': decoded_array_payload_element_rows, 'decoded_transform_payload_value_rows': decoded_transform_payload_value_rows, 'descriptor_tail_kind_metrics': descriptor_tail_kind_metrics, 'descriptor_tail_member_detail_counts': descriptor_tail_member_detail_counts, 'length_change_plan_counts': length_change_plan_counts})
    result.update({'member_descriptor_bytes': member_descriptor_bytes, 'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts, 'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts, 'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts': placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts, 'placement_resize_impact_unique_mixed_target_overlap_impacted_shape_counts': placement_resize_impact_unique_mixed_target_overlap_impacted_shape_counts})
    result.update({'placement_resize_impact_unique_overlap_counts': placement_resize_impact_unique_overlap_counts, 'placement_resize_impact_unique_resource_reference_overlap_counts': placement_resize_impact_unique_resource_reference_overlap_counts, 'placement_resize_impact_unique_resource_reference_target_profile_distance_counts': placement_resize_impact_unique_resource_reference_target_profile_distance_counts, 'reference_descriptor_signature_counts': reference_descriptor_signature_counts, 'reference_descriptor_tail_metrics': reference_descriptor_tail_metrics})
    result.update({'reference_descriptor_tail_offset_candidate_mod_counts': reference_descriptor_tail_offset_candidate_mod_counts, 'reference_descriptor_tail_record_shape_counts': reference_descriptor_tail_record_shape_counts, 'reference_member_count': reference_member_count, 'reference_members_without_descriptor_semantics': reference_members_without_descriptor_semantics, 'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts, 'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts': resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts, 'resource_resize_impact_unique_mixed_target_overlap_impacted_shape_counts': resource_resize_impact_unique_mixed_target_overlap_impacted_shape_counts, 'resource_resize_impact_unique_overlap_counts': resource_resize_impact_unique_overlap_counts, 'resource_resize_impact_unique_resource_reference_overlap_counts': resource_resize_impact_unique_resource_reference_overlap_counts})
    result.update({'resource_resize_impact_unique_resource_reference_target_profile_distance_counts': resource_resize_impact_unique_resource_reference_target_profile_distance_counts, 'transform_descriptor_signature_counts': transform_descriptor_signature_counts, 'transform_descriptor_signature_offset_candidate_counts': transform_descriptor_signature_offset_candidate_counts, 'transform_descriptor_signature_offset_candidate_target_counts': transform_descriptor_signature_offset_candidate_target_counts, 'transform_descriptor_tail_metrics': transform_descriptor_tail_metrics})
    result.update({'transform_descriptor_word0_value_counts': transform_descriptor_word0_value_counts, 'transform_descriptor_word1_value_counts': transform_descriptor_word1_value_counts, 'transform_descriptor_word2_value_counts': transform_descriptor_word2_value_counts, 'transform_descriptor_word3_value_counts': transform_descriptor_word3_value_counts, 'transform_member_count': transform_member_count})
    result.update({'transform_members_without_payload_values': transform_members_without_payload_values, 'transform_name_only_member_count': transform_name_only_member_count, 'transform_nonzero_word3_offset_candidate_status_counts': transform_nonzero_word3_offset_candidate_status_counts, 'transform_nonzero_word3_offset_candidate_target_counts': transform_nonzero_word3_offset_candidate_target_counts, 'transform_theoretical_payload_shape_counts': transform_theoretical_payload_shape_counts})
    result.update({'transform_theoretical_payload_span_fit_metrics': transform_theoretical_payload_span_fit_metrics})
    return result


def _audit_prefab_json_import_sample_stage_2(state: Mapping[str]) -> dict[str, object]:
    from cdmw.core.prefab_corpus_candidate_offsets_0 import _offset_candidate_metrics, _offset_candidate_neighbor_byte_class_counts, _offset_candidate_outside_descriptor_aligned_isolated_role_kind_counts, _offset_candidate_outside_descriptor_metrics
    from cdmw.core.prefab_corpus_candidate_offsets_0 import _offset_candidate_outside_descriptor_mod4_counts, _offset_candidate_outside_descriptor_preserved_middle_metrics, _offset_candidate_outside_descriptor_resource_reference_metrics, _offset_candidate_outside_descriptor_target_role_counts
    from cdmw.core.prefab_corpus_candidate_offsets_0 import _offset_candidate_overlap_count, _offset_candidate_preserved_span_byte_length_counts, _offset_candidate_resource_reference_alignment_target_kind_counts, _offset_candidate_resource_reference_alignment_target_kind_extension_counts
    from cdmw.core.prefab_corpus_candidate_offsets_0 import _offset_candidate_resource_reference_alignment_target_kind_role_counts, _offset_candidate_resource_reference_alignment_target_kind_span_bucket_counts, _offset_candidate_resource_reference_alignment_target_kind_span_position_counts, _offset_candidate_resource_reference_mod4_counts
    from cdmw.core.prefab_corpus_candidate_offsets_0 import _offset_candidate_resource_reference_target_profile_distance_counts, _offset_candidate_resource_reference_target_profile_neighbor_byte_class_counts, _offset_candidate_resource_reference_target_profile_span_position_counts, _outside_member_descriptor_offset_candidates
    from cdmw.core.prefab_corpus_candidate_offsets_0 import _outside_member_descriptor_resource_reference_offset_candidates
    from cdmw.core.prefab_corpus_candidate_offsets_1 import _offset_candidate_descriptor_metrics, _offset_candidate_outside_descriptor_aligned_isolated_span_metrics, _offset_candidate_resource_reference_span_metrics, _offset_candidate_span_metrics
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _descriptor_kind_nonzero_word3_offset_candidate_status_counts, _descriptor_kind_nonzero_word3_offset_candidate_target_counts, _descriptor_owner_kind_offset_candidate_counts, _descriptor_owner_kind_offset_candidate_target_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _generic_descriptor_signature_counts, _generic_descriptor_signature_offset_candidate_counts, _generic_descriptor_signature_offset_candidate_target_counts, _nonzero_word3_offset_candidate_status_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _nonzero_word3_offset_candidate_target_counts, _reference_descriptor_signature_offset_candidate_counts, _reference_descriptor_signature_offset_candidate_target_counts, _scalar_or_bool_descriptor_signature_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _scalar_or_bool_descriptor_signature_offset_candidate_counts, _scalar_or_bool_descriptor_signature_offset_candidate_target_counts, _string_descriptor_signature_counts, _string_descriptor_signature_offset_candidate_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_0 import _string_descriptor_signature_offset_candidate_target_counts
    from cdmw.core.prefab_corpus_descriptor_metrics_1 import _preserved_span_metrics, _reference_descriptor_tail_column_profile_counts, _reference_descriptor_tail_numeric_profile_counts, _reference_descriptor_tail_record_profile_counts
    from cdmw.core.prefab_corpus_edit_probes import _audit_experimental_length_change_placement_rebuild_probe, _audit_experimental_length_change_resource_rebuild_probe, _audit_same_length_placement_edit_probe, _audit_same_length_resource_edit_probe
    from cdmw.core.prefab_corpus_probe_metrics import _audit_report_only_array_count_hint_mutation_probe, _audit_report_only_descriptor_word3_mutation_probe, _audit_report_only_preserved_unknown_byte_mutation_probe, _audit_report_only_reference_word3_mutation_probe
    from cdmw.core.prefab_corpus_probe_metrics import _audit_report_only_transform_word3_mutation_probe, _skipped_probe_results
    array_nonzero_word3_offset_candidate_status_counts, array_nonzero_word3_offset_candidate_target_counts, decoded = (state['array_nonzero_word3_offset_candidate_status_counts'], state['array_nonzero_word3_offset_candidate_target_counts'], state['decoded'])
    document, include_edit_probes, payload = (state['document'], state['include_edit_probes'], state['payload'])
    transform_nonzero_word3_offset_candidate_status_counts, transform_nonzero_word3_offset_candidate_target_counts, virtual_path = (state['transform_nonzero_word3_offset_candidate_status_counts'], state['transform_nonzero_word3_offset_candidate_target_counts'], state['virtual_path'])
    reference_descriptor_tail_record_profile_counts = _reference_descriptor_tail_record_profile_counts(decoded, payload)
    reference_descriptor_tail_numeric_profile_counts = _reference_descriptor_tail_numeric_profile_counts(decoded, payload)
    reference_descriptor_tail_column_profile_counts = _reference_descriptor_tail_column_profile_counts(decoded, payload)
    reference_descriptor_signature_offset_candidate_counts = _reference_descriptor_signature_offset_candidate_counts(decoded)
    reference_nonzero_word3_offset_candidate_status_counts = _nonzero_word3_offset_candidate_status_counts(reference_descriptor_signature_offset_candidate_counts)
    reference_descriptor_signature_offset_candidate_target_counts = _reference_descriptor_signature_offset_candidate_target_counts(decoded)
    reference_nonzero_word3_offset_candidate_target_counts = _nonzero_word3_offset_candidate_target_counts(reference_descriptor_signature_offset_candidate_target_counts)
    scalar_or_bool_descriptor_signature_counts = _scalar_or_bool_descriptor_signature_counts(decoded.member_declarations)
    scalar_or_bool_descriptor_signature_offset_candidate_counts = _scalar_or_bool_descriptor_signature_offset_candidate_counts(decoded)
    scalar_or_bool_nonzero_word3_offset_candidate_status_counts = _nonzero_word3_offset_candidate_status_counts(scalar_or_bool_descriptor_signature_offset_candidate_counts)
    scalar_or_bool_descriptor_signature_offset_candidate_target_counts = _scalar_or_bool_descriptor_signature_offset_candidate_target_counts(decoded)
    scalar_or_bool_nonzero_word3_offset_candidate_target_counts = _nonzero_word3_offset_candidate_target_counts(scalar_or_bool_descriptor_signature_offset_candidate_target_counts)
    string_descriptor_signature_counts = _string_descriptor_signature_counts(decoded.member_declarations)
    string_descriptor_signature_offset_candidate_counts = _string_descriptor_signature_offset_candidate_counts(decoded)
    string_nonzero_word3_offset_candidate_status_counts = _nonzero_word3_offset_candidate_status_counts(string_descriptor_signature_offset_candidate_counts)
    string_descriptor_signature_offset_candidate_target_counts = _string_descriptor_signature_offset_candidate_target_counts(decoded)
    string_nonzero_word3_offset_candidate_target_counts = _nonzero_word3_offset_candidate_target_counts(string_descriptor_signature_offset_candidate_target_counts)
    generic_descriptor_signature_counts = _generic_descriptor_signature_counts(decoded.member_declarations)
    generic_descriptor_signature_offset_candidate_counts = _generic_descriptor_signature_offset_candidate_counts(decoded)
    generic_nonzero_word3_offset_candidate_status_counts = _nonzero_word3_offset_candidate_status_counts(generic_descriptor_signature_offset_candidate_counts)
    generic_descriptor_signature_offset_candidate_target_counts = _generic_descriptor_signature_offset_candidate_target_counts(decoded)
    generic_nonzero_word3_offset_candidate_target_counts = _nonzero_word3_offset_candidate_target_counts(generic_descriptor_signature_offset_candidate_target_counts)
    descriptor_kind_nonzero_word3_offset_candidate_status_counts = _descriptor_kind_nonzero_word3_offset_candidate_status_counts({'array': array_nonzero_word3_offset_candidate_status_counts, 'generic': generic_nonzero_word3_offset_candidate_status_counts, 'reference': reference_nonzero_word3_offset_candidate_status_counts, 'scalar_or_bool': scalar_or_bool_nonzero_word3_offset_candidate_status_counts, 'string': string_nonzero_word3_offset_candidate_status_counts, 'transform': transform_nonzero_word3_offset_candidate_status_counts})
    descriptor_kind_nonzero_word3_offset_candidate_target_counts = _descriptor_kind_nonzero_word3_offset_candidate_target_counts({'array': array_nonzero_word3_offset_candidate_target_counts, 'generic': generic_nonzero_word3_offset_candidate_target_counts, 'reference': reference_nonzero_word3_offset_candidate_target_counts, 'scalar_or_bool': scalar_or_bool_nonzero_word3_offset_candidate_target_counts, 'string': string_nonzero_word3_offset_candidate_target_counts, 'transform': transform_nonzero_word3_offset_candidate_target_counts})
    descriptor_owner_kind_offset_candidate_counts = _descriptor_owner_kind_offset_candidate_counts(decoded)
    descriptor_owner_kind_offset_candidate_target_counts = _descriptor_owner_kind_offset_candidate_target_counts(decoded)
    offset_candidate_count = len(decoded.offset_candidates)
    offset_candidate_overlap_count = _offset_candidate_overlap_count(decoded)
    offset_candidate_metrics = _offset_candidate_metrics(decoded)
    offset_candidate_outside_descriptor_metrics = _offset_candidate_outside_descriptor_metrics(decoded)
    offset_candidate_outside_descriptor_mod4_counts = _offset_candidate_outside_descriptor_mod4_counts(decoded)
    offset_candidate_outside_descriptor_neighbor_byte_class_counts = _offset_candidate_neighbor_byte_class_counts(payload, _outside_member_descriptor_offset_candidates(decoded))
    offset_candidate_outside_descriptor_target_role_counts = _offset_candidate_outside_descriptor_target_role_counts(decoded)
    offset_candidate_outside_descriptor_aligned_isolated_role_kind_counts = _offset_candidate_outside_descriptor_aligned_isolated_role_kind_counts(decoded)
    offset_candidate_outside_descriptor_aligned_isolated_span_metrics = _offset_candidate_outside_descriptor_aligned_isolated_span_metrics(decoded)
    offset_candidate_outside_descriptor_resource_reference_metrics = _offset_candidate_outside_descriptor_resource_reference_metrics(decoded)
    offset_candidate_outside_descriptor_preserved_middle_metrics = _offset_candidate_outside_descriptor_preserved_middle_metrics(decoded, payload)
    offset_candidate_resource_reference_mod4_counts = _offset_candidate_resource_reference_mod4_counts(decoded)
    offset_candidate_resource_reference_neighbor_byte_class_counts = _offset_candidate_neighbor_byte_class_counts(payload, _outside_member_descriptor_resource_reference_offset_candidates(decoded))
    offset_candidate_resource_reference_alignment_target_kind_counts = _offset_candidate_resource_reference_alignment_target_kind_counts(decoded)
    offset_candidate_resource_reference_alignment_target_kind_extension_counts = _offset_candidate_resource_reference_alignment_target_kind_extension_counts(decoded)
    offset_candidate_resource_reference_alignment_target_kind_role_counts = _offset_candidate_resource_reference_alignment_target_kind_role_counts(decoded)
    offset_candidate_resource_reference_alignment_target_kind_span_bucket_counts = _offset_candidate_resource_reference_alignment_target_kind_span_bucket_counts(decoded)
    offset_candidate_resource_reference_alignment_target_kind_span_position_counts = _offset_candidate_resource_reference_alignment_target_kind_span_position_counts(decoded)
    offset_candidate_resource_reference_target_profile_span_position_counts = _offset_candidate_resource_reference_target_profile_span_position_counts(decoded)
    offset_candidate_resource_reference_target_profile_distance_counts = _offset_candidate_resource_reference_target_profile_distance_counts(decoded)
    offset_candidate_resource_reference_target_profile_neighbor_byte_class_counts = _offset_candidate_resource_reference_target_profile_neighbor_byte_class_counts(decoded, payload)
    offset_candidate_resource_reference_span_metrics = _offset_candidate_resource_reference_span_metrics(decoded)
    offset_candidate_resource_reference_span_byte_length_counts = _offset_candidate_preserved_span_byte_length_counts(decoded, _outside_member_descriptor_resource_reference_offset_candidates(decoded))
    offset_candidate_descriptor_metrics = _offset_candidate_descriptor_metrics(decoded)
    offset_candidate_span_metrics = _offset_candidate_span_metrics(decoded)
    preserved_span_metrics = _preserved_span_metrics(decoded)
    preserved_unknown_bytes_without_block_semantics = preserved_span_metrics['preserved_unknown_byte_count_excluding_member_descriptor_headers']
    if include_edit_probes:
        edit_probe = _audit_same_length_resource_edit_probe(payload, document, virtual_path)
        placement_probe = _audit_same_length_placement_edit_probe(payload, document, virtual_path)
        experimental_length_probe = _audit_experimental_length_change_resource_rebuild_probe(payload, document, virtual_path)
        experimental_placement_length_probe = _audit_experimental_length_change_placement_rebuild_probe(payload, document, virtual_path)
        array_count_hint_mutation_probe = _audit_report_only_array_count_hint_mutation_probe(payload, virtual_path)
        transform_word3_mutation_probe = _audit_report_only_transform_word3_mutation_probe(payload, virtual_path)
        reference_word3_mutation_probe = _audit_report_only_reference_word3_mutation_probe(payload, virtual_path)
        preserved_unknown_byte_mutation_probe = _audit_report_only_preserved_unknown_byte_mutation_probe(payload, virtual_path)
        descriptor_word3_mutation_probe = _audit_report_only_descriptor_word3_mutation_probe(payload, virtual_path)
    else:
        edit_probe, placement_probe, experimental_length_probe, experimental_placement_length_probe = _skipped_probe_results(EDIT_PROBES_DISABLED_REASON)
        array_count_hint_mutation_probe = {}
        array_count_hint_mutation_probe.update({'status': 'skipped', 'member_name': ''})
        array_count_hint_mutation_probe.update({'member_type': '', 'descriptor_offset': -1})
        array_count_hint_mutation_probe.update({'old_count_hint': 0, 'new_count_hint': 0})
        array_count_hint_mutation_probe.update({'changed_only_expected_bytes': False, 'layout_fully_accounted_after_edit': False})
        array_count_hint_mutation_probe.update({'no_edit_rebuild_after_edit': False, 'json_no_edit_roundtrip_after_edit': False})
        array_count_hint_mutation_probe.update({'json_layout_rebuild_after_edit': False, 'decoded_count_hint_changed': False})
        array_count_hint_mutation_probe.update({'member_identity_preserved': False, 'semantics_proven': False})
        array_count_hint_mutation_probe.update({'error': EDIT_PROBES_DISABLED_REASON})
        transform_word3_mutation_probe = {}
        transform_word3_mutation_probe.update({'status': 'skipped', 'member_name': ''})
        transform_word3_mutation_probe.update({'member_type': '', 'descriptor_offset': -1})
        transform_word3_mutation_probe.update({'old_word3': 0, 'new_word3': 0})
        transform_word3_mutation_probe.update({'changed_only_expected_bytes': False, 'layout_fully_accounted_after_edit': False})
        transform_word3_mutation_probe.update({'no_edit_rebuild_after_edit': False, 'json_no_edit_roundtrip_after_edit': False})
        transform_word3_mutation_probe.update({'json_layout_rebuild_after_edit': False, 'decoded_word3_changed': False})
        transform_word3_mutation_probe.update({'member_identity_preserved': False, 'semantics_proven': False})
        transform_word3_mutation_probe.update({'error': EDIT_PROBES_DISABLED_REASON})
        reference_word3_mutation_probe = {}
        reference_word3_mutation_probe.update({'status': 'skipped', 'member_name': ''})
        reference_word3_mutation_probe.update({'member_type': '', 'descriptor_offset': -1})
        reference_word3_mutation_probe.update({'old_word3': 0, 'new_word3': 0})
        reference_word3_mutation_probe.update({'changed_only_expected_bytes': False, 'layout_fully_accounted_after_edit': False})
        reference_word3_mutation_probe.update({'no_edit_rebuild_after_edit': False, 'json_no_edit_roundtrip_after_edit': False})
        reference_word3_mutation_probe.update({'json_layout_rebuild_after_edit': False, 'decoded_word3_changed': False})
        reference_word3_mutation_probe.update({'member_identity_preserved': False, 'semantics_proven': False})
        reference_word3_mutation_probe.update({'error': EDIT_PROBES_DISABLED_REASON})
        preserved_unknown_byte_mutation_probe = {}
        preserved_unknown_byte_mutation_probe.update({'status': 'skipped', 'span_index': -1})
        preserved_unknown_byte_mutation_probe.update({'span_start': -1, 'span_end': -1})
        preserved_unknown_byte_mutation_probe.update({'mutation_offset': -1, 'old_byte': 0})
        preserved_unknown_byte_mutation_probe.update({'new_byte': 0, 'changed_only_expected_bytes': False})
        preserved_unknown_byte_mutation_probe.update({'layout_fully_accounted_after_edit': False, 'no_edit_rebuild_after_edit': False})
        preserved_unknown_byte_mutation_probe.update({'json_no_edit_roundtrip_after_edit': False, 'json_layout_rebuild_after_edit': False})
        preserved_unknown_byte_mutation_probe.update({'decoded_byte_changed': False, 'span_identity_preserved': False})
        preserved_unknown_byte_mutation_probe.update({'semantics_proven': False, 'error': EDIT_PROBES_DISABLED_REASON})
        descriptor_word3_mutation_probe = {}
        descriptor_word3_mutation_probe.update({'status': 'skipped', 'member_name': ''})
        descriptor_word3_mutation_probe.update({'member_type': '', 'descriptor_kind': ''})
        descriptor_word3_mutation_probe.update({'descriptor_offset': -1, 'old_word3': 0})
        descriptor_word3_mutation_probe.update({'new_word3': 0, 'changed_only_expected_bytes': False})
        descriptor_word3_mutation_probe.update({'layout_fully_accounted_after_edit': False, 'no_edit_rebuild_after_edit': False})
        descriptor_word3_mutation_probe.update({'json_no_edit_roundtrip_after_edit': False, 'json_layout_rebuild_after_edit': False})
        descriptor_word3_mutation_probe.update({'decoded_word3_changed': False, 'member_identity_preserved': False})
        descriptor_word3_mutation_probe.update({'semantics_proven': False, 'error': EDIT_PROBES_DISABLED_REASON})
    result = {}
    result.update({'array_count_hint_mutation_probe': array_count_hint_mutation_probe, 'descriptor_kind_nonzero_word3_offset_candidate_status_counts': descriptor_kind_nonzero_word3_offset_candidate_status_counts, 'descriptor_kind_nonzero_word3_offset_candidate_target_counts': descriptor_kind_nonzero_word3_offset_candidate_target_counts, 'descriptor_owner_kind_offset_candidate_counts': descriptor_owner_kind_offset_candidate_counts, 'descriptor_owner_kind_offset_candidate_target_counts': descriptor_owner_kind_offset_candidate_target_counts})
    result.update({'descriptor_word3_mutation_probe': descriptor_word3_mutation_probe, 'edit_probe': edit_probe, 'experimental_length_probe': experimental_length_probe, 'experimental_placement_length_probe': experimental_placement_length_probe, 'generic_descriptor_signature_counts': generic_descriptor_signature_counts})
    result.update({'generic_descriptor_signature_offset_candidate_counts': generic_descriptor_signature_offset_candidate_counts, 'generic_descriptor_signature_offset_candidate_target_counts': generic_descriptor_signature_offset_candidate_target_counts, 'generic_nonzero_word3_offset_candidate_status_counts': generic_nonzero_word3_offset_candidate_status_counts, 'generic_nonzero_word3_offset_candidate_target_counts': generic_nonzero_word3_offset_candidate_target_counts, 'offset_candidate_count': offset_candidate_count})
    result.update({'offset_candidate_descriptor_metrics': offset_candidate_descriptor_metrics, 'offset_candidate_metrics': offset_candidate_metrics, 'offset_candidate_outside_descriptor_aligned_isolated_role_kind_counts': offset_candidate_outside_descriptor_aligned_isolated_role_kind_counts, 'offset_candidate_outside_descriptor_aligned_isolated_span_metrics': offset_candidate_outside_descriptor_aligned_isolated_span_metrics, 'offset_candidate_outside_descriptor_metrics': offset_candidate_outside_descriptor_metrics})
    result.update({'offset_candidate_outside_descriptor_mod4_counts': offset_candidate_outside_descriptor_mod4_counts, 'offset_candidate_outside_descriptor_neighbor_byte_class_counts': offset_candidate_outside_descriptor_neighbor_byte_class_counts, 'offset_candidate_outside_descriptor_preserved_middle_metrics': offset_candidate_outside_descriptor_preserved_middle_metrics, 'offset_candidate_outside_descriptor_resource_reference_metrics': offset_candidate_outside_descriptor_resource_reference_metrics, 'offset_candidate_outside_descriptor_target_role_counts': offset_candidate_outside_descriptor_target_role_counts})
    result.update({'offset_candidate_overlap_count': offset_candidate_overlap_count, 'offset_candidate_resource_reference_alignment_target_kind_counts': offset_candidate_resource_reference_alignment_target_kind_counts, 'offset_candidate_resource_reference_alignment_target_kind_extension_counts': offset_candidate_resource_reference_alignment_target_kind_extension_counts, 'offset_candidate_resource_reference_alignment_target_kind_role_counts': offset_candidate_resource_reference_alignment_target_kind_role_counts, 'offset_candidate_resource_reference_alignment_target_kind_span_bucket_counts': offset_candidate_resource_reference_alignment_target_kind_span_bucket_counts})
    result.update({'offset_candidate_resource_reference_alignment_target_kind_span_position_counts': offset_candidate_resource_reference_alignment_target_kind_span_position_counts, 'offset_candidate_resource_reference_mod4_counts': offset_candidate_resource_reference_mod4_counts, 'offset_candidate_resource_reference_neighbor_byte_class_counts': offset_candidate_resource_reference_neighbor_byte_class_counts, 'offset_candidate_resource_reference_span_byte_length_counts': offset_candidate_resource_reference_span_byte_length_counts, 'offset_candidate_resource_reference_span_metrics': offset_candidate_resource_reference_span_metrics})
    result.update({'offset_candidate_resource_reference_target_profile_distance_counts': offset_candidate_resource_reference_target_profile_distance_counts, 'offset_candidate_resource_reference_target_profile_neighbor_byte_class_counts': offset_candidate_resource_reference_target_profile_neighbor_byte_class_counts, 'offset_candidate_resource_reference_target_profile_span_position_counts': offset_candidate_resource_reference_target_profile_span_position_counts, 'offset_candidate_span_metrics': offset_candidate_span_metrics, 'placement_probe': placement_probe})
    result.update({'preserved_span_metrics': preserved_span_metrics, 'preserved_unknown_byte_mutation_probe': preserved_unknown_byte_mutation_probe, 'preserved_unknown_bytes_without_block_semantics': preserved_unknown_bytes_without_block_semantics, 'reference_descriptor_signature_offset_candidate_counts': reference_descriptor_signature_offset_candidate_counts, 'reference_descriptor_signature_offset_candidate_target_counts': reference_descriptor_signature_offset_candidate_target_counts})
    result.update({'reference_descriptor_tail_column_profile_counts': reference_descriptor_tail_column_profile_counts, 'reference_descriptor_tail_numeric_profile_counts': reference_descriptor_tail_numeric_profile_counts, 'reference_descriptor_tail_record_profile_counts': reference_descriptor_tail_record_profile_counts, 'reference_nonzero_word3_offset_candidate_status_counts': reference_nonzero_word3_offset_candidate_status_counts, 'reference_nonzero_word3_offset_candidate_target_counts': reference_nonzero_word3_offset_candidate_target_counts})
    result.update({'reference_word3_mutation_probe': reference_word3_mutation_probe, 'scalar_or_bool_descriptor_signature_counts': scalar_or_bool_descriptor_signature_counts, 'scalar_or_bool_descriptor_signature_offset_candidate_counts': scalar_or_bool_descriptor_signature_offset_candidate_counts, 'scalar_or_bool_descriptor_signature_offset_candidate_target_counts': scalar_or_bool_descriptor_signature_offset_candidate_target_counts, 'scalar_or_bool_nonzero_word3_offset_candidate_status_counts': scalar_or_bool_nonzero_word3_offset_candidate_status_counts})
    result.update({'scalar_or_bool_nonzero_word3_offset_candidate_target_counts': scalar_or_bool_nonzero_word3_offset_candidate_target_counts, 'string_descriptor_signature_counts': string_descriptor_signature_counts, 'string_descriptor_signature_offset_candidate_counts': string_descriptor_signature_offset_candidate_counts, 'string_descriptor_signature_offset_candidate_target_counts': string_descriptor_signature_offset_candidate_target_counts, 'string_nonzero_word3_offset_candidate_status_counts': string_nonzero_word3_offset_candidate_status_counts})
    result.update({'string_nonzero_word3_offset_candidate_target_counts': string_nonzero_word3_offset_candidate_target_counts, 'transform_word3_mutation_probe': transform_word3_mutation_probe})
    return result


def _audit_prefab_json_import_sample_stage_3(state: Mapping[str]) -> dict[str, object]:
    edit_probe, experimental_length_probe, json_rebuilt = (state['edit_probe'], state['experimental_length_probe'], state['json_rebuilt'])
    patched, payload, placement_probe = (state['patched'], state['payload'], state['placement_probe'])
    rebuilt, = (state['rebuilt'],)
    import_ok = patched == payload
    rebuild_ok = rebuilt == payload
    json_rebuild_ok = json_rebuilt == payload
    probe_ok = edit_probe.get('status') in {'passed', 'skipped'} and placement_probe.get('status') in {'passed', 'skipped'} and (experimental_length_probe.get('status') in {'passed', 'skipped'})
    ok = import_ok and rebuild_ok and json_rebuild_ok and probe_ok
    result = {}
    result.update({'import_ok': import_ok, 'json_rebuild_ok': json_rebuild_ok, 'ok': ok, 'rebuild_ok': rebuild_ok})
    return result
