from __future__ import annotations

import json
import math
import struct
import time
from bisect import bisect_right
from copy import deepcopy
from functools import lru_cache
from pathlib import Path
from typing import Callable, Mapping, Optional, Sequence, TypeVar

from cdmw.core.common import raise_if_cancelled
from cdmw.core.archive_attachment_patches import (
    build_prefab_attachment_profile_patch,
    inspect_prefab_attachment_profile_fields,
)
from cdmw.core.crimson_formats import decode_prefab, rebuild_prefab_no_edit
from cdmw.core.prefab_json import (
    PrefabEditJsonError,
    apply_prefab_edit_document,
    build_prefab_edit_document,
    rebuild_prefab_no_edit_from_edit_document,
)
from cdmw.models import ArchiveEntry
from cdmw.core.prefab_corpus_contracts import (
    EDIT_PROBES_DISABLED_REASON,
    NO_SAFE_PLACEMENT_LENGTH_PROBE_REASON,
    NO_SAFE_RESOURCE_LENGTH_PROBE_REASON,
    OVERLAPPING_OFFSET_CANDIDATES_REASON,
    PREFAB_JSON_IMPORT_CORPUS_FORMAT,
    T,
)


def _build_report_summary_part_0(state) -> dict[str, object]:
    result = {}
    result.update({'files_discovered': state['files_discovered']})
    result.update({'files_scanned': len(state['rows'])})
    result.update({'discovery_limit': int(state['discovery_limit']) if state['discovery_limit'] is not None and int(state['discovery_limit']) > 0 else None})
    result.update({'detail_scan_limit': int(state['detail_scan_limit']) if state['detail_scan_limit'] is not None and int(state['detail_scan_limit']) > 0 else None})
    result.update({'scan_offset': max(0, int(state['scan_offset'] or 0))})
    result.update({'scan_count': int(state['scan_count']) if state['scan_count'] is not None and int(state['scan_count']) > 0 else None})
    result.update({'edit_probes_enabled': state['edit_probes_enabled']})
    result.update({'discovery_limited': state['discovery_limited']})
    result.update({'all_discovered_files_scanned': state['all_discovered_files_scanned']})
    result.update({'no_edit_roundtrip_passed': state['passed']})
    result.update({'no_edit_roundtrip_failed': state['failed']})
    result.update({'layout_rebuild_passed': state['layout_rebuild_passed']})
    result.update({'layout_rebuild_failed': state['layout_rebuild_failed']})
    result.update({'json_layout_rebuild_passed': state['json_layout_rebuild_passed']})
    result.update({'json_layout_rebuild_failed': state['json_layout_rebuild_failed']})
    result.update({'prefab_header_versions': dict(sorted(state['header_versions'].items()))})
    result.update({'layout_fully_accounted_files': state['fully_accounted_count']})
    result.update({'parsed_string_bytes': state['parsed_string_byte_count']})
    result.update({'preserved_unknown_bytes': state['preserved_byte_count']})
    result.update({'member_descriptor_preserved_bytes': state['member_descriptor_preserved_byte_count']})
    result.update({'member_descriptor_header_preserved_bytes': state['member_descriptor_header_preserved_byte_count']})
    result.update({'member_descriptor_tail_preserved_bytes': state['member_descriptor_tail_preserved_byte_count']})
    result.update({'preserved_unknown_bytes_excluding_member_descriptors': state['preserved_unknown_byte_count_excluding_member_descriptors']})
    result.update({'preserved_unknown_bytes_excluding_member_descriptor_headers': state['preserved_unknown_byte_count_excluding_member_descriptor_headers']})
    result.update({'preserved_unknown_bytes_without_block_semantics': state['preserved_unknown_bytes_without_block_semantics']})
    result.update({'member_declaration_rows': state['member_declaration_count']})
    result.update({'member_descriptor_bytes': state['member_descriptor_bytes']})
    result.update({'descriptor_tail_member_kind_counts': dict(sorted(state['descriptor_tail_member_kind_counts'].items()))})
    result.update({'descriptor_tail_byte_kind_counts': dict(sorted(state['descriptor_tail_byte_kind_counts'].items()))})
    result.update({'descriptor_tail_member_detail_counts': dict(sorted(state['descriptor_tail_member_detail_counts'].items()))})
    result.update({'transform_member_rows': state['transform_member_count']})
    result.update({'decoded_transform_payload_value_rows': state['decoded_transform_payload_value_rows']})
    result.update({'transform_members_without_payload_values': state['transform_members_without_payload_values']})
    result.update({'transform_members_with_descriptor_tail_bytes': state['transform_members_with_descriptor_tail_bytes']})
    result.update({'transform_descriptor_tail_bytes': state['transform_descriptor_tail_bytes']})
    result.update({'transform_theoretical_payload_member_rows': state['transform_theoretical_payload_member_rows']})
    result.update({'transform_theoretical_payload_byte_count': state['transform_theoretical_payload_byte_count']})
    result.update({'transform_theoretical_payload_exact_preserved_span_rows': state['transform_theoretical_payload_exact_preserved_span_rows']})
    result.update({'transform_theoretical_payload_later_preserved_span_fit_rows': state['transform_theoretical_payload_later_preserved_span_fit_rows']})
    result.update({'transform_theoretical_payload_no_preserved_span_fit_rows': state['transform_theoretical_payload_no_preserved_span_fit_rows']})
    result.update({'transform_theoretical_payload_immediate_window_string_span_overlap_rows': state['transform_theoretical_payload_immediate_window_string_span_overlap_rows']})
    result.update({'transform_theoretical_payload_immediate_window_string_span_overlap_count': state['transform_theoretical_payload_immediate_window_string_span_overlap_count']})
    result.update({'transform_theoretical_payload_immediate_window_string_span_role_counts': dict(sorted(state['transform_theoretical_payload_immediate_window_string_span_role_counts'].items()))})
    result.update({'transform_theoretical_payload_immediate_window_string_span_relation_counts': dict(sorted(state['transform_theoretical_payload_immediate_window_string_span_relation_counts'].items()))})
    result.update({'transform_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows': state['transform_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows']})
    result.update({'transform_theoretical_payload_later_fit_gap_string_span_relation_counts': dict(sorted(state['transform_theoretical_payload_later_fit_gap_string_span_relation_counts'].items()))})
    result.update({'transform_theoretical_payload_later_fit_gap_member_descriptor_relation_counts': dict(sorted(state['transform_theoretical_payload_later_fit_gap_member_descriptor_relation_counts'].items()))})
    result.update({'transform_name_only_member_rows': state['transform_name_only_member_count']})
    result.update({'transform_descriptor_signature_counts': dict(sorted(state['transform_descriptor_signature_counts'].items()))})
    result.update({'transform_descriptor_signature_offset_candidate_counts': dict(sorted(state['transform_descriptor_signature_offset_candidate_counts'].items()))})
    result.update({'transform_nonzero_word3_offset_candidate_status_counts': state['transform_nonzero_word3_offset_candidate_status_counts']})
    result.update({'transform_descriptor_signature_offset_candidate_target_counts': dict(sorted(state['transform_descriptor_signature_offset_candidate_target_counts'].items()))})
    result.update({'transform_nonzero_word3_offset_candidate_target_counts': dict(sorted(state['transform_nonzero_word3_offset_candidate_target_counts'].items()))})
    result.update({'transform_descriptor_word0_value_counts': dict(sorted(state['transform_descriptor_word0_value_counts'].items(), key=lambda item: int(item[0])))})
    result.update({'transform_descriptor_word1_value_counts': dict(sorted(state['transform_descriptor_word1_value_counts'].items(), key=lambda item: int(item[0])))})
    return result


def _build_report_summary_part_1(state) -> dict[str, object]:
    result = {}
    result.update({'transform_descriptor_word2_value_counts': dict(sorted(state['transform_descriptor_word2_value_counts'].items(), key=lambda item: int(item[0])))})
    result.update({'transform_descriptor_word3_value_counts': dict(sorted(state['transform_descriptor_word3_value_counts'].items(), key=lambda item: int(item[0])))})
    result.update({'transform_theoretical_payload_shape_counts': dict(sorted(state['transform_theoretical_payload_shape_counts'].items()))})
    result.update({'array_member_rows': state['array_member_count']})
    result.update({'decoded_array_payload_element_rows': state['decoded_array_payload_element_rows']})
    result.update({'array_members_without_payload_elements': state['array_members_without_payload_elements']})
    result.update({'array_members_with_descriptor_tail_bytes': state['array_members_with_descriptor_tail_bytes']})
    result.update({'array_descriptor_tail_bytes': state['array_descriptor_tail_bytes']})
    result.update({'array_member_stride_hint_rows': state['array_member_stride_hint_count']})
    result.update({'array_member_count_hint_rows': state['array_member_count_hint_count']})
    result.update({'array_descriptor_signature_counts': dict(sorted(state['array_descriptor_signature_counts'].items()))})
    result.update({'array_descriptor_signature_offset_candidate_counts': dict(sorted(state['array_descriptor_signature_offset_candidate_counts'].items()))})
    result.update({'array_descriptor_signature_offset_candidate_target_counts': dict(sorted(state['array_descriptor_signature_offset_candidate_target_counts'].items()))})
    result.update({'array_descriptor_word0_value_counts': dict(sorted(state['array_descriptor_word0_value_counts'].items(), key=lambda item: int(item[0])))})
    result.update({'array_descriptor_word1_value_counts': dict(sorted(state['array_descriptor_word1_value_counts'].items(), key=lambda item: int(item[0])))})
    result.update({'array_descriptor_word2_value_counts': dict(sorted(state['array_descriptor_word2_value_counts'].items(), key=lambda item: int(item[0])))})
    result.update({'array_descriptor_word3_value_counts': dict(sorted(state['array_descriptor_word3_value_counts'].items(), key=lambda item: int(item[0])))})
    result.update({'array_stride_hint_type_counts': dict(sorted(state['array_stride_hint_type_counts'].items()))})
    result.update({'array_count_hint_type_counts': dict(sorted(state['array_count_hint_type_counts'].items()))})
    result.update({'array_count_hint_member_counts': dict(sorted(state['array_count_hint_member_counts'].items()))})
    result.update({'array_word3_relation_counts': dict(sorted(state['array_word3_relation_counts'].items()))})
    result.update({'array_theoretical_payload_shape_counts': dict(sorted(state['array_theoretical_payload_shape_counts'].items()))})
    result.update({'array_theoretical_payload_member_rows': state['array_theoretical_payload_member_rows']})
    result.update({'array_theoretical_payload_byte_count': state['array_theoretical_payload_byte_count']})
    result.update({'array_theoretical_payload_non_tiny_member_rows': state['array_theoretical_payload_non_tiny_member_rows']})
    result.update({'array_theoretical_payload_non_tiny_byte_count': state['array_theoretical_payload_non_tiny_byte_count']})
    result.update({'array_theoretical_payload_exact_preserved_span_rows': state['array_theoretical_payload_exact_preserved_span_rows']})
    result.update({'array_theoretical_payload_later_preserved_span_fit_rows': state['array_theoretical_payload_later_preserved_span_fit_rows']})
    result.update({'array_theoretical_payload_no_preserved_span_fit_rows': state['array_theoretical_payload_no_preserved_span_fit_rows']})
    result.update({'array_theoretical_payload_immediate_window_string_span_overlap_rows': state['array_theoretical_payload_immediate_window_string_span_overlap_rows']})
    result.update({'array_theoretical_payload_immediate_window_string_span_overlap_count': state['array_theoretical_payload_immediate_window_string_span_overlap_count']})
    result.update({'array_theoretical_payload_immediate_window_string_span_role_counts': dict(sorted(state['array_theoretical_payload_immediate_window_string_span_role_counts'].items()))})
    result.update({'array_theoretical_payload_immediate_window_string_span_relation_counts': dict(sorted(state['array_theoretical_payload_immediate_window_string_span_relation_counts'].items()))})
    result.update({'array_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows': state['array_theoretical_payload_later_fit_with_intervening_string_or_declaration_rows']})
    result.update({'array_theoretical_payload_later_fit_gap_string_span_relation_counts': dict(sorted(state['array_theoretical_payload_later_fit_gap_string_span_relation_counts'].items()))})
    result.update({'array_theoretical_payload_later_fit_gap_member_descriptor_relation_counts': dict(sorted(state['array_theoretical_payload_later_fit_gap_member_descriptor_relation_counts'].items()))})
    result.update({'array_word2_delta_member_counts': dict(sorted(state['array_word2_delta_member_counts'].items()))})
    result.update({'array_word2_delta_word3_member_counts': dict(sorted(state['array_word2_delta_word3_member_counts'].items()))})
    result.update({'array_word2_delta_word3_member_offset_candidate_counts': dict(sorted(state['array_word2_delta_word3_member_offset_candidate_counts'].items()))})
    result.update({'array_nonzero_word3_offset_candidate_status_counts': state['array_nonzero_word3_offset_candidate_status_counts']})
    result.update({'array_nonzero_word3_offset_candidate_target_counts': dict(sorted(state['array_nonzero_word3_offset_candidate_target_counts'].items()))})
    result.update({'array_classification_source_counts': state['array_classification_source_counts']})
    result.update({'array_word3_category_counts': state['array_word3_category_counts']})
    result.update({'reference_member_rows': state['reference_member_count']})
    result.update({'reference_members_without_descriptor_semantics': state['reference_members_without_descriptor_semantics']})
    result.update({'reference_members_with_descriptor_tail_bytes': state['reference_members_with_descriptor_tail_bytes']})
    result.update({'reference_descriptor_tail_bytes': state['reference_descriptor_tail_bytes']})
    result.update({'reference_descriptor_signature_counts': dict(sorted(state['reference_descriptor_signature_counts'].items()))})
    result.update({'reference_descriptor_tail_record_shape_counts': dict(sorted(state['reference_descriptor_tail_record_shape_counts'].items()))})
    result.update({'reference_descriptor_tail_offset_candidate_mod_counts': dict(sorted(state['reference_descriptor_tail_offset_candidate_mod_counts'].items()))})
    result.update({'reference_descriptor_tail_record_profile_counts': dict(sorted(state['reference_descriptor_tail_record_profile_counts'].items()))})
    result.update({'reference_descriptor_tail_numeric_profile_counts': dict(sorted(state['reference_descriptor_tail_numeric_profile_counts'].items()))})
    result.update({'reference_descriptor_tail_column_profile_counts': dict(sorted(state['reference_descriptor_tail_column_profile_counts'].items()))})
    result.update({'reference_descriptor_signature_offset_candidate_counts': dict(sorted(state['reference_descriptor_signature_offset_candidate_counts'].items()))})
    result.update({'reference_nonzero_word3_offset_candidate_status_counts': state['reference_nonzero_word3_offset_candidate_status_counts']})
    return result


def _build_report_summary_part_2(state) -> dict[str, object]:
    result = {}
    result.update({'reference_descriptor_signature_offset_candidate_target_counts': dict(sorted(state['reference_descriptor_signature_offset_candidate_target_counts'].items()))})
    result.update({'reference_nonzero_word3_offset_candidate_target_counts': dict(sorted(state['reference_nonzero_word3_offset_candidate_target_counts'].items()))})
    result.update({'scalar_or_bool_descriptor_signature_counts': dict(sorted(state['scalar_or_bool_descriptor_signature_counts'].items()))})
    result.update({'scalar_or_bool_descriptor_signature_offset_candidate_counts': dict(sorted(state['scalar_or_bool_descriptor_signature_offset_candidate_counts'].items()))})
    result.update({'scalar_or_bool_nonzero_word3_offset_candidate_status_counts': state['scalar_or_bool_nonzero_word3_offset_candidate_status_counts']})
    result.update({'scalar_or_bool_descriptor_signature_offset_candidate_target_counts': dict(sorted(state['scalar_or_bool_descriptor_signature_offset_candidate_target_counts'].items()))})
    result.update({'scalar_or_bool_nonzero_word3_offset_candidate_target_counts': dict(sorted(state['scalar_or_bool_nonzero_word3_offset_candidate_target_counts'].items()))})
    result.update({'string_descriptor_signature_counts': dict(sorted(state['string_descriptor_signature_counts'].items()))})
    result.update({'string_descriptor_signature_offset_candidate_counts': dict(sorted(state['string_descriptor_signature_offset_candidate_counts'].items()))})
    result.update({'string_nonzero_word3_offset_candidate_status_counts': state['string_nonzero_word3_offset_candidate_status_counts']})
    result.update({'string_descriptor_signature_offset_candidate_target_counts': dict(sorted(state['string_descriptor_signature_offset_candidate_target_counts'].items()))})
    result.update({'string_nonzero_word3_offset_candidate_target_counts': dict(sorted(state['string_nonzero_word3_offset_candidate_target_counts'].items()))})
    result.update({'generic_descriptor_signature_counts': dict(sorted(state['generic_descriptor_signature_counts'].items()))})
    result.update({'generic_descriptor_signature_offset_candidate_counts': dict(sorted(state['generic_descriptor_signature_offset_candidate_counts'].items()))})
    result.update({'generic_nonzero_word3_offset_candidate_status_counts': state['generic_nonzero_word3_offset_candidate_status_counts']})
    result.update({'generic_descriptor_signature_offset_candidate_target_counts': dict(sorted(state['generic_descriptor_signature_offset_candidate_target_counts'].items()))})
    result.update({'generic_nonzero_word3_offset_candidate_target_counts': dict(sorted(state['generic_nonzero_word3_offset_candidate_target_counts'].items()))})
    result.update({'descriptor_kind_nonzero_word3_offset_candidate_status_counts': state['descriptor_kind_nonzero_word3_offset_candidate_status_counts']})
    result.update({'descriptor_kind_nonzero_word3_offset_candidate_target_counts': dict(sorted(state['descriptor_kind_nonzero_word3_offset_candidate_target_counts'].items()))})
    result.update({'descriptor_owner_kind_offset_candidate_counts': dict(sorted(state['descriptor_owner_kind_offset_candidate_counts'].items()))})
    result.update({'descriptor_owner_kind_offset_candidate_target_counts': dict(sorted(state['descriptor_owner_kind_offset_candidate_target_counts'].items()))})
    result.update({'offset_candidate_rows': state['offset_candidate_count']})
    result.update({'offset_candidate_overlap_rows': state['offset_candidate_overlap_count']})
    result.update({'offset_candidate_aligned_rows': state['offset_candidate_aligned_count']})
    result.update({'offset_candidate_unaligned_rows': state['offset_candidate_unaligned_count']})
    result.update({'offset_candidate_overlap_group_rows': state['offset_candidate_overlap_group_count']})
    result.update({'offset_candidate_overlapping_window_rows': state['offset_candidate_overlapping_window_count']})
    result.update({'offset_candidate_isolated_rows': state['offset_candidate_isolated_count']})
    result.update({'offset_candidate_aligned_isolated_rows': state['offset_candidate_aligned_isolated_count']})
    result.update({'offset_candidate_unaligned_isolated_rows': state['offset_candidate_unaligned_isolated_count']})
    result.update({'offset_candidate_unaligned_or_overlapping_rows': state['offset_candidate_unaligned_or_overlapping_count']})
    result.update({'offset_candidate_target_string_length_prefix_rows': state['offset_candidate_target_string_length_prefix_count']})
    result.update({'offset_candidate_target_string_value_rows': state['offset_candidate_target_string_value_count']})
    result.update({'offset_candidate_target_string_end_rows': state['offset_candidate_target_string_end_count']})
    result.update({'offset_candidate_in_member_descriptor_rows': state['offset_candidate_in_member_descriptor_count']})
    result.update({'offset_candidate_outside_member_descriptor_rows': state['offset_candidate_outside_member_descriptor_count']})
    result.update({'offset_candidate_in_array_descriptor_rows': state['offset_candidate_in_array_descriptor_count']})
    result.update({'offset_candidate_in_transform_descriptor_rows': state['offset_candidate_in_transform_descriptor_count']})
    result.update({'offset_candidate_in_reference_descriptor_rows': state['offset_candidate_in_reference_descriptor_count']})
    result.update({'offset_candidate_in_scalar_or_bool_descriptor_rows': state['offset_candidate_in_scalar_or_bool_descriptor_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_rows': state['offset_candidate_outside_member_descriptor_aligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_rows': state['offset_candidate_outside_member_descriptor_unaligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_overlap_group_rows': state['offset_candidate_outside_member_descriptor_overlap_group_count']})
    result.update({'offset_candidate_outside_member_descriptor_overlapping_window_rows': state['offset_candidate_outside_member_descriptor_overlapping_window_count']})
    result.update({'offset_candidate_outside_member_descriptor_isolated_rows': state['offset_candidate_outside_member_descriptor_isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_isolated_rows': state['offset_candidate_outside_member_descriptor_unaligned_isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_unaligned_or_overlapping_rows': state['offset_candidate_outside_member_descriptor_unaligned_or_overlapping_count']})
    result.update({'offset_candidate_outside_member_descriptor_target_string_length_prefix_rows': state['offset_candidate_outside_member_descriptor_target_string_length_prefix_count']})
    result.update({'offset_candidate_outside_member_descriptor_target_string_value_rows': state['offset_candidate_outside_member_descriptor_target_string_value_count']})
    result.update({'offset_candidate_outside_member_descriptor_target_string_end_rows': state['offset_candidate_outside_member_descriptor_target_string_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_candidate_offset_mod4_counts': state['offset_candidate_outside_member_descriptor_candidate_offset_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_target_value_mod4_counts': state['offset_candidate_outside_member_descriptor_target_value_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_string_value_candidate_offset_mod4_counts': state['offset_candidate_outside_member_descriptor_string_value_candidate_offset_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_string_value_target_value_mod4_counts': state['offset_candidate_outside_member_descriptor_string_value_target_value_mod4_counts']})
    return result


def _build_report_summary_part_3(state) -> dict[str, object]:
    result = {}
    result.update({'offset_candidate_outside_member_descriptor_neighbor_byte_class_counts': state['offset_candidate_outside_member_descriptor_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_target_role_counts': state['offset_candidate_outside_member_descriptor_target_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_string_value_target_role_counts': state['offset_candidate_outside_member_descriptor_string_value_target_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_target_role_kind_counts': state['offset_candidate_outside_member_descriptor_aligned_isolated_target_role_kind_counts']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_outside_preserved_span_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_outside_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_exact_4_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_exact_4_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_le_8_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_preserved_span_le_8_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_start_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_start_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_end_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_at_preserved_span_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_middle_rows': state['offset_candidate_outside_member_descriptor_aligned_isolated_in_preserved_span_middle_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_rows': state['offset_candidate_outside_member_descriptor_resource_reference_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_aligned_rows': state['offset_candidate_outside_member_descriptor_resource_reference_aligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_unaligned_rows': state['offset_candidate_outside_member_descriptor_resource_reference_unaligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_isolated_rows': state['offset_candidate_outside_member_descriptor_resource_reference_isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_unaligned_or_overlapping_rows': state['offset_candidate_outside_member_descriptor_resource_reference_unaligned_or_overlapping_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_length_prefix_rows': state['offset_candidate_outside_member_descriptor_resource_reference_target_string_length_prefix_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_value_rows': state['offset_candidate_outside_member_descriptor_resource_reference_target_string_value_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_string_end_rows': state['offset_candidate_outside_member_descriptor_resource_reference_target_string_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_aligned_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_aligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_unaligned_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_unaligned_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_isolated_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_isolated_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_unaligned_or_overlapping_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_unaligned_or_overlapping_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_length_prefix_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_length_prefix_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_value_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_value_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_end_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_string_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_counts': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_counts': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_span_position_counts': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_span_position_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_neighbor_byte_class_counts': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_span_position_neighbor_byte_class_counts': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_span_position_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_signed_distance_counts': state['offset_candidate_outside_member_descriptor_preserved_span_middle_target_role_kind_signed_distance_counts']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_span_byte_length_counts': state['offset_candidate_outside_member_descriptor_preserved_span_middle_span_byte_length_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_candidate_offset_mod4_counts': state['offset_candidate_outside_member_descriptor_resource_reference_candidate_offset_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_value_mod4_counts': state['offset_candidate_outside_member_descriptor_resource_reference_target_value_mod4_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_neighbor_byte_class_counts': state['offset_candidate_outside_member_descriptor_resource_reference_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_counts': state['offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_extension_counts': state['offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_extension_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_role_counts': state['offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_role_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_span_bucket_counts': state['offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_span_bucket_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_span_position_counts': state['offset_candidate_outside_member_descriptor_resource_reference_alignment_target_kind_span_position_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_profile_span_position_counts': state['offset_candidate_outside_member_descriptor_resource_reference_target_profile_span_position_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_profile_distance_counts': state['offset_candidate_outside_member_descriptor_resource_reference_target_profile_distance_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_target_profile_neighbor_byte_class_counts': state['offset_candidate_outside_member_descriptor_resource_reference_target_profile_neighbor_byte_class_counts']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_in_preserved_span_rows': state['offset_candidate_outside_member_descriptor_resource_reference_in_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_outside_preserved_span_rows': state['offset_candidate_outside_member_descriptor_resource_reference_outside_preserved_span_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_preserved_span_exact_4_rows': state['offset_candidate_outside_member_descriptor_resource_reference_preserved_span_exact_4_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_preserved_span_le_8_rows': state['offset_candidate_outside_member_descriptor_resource_reference_preserved_span_le_8_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_at_preserved_span_start_rows': state['offset_candidate_outside_member_descriptor_resource_reference_at_preserved_span_start_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_at_preserved_span_end_rows': state['offset_candidate_outside_member_descriptor_resource_reference_at_preserved_span_end_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_in_preserved_span_middle_rows': state['offset_candidate_outside_member_descriptor_resource_reference_in_preserved_span_middle_count']})
    result.update({'offset_candidate_outside_member_descriptor_resource_reference_span_byte_length_counts': state['offset_candidate_outside_member_descriptor_resource_reference_span_byte_length_counts']})
    result.update({'offset_candidate_in_preserved_span_rows': state['offset_candidate_in_preserved_span_count']})
    result.update({'offset_candidate_outside_preserved_span_rows': state['offset_candidate_outside_preserved_span_count']})
    result.update({'offset_candidate_preserved_span_exact_4_rows': state['offset_candidate_preserved_span_exact_4_count']})
    return result


def _build_report_summary_part_4(state) -> dict[str, object]:
    result = {}
    result.update({'offset_candidate_preserved_span_le_8_rows': state['offset_candidate_preserved_span_le_8_count']})
    result.update({'offset_candidate_at_preserved_span_start_rows': state['offset_candidate_at_preserved_span_start_count']})
    result.update({'offset_candidate_at_preserved_span_end_rows': state['offset_candidate_at_preserved_span_end_count']})
    result.update({'offset_candidate_in_preserved_span_middle_rows': state['offset_candidate_in_preserved_span_middle_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_exact_4_rows': state['offset_candidate_outside_member_descriptor_preserved_span_exact_4_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_le_8_rows': state['offset_candidate_outside_member_descriptor_preserved_span_le_8_count']})
    result.update({'offset_candidate_outside_member_descriptor_preserved_span_middle_rows': state['offset_candidate_outside_member_descriptor_preserved_span_middle_count']})
    result.update({'largest_preserved_span_bytes': state['largest_preserved_span_byte_count']})
    result.update({'preserved_spans_with_offset_candidates': state['preserved_span_with_offset_candidate_count']})
    result.update({'preserved_spans_without_offset_candidates': state['preserved_span_without_offset_candidate_count']})
    result.update({'preserved_spans_with_member_descriptors': state['preserved_span_with_member_descriptor_count']})
    result.update({'preserved_spans_without_member_descriptors': state['preserved_span_without_member_descriptor_count']})
    result.update({'preserved_spans_with_member_descriptor_headers': state['preserved_span_with_member_descriptor_header_count']})
    result.update({'preserved_spans_with_member_descriptor_tails': state['preserved_span_with_member_descriptor_tail_count']})
    result.update({'editable_reference_rows': state['editable_reference_count']})
    result.update({'editable_placement_field_rows': state['editable_placement_field_count']})
    result.update({'resource_resize_impact_offset_candidate_rows': state['resource_resize_impact_count']})
    result.update({'placement_resize_impact_offset_candidate_rows': state['placement_resize_impact_count']})
    result.update({'resource_resize_impact_target_role_kind_counts': dict(sorted(state['resource_resize_impact_target_role_kind_counts'].items()))})
    result.update({'placement_resize_impact_target_role_kind_counts': dict(sorted(state['placement_resize_impact_target_role_kind_counts'].items()))})
    result.update({'resource_resize_impact_owner_kind_target_counts': dict(sorted(state['resource_resize_impact_owner_kind_target_counts'].items()))})
    result.update({'placement_resize_impact_owner_kind_target_counts': dict(sorted(state['placement_resize_impact_owner_kind_target_counts'].items()))})
    result.update({'resource_resize_impact_resource_reference_target_profile_distance_counts': dict(sorted(state['resource_resize_impact_resource_reference_target_profile_distance_counts'].items()))})
    result.update({'placement_resize_impact_resource_reference_target_profile_distance_counts': dict(sorted(state['placement_resize_impact_resource_reference_target_profile_distance_counts'].items()))})
    result.update({'resource_resize_impact_resource_reference_target_profile_span_position_counts': dict(sorted(state['resource_resize_impact_resource_reference_target_profile_span_position_counts'].items()))})
    result.update({'placement_resize_impact_resource_reference_target_profile_span_position_counts': dict(sorted(state['placement_resize_impact_resource_reference_target_profile_span_position_counts'].items()))})
    result.update({'resource_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts': dict(sorted(state['resource_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts'].items()))})
    result.update({'placement_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts': dict(sorted(state['placement_resize_impact_resource_reference_target_profile_neighbor_byte_class_counts'].items()))})
    result.update({'resource_resize_impact_unique_offset_candidate_rows': state['resource_resize_impact_unique_offset_candidate_count']})
    result.update({'placement_resize_impact_unique_offset_candidate_rows': state['placement_resize_impact_unique_offset_candidate_count']})
    result.update({'resource_resize_impact_unique_target_role_kind_counts': dict(sorted(state['resource_resize_impact_unique_target_role_kind_counts'].items()))})
    result.update({'placement_resize_impact_unique_target_role_kind_counts': dict(sorted(state['placement_resize_impact_unique_target_role_kind_counts'].items()))})
    result.update({'resource_resize_impact_unique_owner_kind_target_counts': dict(sorted(state['resource_resize_impact_unique_owner_kind_target_counts'].items()))})
    result.update({'placement_resize_impact_unique_owner_kind_target_counts': dict(sorted(state['placement_resize_impact_unique_owner_kind_target_counts'].items()))})
    result.update({'resource_resize_impact_unique_candidate_profile_counts': dict(sorted(state['resource_resize_impact_unique_candidate_profile_counts'].items()))})
    result.update({'placement_resize_impact_unique_candidate_profile_counts': dict(sorted(state['placement_resize_impact_unique_candidate_profile_counts'].items()))})
    result.update({'resource_resize_impact_unique_overlap_profile_counts': dict(sorted(state['resource_resize_impact_unique_overlap_profile_counts'].items()))})
    result.update({'placement_resize_impact_unique_overlap_profile_counts': dict(sorted(state['placement_resize_impact_unique_overlap_profile_counts'].items()))})
    result.update({'resource_resize_impact_unique_overlap_group_profile_counts': dict(sorted(state['resource_resize_impact_unique_overlap_group_profile_counts'].items()))})
    result.update({'placement_resize_impact_unique_overlap_group_profile_counts': dict(sorted(state['placement_resize_impact_unique_overlap_group_profile_counts'].items()))})
    result.update({'resource_resize_impact_unique_overlap_group_target_identity_counts': dict(sorted(state['resource_resize_impact_unique_overlap_group_target_identity_counts'].items()))})
    result.update({'placement_resize_impact_unique_overlap_group_target_identity_counts': dict(sorted(state['placement_resize_impact_unique_overlap_group_target_identity_counts'].items()))})
    result.update({'resource_resize_impact_unique_same_target_overlap_collapse_counts': dict(sorted(state['resource_resize_impact_unique_same_target_overlap_collapse_counts'].items()))})
    result.update({'placement_resize_impact_unique_same_target_overlap_collapse_counts': dict(sorted(state['placement_resize_impact_unique_same_target_overlap_collapse_counts'].items()))})
    result.update({'resource_resize_impact_unique_same_target_overlap_shift_conflict_counts': dict(sorted(state['resource_resize_impact_unique_same_target_overlap_shift_conflict_counts'].items()))})
    result.update({'placement_resize_impact_unique_same_target_overlap_shift_conflict_counts': dict(sorted(state['placement_resize_impact_unique_same_target_overlap_shift_conflict_counts'].items()))})
    result.update({'resource_resize_impact_unique_same_target_shift_conflict_group_detail_counts': dict(sorted(state['resource_resize_impact_unique_same_target_shift_conflict_group_detail_counts'].items()))})
    result.update({'placement_resize_impact_unique_same_target_shift_conflict_group_detail_counts': dict(sorted(state['placement_resize_impact_unique_same_target_shift_conflict_group_detail_counts'].items()))})
    result.update({'resource_resize_impact_unique_same_target_resource_alias_counts': dict(sorted(state['resource_resize_impact_unique_same_target_resource_alias_counts'].items()))})
    result.update({'placement_resize_impact_unique_same_target_resource_alias_counts': dict(sorted(state['placement_resize_impact_unique_same_target_resource_alias_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_shift_conflict_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_overlap_shift_conflict_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_shift_conflict_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_overlap_shift_conflict_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_profile_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_shift_consistent_profile_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_profile_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_shift_consistent_profile_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_identity_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_shift_consistent_identity_counts'].items()))})
    return result


def _build_report_summary_part_5(state) -> dict[str, object]:
    result = {}
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_identity_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_shift_consistent_identity_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_shape_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_shift_consistent_shape_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_shape_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_shift_consistent_shape_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_shift_consistent_group_detail_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_shift_consistent_metadata_collision_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_blocker_profile_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_overlap_blocker_profile_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_blocker_profile_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_overlap_blocker_profile_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_overlap_impacted_identity_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_overlap_impacted_identity_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary': dict(sorted(state['resource_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary': dict(sorted(state['placement_resize_impact_unique_mixed_target_overlap_impacted_identity_repeat_summary'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_collapse_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_profile_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_identity_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_role_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_group_detail_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_metadata_collision_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_resource_reference_nonimpacted_reference_collision_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_high_repeat_identity_remaining_shape_counts'].items()))})
    result.update({'resource_resize_impact_unique_mixed_target_overlap_impacted_shape_counts': dict(sorted(state['resource_resize_impact_unique_mixed_target_overlap_impacted_shape_counts'].items()))})
    result.update({'placement_resize_impact_unique_mixed_target_overlap_impacted_shape_counts': dict(sorted(state['placement_resize_impact_unique_mixed_target_overlap_impacted_shape_counts'].items()))})
    result.update({'resource_resize_impact_unique_resource_reference_target_profile_distance_counts': dict(sorted(state['resource_resize_impact_unique_resource_reference_target_profile_distance_counts'].items()))})
    result.update({'placement_resize_impact_unique_resource_reference_target_profile_distance_counts': dict(sorted(state['placement_resize_impact_unique_resource_reference_target_profile_distance_counts'].items()))})
    result.update({'resource_resize_impact_unique_overlap_counts': dict(sorted(state['resource_resize_impact_unique_overlap_counts'].items()))})
    result.update({'placement_resize_impact_unique_overlap_counts': dict(sorted(state['placement_resize_impact_unique_overlap_counts'].items()))})
    result.update({'resource_resize_impact_unique_resource_reference_overlap_counts': dict(sorted(state['resource_resize_impact_unique_resource_reference_overlap_counts'].items()))})
    result.update({'placement_resize_impact_unique_resource_reference_overlap_counts': dict(sorted(state['placement_resize_impact_unique_resource_reference_overlap_counts'].items()))})
    result.update({'length_change_tail_only_candidate_rows': state['length_change_tail_only_candidate_count']})
    result.update({'length_change_downstream_rebuild_rows': state['length_change_downstream_rebuild_row_count']})
    result.update({'length_change_offset_rebuild_rows': state['length_change_offset_rebuild_row_count']})
    result.update({'policy_resize_readiness_editable_rows': state['policy_resize_readiness_editable_rows']})
    result.update({'policy_resize_readiness_impacted_rows': state['policy_resize_readiness_impacted_rows']})
    result.update({'policy_resize_readiness_offset_candidate_rows': state['policy_resize_readiness_offset_candidate_rows']})
    result.update({'policy_length_changing_ready_files': state['policy_length_changing_ready_files']})
    result.update({'files_with_editable_references': state['files_with_editable_references']})
    result.update({'files_with_editable_placement_fields': state['files_with_editable_placement_fields']})
    result.update({'files_with_offset_candidates': state['files_with_offset_candidates']})
    result.update({'files_with_offset_candidate_overlaps': state['files_with_offset_candidate_overlaps']})
    result.update({'files_with_policy_resize_impacts': state['files_with_policy_resize_impacts']})
    result.update({'same_length_resource_edit_probe_passed': state['same_length_probe_passed']})
    result.update({'same_length_resource_edit_probe_skipped': state['same_length_probe_skipped']})
    result.update({'same_length_resource_edit_probe_failed': state['same_length_probe_failed']})
    result.update({'same_length_resource_edit_probe_rows_patched': state['same_length_probe_edited_rows']})
    result.update({'same_length_placement_edit_probe_passed': state['placement_probe_passed']})
    result.update({'same_length_placement_edit_probe_skipped': state['placement_probe_skipped']})
    return result


def _build_report_summary_part_6(state) -> dict[str, object]:
    result = {}
    result.update({'same_length_placement_edit_probe_failed': state['placement_probe_failed']})
    result.update({'same_length_placement_edit_probe_rows_patched': state['placement_probe_edited_rows']})
    result.update({'experimental_length_change_resource_rebuild_probe_passed': state['experimental_length_probe_passed']})
    result.update({'experimental_length_change_resource_rebuild_probe_skipped': state['experimental_length_probe_skipped']})
    result.update({'experimental_length_change_resource_rebuild_probe_failed': state['experimental_length_probe_failed']})
    result.update({'experimental_length_change_resource_rebuild_probe_rows_patched': state['experimental_length_probe_edited_rows']})
    result.update({'experimental_length_change_resource_rebuild_probe_byte_delta': state['experimental_length_probe_byte_delta']})
    result.update({'experimental_length_change_resource_rebuild_probe_offset_candidate_rows_after_edit': state['experimental_length_probe_offset_candidates']})
    result.update({'experimental_length_change_resource_rebuild_probe_offset_remap_passed': state['experimental_length_probe_offset_remap_passed']})
    result.update({'experimental_length_change_resource_rebuild_probe_effective_offset_remap_passed': state['experimental_length_probe_effective_offset_remap_passed']})
    result.update({'experimental_length_change_resource_rebuild_probe_changed_only_expected_passed': state['experimental_length_probe_changed_only_expected_passed']})
    result.update({'experimental_length_change_resource_rebuild_probe_changed_only_effective_expected_passed': state['experimental_length_probe_changed_only_effective_expected_passed']})
    result.update({'experimental_length_change_resource_rebuild_probe_report_only_effective_remap_status_counts': state['experimental_length_probe_report_only_effective_remap_status_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_status_effective_remap_status_counts': state['experimental_length_probe_status_effective_remap_status_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_status_effective_expected_counts': state['experimental_length_probe_status_effective_expected_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_offset_remap_missing_count': state['experimental_length_probe_offset_remap_missing_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_after_effective_offset_remap_exclusion': state['experimental_length_probe_missing_after_effective_exclusion']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_unshifted_value_at_expected_offset_count': state['experimental_length_probe_missing_unshifted_value_at_expected_offset_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_shifted_value_at_expected_offset_count': state['experimental_length_probe_missing_shifted_value_at_expected_offset_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_other_value_at_expected_offset_count': state['experimental_length_probe_missing_other_value_at_expected_offset_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_out_of_bounds_expected_offset_count': state['experimental_length_probe_missing_out_of_bounds_expected_offset_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_unshifted_owner_kind_target_role_kind_counts': state['experimental_length_probe_missing_unshifted_owner_kind_target_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_non_metadata_resource_reference_extension_counts': state['experimental_length_probe_missing_non_metadata_resource_reference_extension_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_non_metadata_resource_reference_target_kind_extension_counts': state['experimental_length_probe_missing_non_metadata_resource_reference_target_kind_extension_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_missing_non_metadata_resource_reference_target_name_top_counts': state['experimental_length_probe_missing_non_metadata_resource_reference_target_name_top_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_offset_candidate_count': state['experimental_length_probe_selected_offset_candidate_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_non_overlapping_count': state['experimental_length_probe_selected_non_overlapping_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_overlapping_count': state['experimental_length_probe_selected_overlapping_count']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_target_role_kind_counts': state['experimental_length_probe_selected_target_role_kind_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_owner_kind_target_counts': state['experimental_length_probe_selected_owner_kind_target_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_same_target_overlap_shift_conflict_counts': state['experimental_length_probe_selected_same_target_shift_conflict_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_same_target_overlap_shift_conflict_profile_counts': state['experimental_length_probe_selected_same_target_shift_conflict_profile_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_same_target_resource_alias_counts': state['experimental_length_probe_selected_same_target_resource_alias_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_mixed_target_overlap_shift_conflict_counts': state['experimental_length_probe_selected_mixed_target_shift_conflict_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_mixed_target_overlap_shift_conflict_profile_counts': state['experimental_length_probe_selected_mixed_target_shift_conflict_profile_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_selected_mixed_target_resource_reference_group_detail_counts': state['experimental_length_probe_selected_mixed_target_resource_reference_group_detail_counts']})
    result.update({'experimental_length_change_resource_rebuild_probe_skip_reasons': state['experimental_length_probe_skip_reasons']})
    result.update({'experimental_length_change_resource_rebuild_probe_failure_reasons': state['experimental_length_probe_failure_reasons']})
    result.update({'experimental_length_change_placement_rebuild_probe_passed': state['experimental_placement_length_probe_passed']})
    result.update({'experimental_length_change_placement_rebuild_probe_skipped': state['experimental_placement_length_probe_skipped']})
    result.update({'experimental_length_change_placement_rebuild_probe_failed': state['experimental_placement_length_probe_failed']})
    result.update({'experimental_length_change_placement_rebuild_probe_rows_patched': state['experimental_placement_length_probe_edited_rows']})
    result.update({'experimental_length_change_placement_rebuild_probe_byte_delta': state['experimental_placement_length_probe_byte_delta']})
    result.update({'experimental_length_change_placement_rebuild_probe_offset_candidate_rows_after_edit': state['experimental_placement_length_probe_offset_candidates']})
    result.update({'experimental_length_change_placement_rebuild_probe_offset_remap_passed': state['experimental_placement_length_probe_offset_remap_passed']})
    result.update({'experimental_length_change_placement_rebuild_probe_effective_offset_remap_passed': state['experimental_placement_length_probe_effective_offset_remap_passed']})
    result.update({'experimental_length_change_placement_rebuild_probe_changed_only_expected_passed': state['experimental_placement_length_probe_changed_only_expected_passed']})
    result.update({'experimental_length_change_placement_rebuild_probe_changed_only_effective_expected_passed': state['experimental_placement_length_probe_changed_only_effective_expected_passed']})
    result.update({'experimental_length_change_placement_rebuild_probe_report_only_effective_remap_status_counts': state['experimental_placement_length_probe_report_only_effective_remap_status_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_status_effective_remap_status_counts': state['experimental_placement_length_probe_status_effective_remap_status_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_status_effective_expected_counts': state['experimental_placement_length_probe_status_effective_expected_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_offset_remap_missing_count': state['experimental_placement_length_probe_offset_remap_missing_count']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_after_effective_offset_remap_exclusion': state['experimental_placement_length_probe_missing_after_effective_exclusion']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_unshifted_value_at_expected_offset_count': state['experimental_placement_length_probe_missing_unshifted_value_at_expected_offset_count']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_shifted_value_at_expected_offset_count': state['experimental_placement_length_probe_missing_shifted_value_at_expected_offset_count']})
    return result


def _build_report_summary_part_7(state) -> dict[str, object]:
    result = {}
    result.update({'experimental_length_change_placement_rebuild_probe_missing_other_value_at_expected_offset_count': state['experimental_placement_length_probe_missing_other_value_at_expected_offset_count']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_out_of_bounds_expected_offset_count': state['experimental_placement_length_probe_missing_out_of_bounds_expected_offset_count']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_unshifted_owner_kind_target_role_kind_counts': state['experimental_placement_length_probe_missing_unshifted_owner_kind_target_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_non_metadata_resource_reference_extension_counts': state['experimental_placement_length_probe_missing_non_metadata_resource_reference_extension_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_non_metadata_resource_reference_target_kind_extension_counts': state['experimental_placement_length_probe_missing_non_metadata_resource_reference_target_kind_extension_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_missing_non_metadata_resource_reference_target_name_top_counts': state['experimental_placement_length_probe_missing_non_metadata_resource_reference_target_name_top_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_offset_candidate_count': state['experimental_placement_length_probe_selected_offset_candidate_count']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_non_overlapping_count': state['experimental_placement_length_probe_selected_non_overlapping_count']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_overlapping_count': state['experimental_placement_length_probe_selected_overlapping_count']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_target_role_kind_counts': state['experimental_placement_length_probe_selected_target_role_kind_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_owner_kind_target_counts': state['experimental_placement_length_probe_selected_owner_kind_target_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_same_target_overlap_shift_conflict_counts': state['experimental_placement_length_probe_selected_same_target_shift_conflict_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_same_target_overlap_shift_conflict_profile_counts': state['experimental_placement_length_probe_selected_same_target_shift_conflict_profile_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_same_target_resource_alias_counts': state['experimental_placement_length_probe_selected_same_target_resource_alias_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_mixed_target_overlap_shift_conflict_counts': state['experimental_placement_length_probe_selected_mixed_target_shift_conflict_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_mixed_target_overlap_shift_conflict_profile_counts': state['experimental_placement_length_probe_selected_mixed_target_shift_conflict_profile_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_selected_mixed_target_resource_reference_group_detail_counts': state['experimental_placement_length_probe_selected_mixed_target_resource_reference_group_detail_counts']})
    result.update({'experimental_length_change_placement_rebuild_probe_skip_reasons': state['experimental_placement_length_probe_skip_reasons']})
    result.update({'experimental_length_change_placement_rebuild_probe_failure_reasons': state['experimental_placement_length_probe_failure_reasons']})
    result.update({'report_only_array_count_hint_mutation_probe_passed': state['array_count_hint_mutation_probe_passed']})
    result.update({'report_only_array_count_hint_mutation_probe_skipped': state['array_count_hint_mutation_probe_skipped']})
    result.update({'report_only_array_count_hint_mutation_probe_failed': state['array_count_hint_mutation_probe_failed']})
    result.update({'report_only_array_count_hint_mutation_probe_changed_only_expected_passed': state['array_count_hint_mutation_probe_changed_only_expected_passed']})
    result.update({'report_only_array_count_hint_mutation_probe_layout_fully_accounted_passed': state['array_count_hint_mutation_probe_layout_fully_accounted_passed']})
    result.update({'report_only_array_count_hint_mutation_probe_no_edit_rebuild_passed': state['array_count_hint_mutation_probe_no_edit_rebuild_passed']})
    result.update({'report_only_array_count_hint_mutation_probe_json_no_edit_roundtrip_passed': state['array_count_hint_mutation_probe_json_no_edit_roundtrip_passed']})
    result.update({'report_only_array_count_hint_mutation_probe_json_layout_rebuild_passed': state['array_count_hint_mutation_probe_json_layout_rebuild_passed']})
    result.update({'report_only_array_count_hint_mutation_probe_decoded_count_hint_changed': state['array_count_hint_mutation_probe_decoded_count_hint_changed']})
    result.update({'report_only_array_count_hint_mutation_probe_member_identity_preserved': state['array_count_hint_mutation_probe_member_identity_preserved']})
    result.update({'report_only_array_count_hint_mutation_probe_semantics_proven': state['array_count_hint_mutation_probe_semantics_proven']})
    result.update({'report_only_array_count_hint_mutation_probe_status_semantics_proven_counts': state['array_count_hint_mutation_probe_status_semantics_proven_counts']})
    result.update({'report_only_array_count_hint_mutation_probe_member_counts': state['array_count_hint_mutation_probe_member_counts']})
    result.update({'report_only_array_count_hint_mutation_probe_type_counts': state['array_count_hint_mutation_probe_type_counts']})
    result.update({'report_only_array_count_hint_mutation_probe_skip_reasons': state['array_count_hint_mutation_probe_skip_reasons']})
    result.update({'report_only_array_count_hint_mutation_probe_failure_reasons': state['array_count_hint_mutation_probe_failure_reasons']})
    result.update({'report_only_transform_word3_mutation_probe_passed': state['transform_word3_mutation_probe_passed']})
    result.update({'report_only_transform_word3_mutation_probe_skipped': state['transform_word3_mutation_probe_skipped']})
    result.update({'report_only_transform_word3_mutation_probe_failed': state['transform_word3_mutation_probe_failed']})
    result.update({'report_only_transform_word3_mutation_probe_changed_only_expected_passed': state['transform_word3_mutation_probe_changed_only_expected_passed']})
    result.update({'report_only_transform_word3_mutation_probe_layout_fully_accounted_passed': state['transform_word3_mutation_probe_layout_fully_accounted_passed']})
    result.update({'report_only_transform_word3_mutation_probe_no_edit_rebuild_passed': state['transform_word3_mutation_probe_no_edit_rebuild_passed']})
    result.update({'report_only_transform_word3_mutation_probe_json_no_edit_roundtrip_passed': state['transform_word3_mutation_probe_json_no_edit_roundtrip_passed']})
    result.update({'report_only_transform_word3_mutation_probe_json_layout_rebuild_passed': state['transform_word3_mutation_probe_json_layout_rebuild_passed']})
    result.update({'report_only_transform_word3_mutation_probe_decoded_word3_changed': state['transform_word3_mutation_probe_decoded_word3_changed']})
    result.update({'report_only_transform_word3_mutation_probe_member_identity_preserved': state['transform_word3_mutation_probe_member_identity_preserved']})
    result.update({'report_only_transform_word3_mutation_probe_semantics_proven': state['transform_word3_mutation_probe_semantics_proven']})
    result.update({'report_only_transform_word3_mutation_probe_status_semantics_proven_counts': state['transform_word3_mutation_probe_status_semantics_proven_counts']})
    result.update({'report_only_transform_word3_mutation_probe_member_counts': state['transform_word3_mutation_probe_member_counts']})
    result.update({'report_only_transform_word3_mutation_probe_type_counts': state['transform_word3_mutation_probe_type_counts']})
    result.update({'report_only_transform_word3_mutation_probe_skip_reasons': state['transform_word3_mutation_probe_skip_reasons']})
    result.update({'report_only_transform_word3_mutation_probe_failure_reasons': state['transform_word3_mutation_probe_failure_reasons']})
    result.update({'report_only_reference_word3_mutation_probe_passed': state['reference_word3_mutation_probe_passed']})
    result.update({'report_only_reference_word3_mutation_probe_skipped': state['reference_word3_mutation_probe_skipped']})
    result.update({'report_only_reference_word3_mutation_probe_failed': state['reference_word3_mutation_probe_failed']})
    result.update({'report_only_reference_word3_mutation_probe_changed_only_expected_passed': state['reference_word3_mutation_probe_changed_only_expected_passed']})
    return result


def _build_report_summary_part_8(state) -> dict[str, object]:
    result = {}
    result.update({'report_only_reference_word3_mutation_probe_layout_fully_accounted_passed': state['reference_word3_mutation_probe_layout_fully_accounted_passed']})
    result.update({'report_only_reference_word3_mutation_probe_no_edit_rebuild_passed': state['reference_word3_mutation_probe_no_edit_rebuild_passed']})
    result.update({'report_only_reference_word3_mutation_probe_json_no_edit_roundtrip_passed': state['reference_word3_mutation_probe_json_no_edit_roundtrip_passed']})
    result.update({'report_only_reference_word3_mutation_probe_json_layout_rebuild_passed': state['reference_word3_mutation_probe_json_layout_rebuild_passed']})
    result.update({'report_only_reference_word3_mutation_probe_decoded_word3_changed': state['reference_word3_mutation_probe_decoded_word3_changed']})
    result.update({'report_only_reference_word3_mutation_probe_member_identity_preserved': state['reference_word3_mutation_probe_member_identity_preserved']})
    result.update({'report_only_reference_word3_mutation_probe_semantics_proven': state['reference_word3_mutation_probe_semantics_proven']})
    result.update({'report_only_reference_word3_mutation_probe_status_semantics_proven_counts': state['reference_word3_mutation_probe_status_semantics_proven_counts']})
    result.update({'report_only_reference_word3_mutation_probe_member_counts': state['reference_word3_mutation_probe_member_counts']})
    result.update({'report_only_reference_word3_mutation_probe_type_counts': state['reference_word3_mutation_probe_type_counts']})
    result.update({'report_only_reference_word3_mutation_probe_skip_reasons': state['reference_word3_mutation_probe_skip_reasons']})
    result.update({'report_only_reference_word3_mutation_probe_failure_reasons': state['reference_word3_mutation_probe_failure_reasons']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_passed': state['preserved_unknown_byte_mutation_probe_passed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_skipped': state['preserved_unknown_byte_mutation_probe_skipped']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_failed': state['preserved_unknown_byte_mutation_probe_failed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_changed_only_expected_passed': state['preserved_unknown_byte_mutation_probe_changed_only_expected_passed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_layout_fully_accounted_passed': state['preserved_unknown_byte_mutation_probe_layout_fully_accounted_passed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_no_edit_rebuild_passed': state['preserved_unknown_byte_mutation_probe_no_edit_rebuild_passed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_json_no_edit_roundtrip_passed': state['preserved_unknown_byte_mutation_probe_json_no_edit_roundtrip_passed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_json_layout_rebuild_passed': state['preserved_unknown_byte_mutation_probe_json_layout_rebuild_passed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_decoded_byte_changed': state['preserved_unknown_byte_mutation_probe_decoded_byte_changed']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_span_identity_preserved': state['preserved_unknown_byte_mutation_probe_span_identity_preserved']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_semantics_proven': state['preserved_unknown_byte_mutation_probe_semantics_proven']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_status_semantics_proven_counts': state['preserved_unknown_byte_mutation_probe_status_semantics_proven_counts']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_skip_reasons': state['preserved_unknown_byte_mutation_probe_skip_reasons']})
    result.update({'report_only_preserved_unknown_byte_mutation_probe_failure_reasons': state['preserved_unknown_byte_mutation_probe_failure_reasons']})
    result.update({'report_only_descriptor_word3_mutation_probe_passed': state['descriptor_word3_mutation_probe_passed']})
    result.update({'report_only_descriptor_word3_mutation_probe_skipped': state['descriptor_word3_mutation_probe_skipped']})
    result.update({'report_only_descriptor_word3_mutation_probe_failed': state['descriptor_word3_mutation_probe_failed']})
    result.update({'report_only_descriptor_word3_mutation_probe_changed_only_expected_passed': state['descriptor_word3_mutation_probe_changed_only_expected_passed']})
    result.update({'report_only_descriptor_word3_mutation_probe_layout_fully_accounted_passed': state['descriptor_word3_mutation_probe_layout_fully_accounted_passed']})
    result.update({'report_only_descriptor_word3_mutation_probe_no_edit_rebuild_passed': state['descriptor_word3_mutation_probe_no_edit_rebuild_passed']})
    result.update({'report_only_descriptor_word3_mutation_probe_json_no_edit_roundtrip_passed': state['descriptor_word3_mutation_probe_json_no_edit_roundtrip_passed']})
    result.update({'report_only_descriptor_word3_mutation_probe_json_layout_rebuild_passed': state['descriptor_word3_mutation_probe_json_layout_rebuild_passed']})
    result.update({'report_only_descriptor_word3_mutation_probe_decoded_word3_changed': state['descriptor_word3_mutation_probe_decoded_word3_changed']})
    result.update({'report_only_descriptor_word3_mutation_probe_member_identity_preserved': state['descriptor_word3_mutation_probe_member_identity_preserved']})
    result.update({'report_only_descriptor_word3_mutation_probe_semantics_proven': state['descriptor_word3_mutation_probe_semantics_proven']})
    result.update({'report_only_descriptor_word3_mutation_probe_status_semantics_proven_counts': state['descriptor_word3_mutation_probe_status_semantics_proven_counts']})
    result.update({'report_only_descriptor_word3_mutation_probe_kind_counts': state['descriptor_word3_mutation_probe_kind_counts']})
    result.update({'report_only_descriptor_word3_mutation_probe_member_counts': state['descriptor_word3_mutation_probe_member_counts']})
    result.update({'report_only_descriptor_word3_mutation_probe_type_counts': state['descriptor_word3_mutation_probe_type_counts']})
    result.update({'report_only_descriptor_word3_mutation_probe_skip_reasons': state['descriptor_word3_mutation_probe_skip_reasons']})
    result.update({'report_only_descriptor_word3_mutation_probe_failure_reasons': state['descriptor_word3_mutation_probe_failure_reasons']})
    return result


def _build_report_summary(state) -> dict[str, object]:
    result: dict[str, object] = {}
    result.update(_build_report_summary_part_0(state))
    result.update(_build_report_summary_part_1(state))
    result.update(_build_report_summary_part_2(state))
    result.update(_build_report_summary_part_3(state))
    result.update(_build_report_summary_part_4(state))
    result.update(_build_report_summary_part_5(state))
    result.update(_build_report_summary_part_6(state))
    result.update(_build_report_summary_part_7(state))
    result.update(_build_report_summary_part_8(state))
    return result
