"""Pure mesh-domain session and validation rules."""

from __future__ import annotations

from .editing import (
    MESH_EDIT_ACTIONS,
    MESH_EDIT_MODES,
    MeshEditCommand,
    MeshEditHistoryEntry,
    MeshEditResult,
    MeshEditSelection,
    MeshEditSessionView,
)
from .material_resource_policy import (
    MeshMaterialResourcePolicy,
    canonical_material_channel,
    mesh_material_resource_policy,
)
from .asset import (
    BinaryLayout,
    IndexBuffer,
    MaterialSlot,
    MeshAsset,
    MeshAssetSubmesh,
    MeshFileSection,
    MeshLod,
    MeshValidationIssue,
    MeshValidationResult,
    MeshVertex,
    VertexBuffer,
    validate_mesh_asset_rebuild,
)
from .compare import MeshBoundsSummary, MeshCompareSummary, MeshPartCompareSummary, compare_meshes
from .export_validation import (
    DEVELOPER_OVERRIDABLE_REBUILD_BLOCKERS,
    SUPPORTED_GAME_MESH_FORMATS,
    MeshExportValidationIssue,
    MeshExportValidationReport,
    validate_mesh_export,
)
from .operations import (
    BLOCKED_MESH_EDIT_OPERATIONS,
    SAFE_MESH_EDIT_OPERATIONS,
    MeshEditOperation,
    MeshEditOperationIssue,
    mesh_edit_operation_changed_channel,
    mesh_edit_operations_from_dicts,
    mesh_edit_operations_to_dicts,
    validate_mesh_edit_operation_coverage,
    validate_mesh_edit_operations,
)
from .parts import MeshPartSummary, MeshWorkspaceSummary, summarize_mesh_workspace
from .skeleton import (
    MeshAnimationClip,
    MeshAnimationKeyframe,
    MeshAnimationPlaybackSummary,
    MeshAnimationSequenceSegment,
    MeshAnimationTrack,
    MeshAuthoringStatusRow,
    MeshConstraintEvidenceSummary,
    MeshSkeletonBoneSummary,
    MeshSkeletonPoseSummary,
    MeshSkeletonSummary,
    MeshSkinningPartSummary,
    MeshVertexWeightSummary,
    mesh_animation_clip_from_document,
    mesh_pose_deformed_vertices,
    sample_mesh_animation_pose,
    summarize_mesh_animation_playback,
    summarize_mesh_skinning,
    summarize_skeleton_bones,
)
from .textures import MeshTextureEditTarget, selected_mesh_texture_edit_target
from .uv import MeshUvIslandSummary, MeshUvSummary, mesh_uv_lasso_selection, mesh_uv_region_selection, summarize_mesh_uvs

__all__ = [
    "MESH_EDIT_ACTIONS",
    "MESH_EDIT_MODES",
    "MeshEditCommand",
    "MeshEditHistoryEntry",
    "MeshEditResult",
    "MeshEditSelection",
    "MeshEditSessionView",
    "MeshMaterialResourcePolicy",
    "canonical_material_channel",
    "mesh_material_resource_policy",
    "MeshEditOperation",
    "MeshEditOperationIssue",
    "BinaryLayout",
    "IndexBuffer",
    "MaterialSlot",
    "MeshAsset",
    "MeshAssetSubmesh",
    "MeshFileSection",
    "MeshLod",
    "MeshValidationIssue",
    "MeshValidationResult",
    "MeshVertex",
    "VertexBuffer",
    "MeshBoundsSummary",
    "MeshCompareSummary",
    "MeshExportValidationIssue",
    "MeshExportValidationReport",
    "MeshPartSummary",
    "MeshPartCompareSummary",
    "MeshAnimationClip",
    "MeshAnimationKeyframe",
    "MeshAnimationPlaybackSummary",
    "MeshAnimationSequenceSegment",
    "MeshAnimationTrack",
    "MeshAuthoringStatusRow",
    "MeshConstraintEvidenceSummary",
    "MeshSkeletonBoneSummary",
    "MeshSkeletonPoseSummary",
    "MeshSkeletonSummary",
    "MeshSkinningPartSummary",
    "MeshVertexWeightSummary",
    "mesh_animation_clip_from_document",
    "mesh_pose_deformed_vertices",
    "MeshTextureEditTarget",
    "MeshUvIslandSummary",
    "MeshUvSummary",
    "MeshWorkspaceSummary",
    "DEVELOPER_OVERRIDABLE_REBUILD_BLOCKERS",
    "SUPPORTED_GAME_MESH_FORMATS",
    "SAFE_MESH_EDIT_OPERATIONS",
    "BLOCKED_MESH_EDIT_OPERATIONS",
    "compare_meshes",
    "selected_mesh_texture_edit_target",
    "mesh_uv_lasso_selection",
    "mesh_uv_region_selection",
    "sample_mesh_animation_pose",
    "summarize_mesh_animation_playback",
    "summarize_mesh_skinning",
    "summarize_skeleton_bones",
    "summarize_mesh_uvs",
    "summarize_mesh_workspace",
    "validate_mesh_asset_rebuild",
    "validate_mesh_export",
    "mesh_edit_operation_changed_channel",
    "validate_mesh_edit_operation_coverage",
    "validate_mesh_edit_operations",
    "mesh_edit_operations_from_dicts",
    "mesh_edit_operations_to_dicts",
]
